### ISSUE TITLE
组件u-calendar.vue 中 dayjs 报错

### ISSUE THREAD

**Issue by chenchaohan** [ijry/uview-plus#1]
10:47:42.230 vite v2.9.12 building for development...
10:47:48.908 [vite]: Rollup failed to resolve import "dayjs" from "E:\tansuo-uview-plus\uni_modules\uview-plus\components\u-calendar\u-calendar.vue".
10:47:48.911 This is most likely unintended because it can break your application at runtime.
10:47:48.915 If you do want to externalize this module explicitly add it to
10:47:48.916 `build.rollupOptions.external`

**Comment by ijry** [comment]
你好试下npm i dayjs
