### ISSUE TITLE
u-grid 事件会执行两次

### ISSUE THREAD

**Issue by huangxinrui** [ijry/uview-plus#100]
执行下面代码 testEvent 会先传送一次带name的事件，第二次会传递 原生click事件

"uview-plus": "^3.1.29",

![image](https://user-images.githubusercontent.com/20434566/224967396-db490fed-7372-4ff2-9e67-1a307c56e6ee.png)

const testEvent = (event) => {
  debugger;
  console.log(event);
};

**Comment by ijry** [comment]
fixed
