### ISSUE TITLE
Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by alan-amazing** [ijry/uview-plus#104]
按照官方 Http请求 方法 
在main.js 引入js
`
export function createApp() {
  const app = createSSRApp(App);
  import('/config/request.js')

  app.use(uviewPlus);
  
  return {
    app
  }
}`

报错
`Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.`

**Comment by Onion17** [comment]
请问解决了吗？我也遇到了

**Comment by 919642993** [comment]
？

**Comment by ijry** [comment]
使用示例工程里的request引入
