### ISSUE TITLE
使用 u-swipe-action  组件报错，[渲染层错误] TypeError: Cannot read property 'nv_disabled' of undefined     at nv_sizeChange 

### ISSUE THREAD

**Issue by changzhanpeng** [ijry/uview-plus#105]
引入组件就报错
![image](https://user-images.githubusercontent.com/82796772/227705063-98bbd221-0712-49ba-93f8-9787c8f61b00.png)

**Comment by changzhanpeng** [comment]
![image](https://user-images.githubusercontent.com/82796772/227705818-8163eb25-45e2-4bf7-84bf-00dcf7e1c7ec.png)
查看源码，我发现是有个地方的实例没有获取到，如上图， 我更改了     u-swipe-action-item 组件中 index.wxs 的部分逻辑，添加了一个 if 阻断，这样就不会报错了，但是不知道这么改会不会有什么其他问题，麻烦作者帮我看下，如果可以的话，修复一下这个问题。

**Comment by ijry** [comment]
已按此方案临时修复
