### ISSUE TITLE
uview-plus里的u-parse渲染html后linkTap点击事件无效，

### ISSUE THREAD

**Issue by MuseMatrix** [ijry/uview-plus#106]
![1679994871719](https://user-images.githubusercontent.com/17466084/228189097-741482b7-d8db-462d-a994-77b37646f372.png)

**Comment by wangzhongshun** [comment]
可以正常渲染，但是在app上 和 小程序上，都无法触发linkTap事件

**Comment by wangzhongshun** [comment]
可以正常渲染，但是在app上 和 小程序上，都无法触发linkTap事件；经过测试，在demo上也无法触发linkTap事件
