### ISSUE TITLE
u-image组件和v2.0展示形式不一样

### ISSUE THREAD

**Issue by DaDaDaBocai** [ijry/uview-plus#107]
举个例子：

`<u--image src="https://img01.yzcdn.cn/upload_files/2022/11/03/FjC1yBeheuMmgX6_nUWsAyAaJYqN.jpg!middle.jpg" mode="widthFix" width="200rpx" height="auto"></u--image>`

v2.0：这种情况下，图片的高度会自适应。

v3.0：图片不显示，排查发现高度为0

**Comment by ijry** [comment]
复制以上代码在3.0发现图片正常显示
