### ISSUE TITLE
calendar日历组件使用后产生错误，Cannot read properties of undefined (reading 'mpMixin')

### ISSUE THREAD

**Issue by callerlibrary** [ijry/uview-plus#108]
@ijry 
# 开发环境

vue3 + vite + ts 使用cli创建的项目，windows10，联想模拟器

### 在界面内引入组建后控制台就产生如下错误

![image](https://user-images.githubusercontent.com/96159769/228500138-6c01b268-57ae-4dba-ab3c-ace40c39f338.png)

### 在对照配置后发现按照官网npm安装配置最后一步对vite.congif.js做如下配置时也会产生相关错误
![image](https://user-images.githubusercontent.com/96159769/228500758-1fa734fa-0def-4d40-9208-5ef96d0989a8.png)

**Comment by ljb2458** [comment]
最新版在安卓平台会报错
exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'mpMixin' of undefined
 at  (app-service.js:7564:21)
 at  (app-service.js:14221:3)

**Comment by Libetr** [comment]
这个问题出现的原因是  uni_modules\uview-plus\components\u-calendar\header.vue  这个文件内的 mpMixin 报错
![image](https://github.com/ijry/uview-plus/assets/94942088/9ff2b7e1-c2ac-421f-91ca-f7d02f969de7)
需要自行修改
![image](https://github.com/ijry/uview-plus/assets/94942088/07065132-6fd5-422b-80d1-f7aa30389538)

**Comment by ijry** [comment]
fixed
