### ISSUE TITLE
在swiper中使用tabs组件bug

### ISSUE THREAD

**Issue by hzlzsm** [ijry/uview-plus#110]
在swiper中使用tabs组件时，非当前swiper-item中的tabs中的scrollLeft位置不对
![test4](https://user-images.githubusercontent.com/73974273/230534133-92d20980-5b29-48d0-b9fd-9c36fbd51bc0.gif)
应该是下面的属性没有考虑到这种情况，这两种属性中多计算了swiper的宽度
![企业微信截图_20230407103823](https://user-images.githubusercontent.com/73974273/230534149-fd959250-fd7e-422b-b546-1cc8ba41e3db.png)

**Comment by hzlzsm** [comment]
目前我的临时处理方法是把swiper的宽度传进去，在里面再处理。从组件化的思路上，这并不是一种正确的方法。
![企业微信截图_20230407135245](https://user-images.githubusercontent.com/73974273/230550154-dfc7c911-b6fa-4bfa-9b8f-0c4c712b954a.png)

**Comment by ijry** [comment]
fixed@3.3.11
