### ISSUE TITLE
PC端点击 u-input 点击 clear 没清空效果，移动端则正常

### ISSUE THREAD

**Issue by 1014156094** [ijry/uview-plus#117]
![image](https://user-images.githubusercontent.com/16074662/233043924-11f1dd41-ce8e-454d-a9d1-8234b3309cea.png)

**Comment by linqingjie** [comment]
> ![图像](https://user-images.githubusercontent.com/16074662/233043924-11f1dd41-ce8e-454d-a9d1-8234b3309cea.png)

点击clear会触发@clear事件，清空逻辑要自己写

**Comment by 1014156094** [comment]
> > ![图像](https://user-images.githubusercontent.com/16074662/233043924-11f1dd41-ce8e-454d-a9d1-8234b3309cea.png)
> 
> 点击clear会触发@clear事件，清空逻辑要自己写

@clear 没有触发

**Comment by ijry** [comment]
fixed

**Comment by 1014156094** [comment]
> > ![图像](https://user-images.githubusercontent.com/16074662/233043924-11f1dd41-ce8e-454d-a9d1-8234b3309cea.png)
> 
> 点击clear会触发@clear事件，清空逻辑要自己写

但移动端是不需要自己写的
