### ISSUE TITLE
文档组件名错误

### ISSUE THREAD

**Issue by zjtt** [ijry/uview-plus#118]
https://uiadmin.net/uview-plus/components/image.html
![image](https://user-images.githubusercontent.com/22001904/234196305-57ef3922-6a7c-4849-ad4a-d90b36b4dee2.png)
应该为u-image

**Comment by linqingjie** [comment]
> https://uiadmin.net/uview-plus/components/image.html ![image](https://user-images.githubusercontent.com/22001904/234196305-57ef3922-6a7c-4849-ad4a-d90b36b4dee2.png) 应该为u-image
由于在nvue下，u-image名称被uni-app官方占用，在nvue页面中请使用u--image名称，在vue页面中使用u--image或者u-image均可

**Comment by zjtt** [comment]
收到啦，谢谢

**Comment by ijry** [comment]
已支持全新前缀up-
