### ISSUE TITLE
不支持组合式api的写法吗

### ISSUE THREAD

**Issue by web0924** [ijry/uview-plus#122]
对于需要用到组件ref的情况，请问组合式写法怎么办
例如： this.$refs.uToast

**Comment by linqingjie** [comment]
> 对于需要用到组ref的情况，请问组合式写法怎么办 例如： this.$refs.uToast

const uToast=ref(null);
uToast.value.show();
这样子调用

**Comment by canyonwan** [comment]
建议先学习vue3语法

**Comment by chanhuiwumeng** [comment]
<u-toast ref="uToast"></u-toast>
<button @click='click'>click</button>
<script setup> 
const uToast = ref(null)
const click = ()=>{
console.log(uToast.value)
}
</script>
这样输出值一直为空 消息弹窗怎么展示成功呢?

**Comment by ijry** [comment]
ref="uToastRef"

**Comment by chergn** [comment]
不如https://sutras.github.io/sard-uniapp-docs/#/guide/intro 组件库
