### ISSUE TITLE
<u-calendar :show="show"></u-calendar>组件出现问题无法显示

### ISSUE THREAD

**Issue by zygDemo** [ijry/uview-plus#127]

**Comment by zygDemo** [comment]
<u-datetime-picker
                :show="show"
                v-model="value1"
                mode="datetime"
        ></u-datetime-picker>
这个组件也是同样问题

**Comment by zygDemo** [comment]
u-datetime-picker

**Comment by ijry** [comment]
你是不是没安装dayjs

**Comment by zygDemo** [comment]
> 

是的 用的uview的时间格式化api就没用day.js

**Comment by zygDemo** [comment]
@ijry 是的 用的uview的时间格式化api就没用day.js

**Comment by zygDemo** [comment]
官方文档的部分组件为什么demo显示不出来
![image](https://github.com/ijry/uview-plus/assets/45715263/b6fcf8ef-5078-4364-9ea8-a03aa3ac356e)

**Comment by yangxuy** [comment]
请问使用hbuildx创建的项目没有packages.json 怎么安装day.js
