### ISSUE TITLE
Popup 弹出层设置zIndex并开启遮罩会被遮罩盖住内容

### ISSUE THREAD

**Issue by xkfe** [ijry/uview-plus#136]
封装的组件不应该是传了zIndex并开启遮罩的情况下，组件里面的遮罩设置传入的zIndex-1吗

**Comment by chergn** [comment]
弹出层的高度应该控制一下
![image](https://github.com/user-attachments/assets/e4842da6-8f7c-4a96-b750-f9962c6cb98f)
不然满屏都是
