### ISSUE TITLE
px修改为rpx之后，许多组件显示异常

### ISSUE THREAD

**Issue by asd8855** [ijry/uview-plus#138]
因为是在组件内部写死的，px修改为rpx之后，许多组件显示异常

**Comment by zengyuanqiu** [comment]
当使用setConfig配置单位为rpx，组件内部没做处理，使组件尺寸只有原尺寸的一半大小

**Comment by ijry** [comment]
系原uview2问题暂时需要时间确认优化方案

**Comment by ijry** [comment]
fixed@3.3.15
