### ISSUE TITLE
u-back-top组件导致编译app时白屏无法启动

### ISSUE THREAD

**Issue by BoxCode7** [ijry/uview-plus#141]
使用编译成app时使用u-back-top组件会导致白屏无法启动产生以下报错：
`reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'mpMixin' of undefined`

解决方式是将：
`mixins: [uni.$u.mpMixin, uni.$u.mixin,props],`
改成：
`mixins: [mpMixin, mixin, props],`

**Comment by ijry** [comment]
感谢，已修复。
