### ISSUE TITLE
u-swipe-action-item会报“渲染层错误”

### ISSUE THREAD

**Issue by J1angyue** [ijry/uview-plus#142]
向右滑动时控制台报错：[渲染层错误] TypeError: Cannot read property 'nv_disabled' of undefined
使用静态数据滑动不会报错，比如：
`<u-swipe-action-item v-for="customer in list" :key="customer.id" :options="[{text: "删除"}]">`
使用响应式数据则会报错，比如：
`<u-swipe-action-item v-for="customer in list" :key="customer.id" :options="swipeOptions">
`
`const swipeOptions =  computed(() => {
  const opts = []
  // 有删除权限
  if (hasPermi(['customer:delete'])) {
    opts.push({
      text: '删除'
    })
  }
  return opts
})`

uview-plus版本：3.1.35

![image](https://github.com/ijry/uview-plus/assets/39160902/062ce3aa-a5fd-4957-946b-bef91e0ebfa0)

**Comment by trcat** [comment]
+1

**Comment by trcat** [comment]
可以看看这个 issue，虽然只能通过源码解决，https://github.com/ijry/uview-plus/issues/105
