### ISSUE TITLE
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors

### ISSUE THREAD

**Issue by mofashi998** [ijry/uview-plus#145]
以上错误是由于违反了自定义组件的一些特殊规则所致。
以上英文翻译：组件的wxss文件中禁止使用 标签名选择器，id选择器和属性选择器；

![image](https://github.com/ijry/uview-plus/assets/18150343/ea7fe09c-f233-4118-b1b7-2957c9512778)

**Comment by cgx452306705** [comment]
请问下 你解决了吗

**Comment by ijry** [comment]
已修复
