### ISSUE TITLE
uniapp 使用uview-plus u-form组件一直报错，页面无法显示

### ISSUE THREAD

**Issue by pandaFront** [ijry/uview-plus#149]
HBuilder X 3.8.7
uview-plus: 3.1.36

使用u-from、u--from、up-from在内置浏览器预览一直报错，chrome浏览器能正常显示，打包成app也无法显示。

错误提示[Vue warn]: Unhandled error during execution of async component loader

**Comment by ppdxzz** [comment]
同楼主，我在微信小程序直接报SyntaxError: Unexpected token .

**Comment by ijry** [comment]
发个demo代码方便调试。

**Comment by ppdxzz** [comment]
> 发个demo代码方便调试。

我用的就是官网的例子，直接复制过去测试的，结果发现内置浏览器模式会报错，微信开发者工具运行就不会，我现在在开发者工具上面用呢。

**Comment by ijry** [comment]
https://uview-plus.jiangruyi.com/h5/#/pages/componentsC/form/form试下演示。

**Comment by feige-2011** [comment]
修复了么，我最新安庄也是，会白屏
