### ISSUE TITLE
u-datetime-picker报错

### ISSUE THREAD

**Issue by chenyexuan** [ijry/uview-plus#15]
dayjs.js在hbuilderx构建的vue3项目中并没有附带，无法像你们用改引用一样直接用项目自带的dayjs，而项目自带的第三方包还需要另外找方法下载，不是像用uniapp-cli一样直接导入就行了，因为vue3使用的是vite，vite其实就是rollup简化版，无法像webpack一样解析require，这样又得去找插件配置解析方法，所以还是带上ESmodules形式的dayjs一起封进去吧

**Comment by chenyexuan** [comment]
刚找了一圈，原理是这个原理，然后装这个报那个，最后还是放弃了，回来在项目根目录上npm init -y用dayjs的npm包解决报错，我还是希望你们能一起搞进去，或者使用的时候写明依赖

**Comment by 13799433448** [comment]
> 刚找了一圈，原理是这个原理，然后装这个报那个，最后还是放弃了，回来在项目根目录上npm init -y用dayjs的npm包解决报错，我还是希望你们能一起搞进去，或者使用的时候写明依赖

关于这个： 
[npm配置](https://uiadmin.net/uview-plus/components/npmSetting.html)
![image](https://user-images.githubusercontent.com/52238305/190982937-5b3ac728-106f-4cbe-8608-f0db2f34d0d7.png)

[hbuilder导入](https://uiadmin.net/uview-plus/components/downloadSetting.html)
![image](https://user-images.githubusercontent.com/52238305/190983031-761ba291-ae57-4d3e-a5b8-a6979f688645.png)

写的比较隐蔽 很抱歉
