### ISSUE TITLE
在 app.vue 中使用 u-tabbar 组件报错

### ISSUE THREAD

**Issue by Abernethy-BY** [ijry/uview-plus#150]
### app.vue 
``` vue
<script lang="ts" setup>
const active = ref('home')
const value1 = ref('home')
function change1(value: string) {
  consola.log(value)
}
function click1(e) {
  consola.log('click1', e)
}
</script>

<template>
  <div>
    <router-view />
    <u-tabbar
      :value="value1"
      :fixed="false"
      :placeholder="false"
      :safe-area-inset-bottom="false"
      class="tabber-content absolute bottom-0"
      @change="change1"
    >
      <u-tabbar-item text="首页" icon="home" @click="click1" />
      <u-tabbar-item text="放映厅" icon="photo" @click="click1" />
      <u-tabbar-item text="直播" icon="play-right" @click="click1" />
      <u-tabbar-item text="我的" icon="account" @click="click1" />
    </u-tabbar>
  </div>
</template>
```

### page.json
```json
{
  "easycom": {
		"custom": {
			"^u--(.*)": "uview-plus/components/u-$1/u-$1.vue",
			"^up-(.*)": "uview-plus/components/u-$1/u-$1.vue",
	        "^u-([^-].*)": "uview-plus/components/u-$1/u-$1.vue"
		}
	},
  "globalStyle": {
    "backgroundColor": "@bgColor",
    "backgroundColorBottom": "@bgColorBottom",
    "backgroundColorTop": "@bgColorTop",
    "backgroundTextStyle": "@bgTxtStyle",
    "navigationBarBackgroundColor": "#000000",
    "navigationBarTextStyle": "@navTxtStyle",
    "navigationBarTitleText": "Starter-Uni",
    "navigationStyle": "custom"
  },
  "pages": [
    { "path": "pages/index" },
    { "path": "pages/splash" },
    { "path": "pages/dashboard" }
  ]
}
```

### error info：
![image](https://github.com/ijry/uview-plus/assets/69035266/83765edc-1964-431e-b821-75b2132dfbf8)

### Reproduction:
https://github.com/HW-maintenance/HW_maintenance_app.git

### core dependencies
{
    "@dcloudio/uni-app": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-components": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-h5": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3071220230331002",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3071220230331002",
    "uview-plus": "^3.1.35",
    "vue": "^3.2.47",
}

**Comment by ijry** [comment]
小程序/uni-app并不支持app.vue里定义template
