### ISSUE TITLE
【u-list】u-list超过1屏的内容时，在列表区域内，下拉刷新（系统原生）无响应

### ISSUE THREAD

**Issue by beSmallFish** [ijry/uview-plus#160]
微信小程序
1.u-list超过1屏的内容时，在列表区域内，下拉刷新（系统原生）无响应.  
2.若不使用u-list， 直接<view v-for...> 这样添加， 下拉刷新正常
3.提议：是否能增加u-refresh组件 以配合 u-list进行自定义的下拉刷新功能

**Comment by ijry** [comment]
已增加兼容scroll-view相关的下拉刷新事件
