### ISSUE TITLE
使用u-button的时候想要通过修饰符阻止不了冒泡，无论是.native.stop还是.stop都不行，会报underfined的错误

### ISSUE THREAD

**Issue by GdgmPhs** [ijry/uview-plus#162]
![777](https://github.com/ijry/uview-plus/assets/50160846/c4f68988-f139-47ba-929a-208722a2a9f9)
![888](https://github.com/ijry/uview-plus/assets/50160846/d0626486-a71f-4056-bd1b-8fc94ecae368)

**Comment by ijry** [comment]
在 Vue 3 中，@click.native 被替换为 @click，因为 Vue 3 默认会使用 addEventListener() 来监听原生的事件。

**Comment by moshanghan** [comment]
https://github.com/ijry/uview-plus/issues/733#issuecomment-2965159275
