### ISSUE TITLE
DatetimePicker文档示例错误

### ISSUE THREAD

**Issue by ban-xian** [ijry/uview-plus#164]
DatetimePicker文档上格式化示例里通过ref定义的datetimePicker，使用datetimePicker时，应该是datetimePicker.value.setFormatter，目前是datetimePicker.setFormatter

![image](https://github.com/ijry/uview-plus/assets/72494850/6be79551-95cf-4363-9355-53961036c47d)

**Comment by ijry** [comment]
fixed
