### ISSUE TITLE
Image组件表现异常

### ISSUE THREAD

**Issue by hi-noikiy** [ijry/uview-plus#178]
##### 代码
<img width="878" alt="image" src="https://github.com/ijry/uview-plus/assets/32630320/267529d4-b5f2-46e7-bf8c-c5766ae7e472">

##### 表现
<img width="435" alt="image" src="https://github.com/ijry/uview-plus/assets/32630320/1cd0cef9-06e8-44d7-9b11-7b391c10f639">

##### 问题
无法自适应宽度，但是uni自身的image是可以的

**Comment by ijry** [comment]
因封装的组件有层级关系，w-full不能直接作用于内部的image，需要传入width参数为100%，否则有一个默认值为300px。
