### ISSUE TITLE
setConfig 修改全局配置无效

### ISSUE THREAD

**Issue by cordmaker** [ijry/uview-plus#179]
<img width="1440" alt="image" src="https://github.com/ijry/uview-plus/assets/83860971/3c2c460b-bded-4fca-8ce6-490f055f26f4">

<img width="1440" alt="image" src="https://github.com/ijry/uview-plus/assets/83860971/8d2ae4f6-8218-4a1b-a0c8-3ed379300c9f">

<img width="1440" alt="image" src="https://github.com/ijry/uview-plus/assets/83860971/e3f796c0-c3f0-434e-9c24-8c9e842c15ad">

uni.$u.setConfig 函数确实将配置深度合并了，但组件内部使用的 props 对象仍然是未进行深度合并之前的配置对象，这导致了 setConfig 函数不生效

**Comment by cordmaker** [comment]
> 这是由于uni-app sdk3.0目前存在一些问题，在一些环境下挂在$u会失败，导致不得不先将props写死。

哦哦，原来是这样、

**Comment by cordmaker** [comment]
> 这是由于uni-app sdk3.0目前有一些问题，在一些环境下挂在$u会失败，导致不得不先将props写死。

那可以写个判断，例如 `uni?.$u?.props?.textarea?.maxlength || defprops.textarea.maxlength`，同时在官方文档提示开发者：可能在不同平台可能会导致 setConfig 函数不生效。这样至少在部分平台不会有问题，可以照顾到大部分开发者。

**Comment by heihei001** [comment]
> 这是由于uni-app sdk3.0目前有一些问题，在一些环境下挂在$u会失败，导致不得不先将props写死。

快2025年了，在web端setConfig还是不生效的
