### ISSUE TITLE
swiper点击事情重复触发

### ISSUE THREAD

**Issue by lping101315** [ijry/uview-plus#182]
版本：uview-plus3.0
hbuilder:3.8.12.20230817
vue:3.0
描述：
swiper组件中swiper-item 的$emit传click到u-swiper会触发u-swiper本身的click事件，导致两次触发click，第一次回调值为swiper-item，第二次为u-swiper的click对象。

代码：
temp
`<view class="swip">
				 <u-swiper @click="to_swiper_detail" :list="swipt_list" keyName="image" showTitle :autoplay="true"  class="swip-box" height="360rpx"></u-swiper>
			</view>`

script:
`to_swiper_detail(e){
				console.log(e)
			},`

打印结果：
![image](https://github.com/ijry/uview-plus/assets/30251696/d63ff9ca-aaaf-4091-be47-cd030c92479c)

过度方案：
把u-swiper.vue里面的
`clickHandler(index) {
				this.$emit(click', index)
			}`

改成：
`clickHandler(index) {
				this.$emit('on-click', index)
			}`

打印结果正常：
![image](https://github.com/ijry/uview-plus/assets/30251696/142c15ba-3363-4393-9bbd-3d912204303a)

**Comment by ijry** [comment]
fixed
