### ISSUE TITLE
vue3 使用 uToast 时 ref 获取不到组件实例

### ISSUE THREAD

**Issue by LiangXixixi** [ijry/uview-plus#183]
<u-toast ref="uToast"></u-toast>

const uToast = ref<any>(null)

uToast.value!.show({
	type: 'success',
	title: '发送成功',
	icon: false
})
`
![image](https://github.com/ijry/uview-plus/assets/50560783/8216560a-3926-4d14-b0a6-f39527d7543e`)

**Comment by LiangXixixi** [comment]
![image](https://github.com/ijry/uview-plus/assets/50560783/7a033248-852f-463a-84f3-80ead8ae599d)
打印出来的ref是vue实例，并没有获取到u-toast，使用的是uniapp+vite+vue3+uview-plus

**Comment by LiangXixixi** [comment]
![image](https://github.com/ijry/uview-plus/assets/50560783/ea8c780f-4f7d-43e7-b11d-af1f860286e0)
上图为具体代码，加载时就有很多警告，如下
![image](https://github.com/ijry/uview-plus/assets/50560783/2f763b3e-9be4-4e30-b431-713072d5cba4)

**Comment by LiangXixixi** [comment]
解决了，ref不知道为什么不能定义成官方文档一样的名字，不然就不行，如下图

![image](https://github.com/ijry/uview-plus/assets/50560783/80f0d4b2-f19b-4e0b-a09e-d76a3e84cf37)

**Comment by ijry** [comment]
因为与组件重名冲突了
