### ISSUE TITLE
【微信小程序】safeAreaInsetBottom 为 true 不起作用

### ISSUE THREAD

**Issue by quulu** [ijry/uview-plus#189]
<img width="509" alt="image" src="https://github.com/ijry/uview-plus/assets/12093189/0b6f3104-1f8b-4c98-b31e-8ed41a4d7d62">
safeAreaInsetBottom 设置为 true 不起作用

**Comment by quulu** [comment]
<img width="351" alt="image" src="https://github.com/ijry/uview-plus/assets/12093189/c9375676-4de8-4d65-b6b7-7d6da7c19de5">

**Comment by ijry** [comment]
引入index.scss了吗

**Comment by Guocheng-c** [comment]
> 引入index.scss了吗

怎么引入，我也碰到这个问题，h5正常，小程序上面高度不生效
