### ISSUE TITLE
IndexList 索引列表 高度错误

### ISSUE THREAD

**Issue by zzz-hwx** [ijry/uview-plus#193]
给<scroll-view>和<list>组件设置高度时，`scrollViewHeight`来自系统屏幕高度`this.sys.windowHeight`（单位默认px） - 传入的参数`customNavHeight`（单位可通过`uni.$u.config.unit`设置）
如果开发者设置了默认单位`uni.$u.config.unit`为`rpx`
`customNavHeight`单位为`rpx`
`this.sys.windowHeight`单位为`px`
导致组件内部单位不一致
IndexList 索引列表组件展示高度错误

**Comment by zzz-hwx** [comment]
![image](https://github.com/ijry/uview-plus/assets/51980221/6d99beda-c6a7-4b49-8b06-3052fd5e1762)

**Comment by ijry** [comment]
已优化
