### ISSUE TITLE
u-popup 在微信里面 弹出动画有时候失效  vue2版本一直存在的bug 

### ISSUE THREAD

**Issue by idujiayou** [ijry/uview-plus#194]
需要在u-transition组件内部 vueEnter 函X数内加上50ms的延迟才正常
<img width="812" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/55a5fa6a-4304-44d8-be07-fb8128b460a9">

**Comment by ijry** [comment]
this.delay()?

**Comment by idujiayou** [comment]
@ijry 
<img width="788" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/6a50559c-2408-42c0-a305-1bcf101ca116">
this.delay 是我针对微信小程序做了一个延迟50ms的处理 延迟过后 弹窗动画还正常

**Comment by monsterxwx** [comment]
> @ijry <img alt="image" width="788" src="https://user-images.githubusercontent.com/16297776/278363058-6a50559c-2408-42c0-a305-1bcf101ca116.png"> this.delay 是我针对微信小程序做了一个延迟50ms的处理 延迟过后 弹窗动画才正常

老哥，我用你这个在模拟器上挺流畅的，但是在真机上体验第一次很流畅，第二次第三次点击的时候就感觉卡卡的是什么问题

**Comment by idujiayou** [comment]
> ，第二次第三次点击的
你这边使用了新版本吗 新版版我看他之前自定义的nextTick  改成了 waitTick
<img width="875" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/f992f07d-414b-445c-8d3a-99451868e271">

**Comment by idujiayou** [comment]
> @idujiayou
> 
> 老哥，我用你这个在模拟器上挺流畅的，但是在真机上体验第一次很流畅，第二次第三次点击的时候就感觉卡卡的是什么问题

我试了一下新版的 已经修复了这问题了

**Comment by monsterxwx** [comment]
@idujiayou 我刚刚重新更新了下新版，第一次点击确实是有动画效果的，不过多点几次还是有概率丢失掉出现动画的问题，难道是我使用的姿势不对？意思是现在不需要加上你这个了是吗

**Comment by idujiayou** [comment]
> @idujiayou 我刚刚重新更新了下新版，第一次点击确实是有动画效果的，不过多点几次还是有概率丢失掉出现动画的问题，难道是我使用的姿势不对？意思是现在不需要加上你这个了是吗
有了其实就不用加了我代码    要加的话 把 await nextTick  改成  await waitTick  我怀疑是因为 nextTick用的是vue 导致50ms执行的太频繁导致卡顿
