### ISSUE TITLE
你们自定义导航栏里面的自定义导航栏内容的代码写错了,template和u-navbar的标签位置写反了

### ISSUE THREAD

**Issue by ljgx** [ijry/uview-plus#195]
你们自定义导航栏里面的自定义导航栏内容的代码写错了,template和u-navbar的标签位置写反了   ,而且你们这个自定义导航我使用了之后报错 vendor.js? [sm]:2906 TypeError: Cannot read property 'deepMerge' of undefined   和  vendor.js? [sm]:2906 TypeError: Cannot read property 'addUnit' of undefined

**Comment by ijry** [comment]
是指文档写错了？

**Comment by ljgx** [comment]
是的,你的文档里面的代码标签位置也错了,你可以去看一下,Navbar 自定义导航栏 下面 自定义导航栏内容  这个标题里面的代码,至于报错的,我忘记了当时是什么情况了
![03A21D3C77F5A79E545438926358A3DF](https://github.com/ijry/uview-plus/assets/59424192/5647b605-20c2-4849-804b-89e9e2fe83f6)

**Comment by ijry** [comment]
已修正感谢
