### ISSUE TITLE
按钮文档里面细节不完善

### ISSUE THREAD

**Issue by ljgx** [ijry/uview-plus#196]
你们文档里面的按钮中一个例子(定义需要用到的外部样式),里面ref和reactive 都使用了,是否可以完善一下文档,把reactive也引入一下?

**Comment by ljgx** [comment]
抱歉,原来是单人开发的,辛苦了

**Comment by ijry** [comment]
已更新

**Comment by chergn** [comment]
不如https://sutras.github.io/sard-uniapp-docs/#/guide/intro 组件库
