### ISSUE TITLE
u-picker点击取消后需要自己绑定cancel事件去关闭弹框，而不是组件自己处理

### ISSUE THREAD

**Issue by tt-cell** [ijry/uview-plus#199]

**Comment by ijry** [comment]
为了便于自定义拦截取消操作

**Comment by tt-cell** [comment]
是的，我需要一个一个去自定义取消



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ijry/uview-plus] u-picker点击取消后需要自己绑定cancel事件去关闭弹框，而不是组件自己处理 (Issue #199)




 
为了便于自定义拦截取消操作
