### ISSUE TITLE
iPhone 11  版本 ios 13  14运行在小程序上会白屏

### ISSUE THREAD

**Issue by baseSky** [ijry/uview-plus#2]
iPhone 11  版本 ios 13  14运行在小程序上会白屏

**Comment by ijry** [comment]
> iPhone 11  版本 ios 13  14运行在小程序上会白屏

最新版本试了iphone11上微信小程序支付宝小程序都正常

**Comment by baseSky** [comment]
ios 版本在13- 14之间才会，最新版本不会

**Comment by ijry** [comment]
暂无测试条件
