### ISSUE TITLE
tabs组件滑块不居中显示

### ISSUE THREAD

**Issue by littlecai-1021** [ijry/uview-plus#205]
在uniapp中使用tabs组件，文字底部滑块不居中显示。
![WechatIMG3](https://github.com/ijry/uview-plus/assets/148963543/ee56ebc5-e7f0-43de-9dab-f2fa1377029b)

**Comment by ijry** [comment]
需要上下文代码样式复现

**Comment by ygq-future** [comment]
`<script setup>
import { computed } from 'vue'

const props = defineProps({
  windowHeight: Number,
})
const height = computed(() => `${ props.windowHeight - uni.upx2px(80) }px`)

const current = ref(0)
const tabs = [{ name: '萌配列表' }, { name: '我的萌配' }]
</script>

<template>
  <view class="wrapper" :style="{ height }">
    <view class="tabs">
      <u-tabs
        :current="current"
        :list="tabs"
        line-height="5rpx"
        lineColor="#ffab38"
        :lineWidth="50"
        :itemStyle="{ height: '60rpx' }"
        :inactiveStyle="{ color: '#bdc3c7' }"
        :activeStyle="{
          color: '#ffab38',
          fontWeight: 'bold',
          fontSize: '35rpx'
        }"
      />
    </view>
  </view>
</template>`
自定义滑块长度后就会不居中

**Comment by qcjackman** [comment]
请问解决了吗，遇到同样的问题，不明白哪里错了

**Comment by ygq-future** [comment]
> 请问解决了吗，遇到同样的问题，不明白哪里错了 ![image](https://private-user-images.githubusercontent.com/12554120/298061468-81dba662-d5ac-4eaf-81c8-cd87db315c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjY2ODUsIm5iZiI6MTcwNTY2NjM4NSwicGF0aCI6Ii8xMjU1NDEyMC8yOTgwNjE0NjgtODFkYmE2NjItZDVhYy00ZWFmLTgxYzgtY2Q4N2RiMzE1YzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyMTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YjNhZDg5YzJjYWU5NTA3NGRiY2ZhOTg1M2Q3M2Y1MzE2NGNmZmY4ZDNmZjAxZDEwY2ZjYTJmZWUyNmRkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ExIeTkwdtG7IgTa7eagWpD-5z35RmdfnHARa2PqRZA)
> 
> ```
> <template>
> 	<u-tabs :list="list" :current="tabCur" lineWidth="60" lineHeight="6"></u-tabs>
> </template>
> 
> <script>
> 	import {
> 		reactive,
> 		toRefs
> 	} from 'vue'
> 
> 	export default {
> 		setup() {
> 			const data = reactive({
> 				tabCur: 0,
> 				list: [{
> 					id: 1,
> 					name: 'abc1'
> 				}, {
> 					id: 2,
> 					name: 'abc2'
> 				}, {
> 					id: 3,
> 					name: 'abc3'
> 				}, {
> 					id: 4,
> 					name: 'abc4'
> 				}, {
> 					id: 5,
> 					name: 'abc5'
> 				}, {
> 					id: 6,
> 					name: 'abc6'
> 				}, {
> 					id: 7,
> 					name: 'abc7'
> 				}]
> 			})
> 
> 			const bindTabChangeEvent = (e) => {
> 				console.log("bindTabChangeEvent:", e)
> 				data.tabCur = e.index
> 			}
> 
> 			return {
> 				...toRefs(data),
> 
> 				bindTabChangeEvent
> 			}
> 		}
> 	}
> </script>
> 
> <style lang="scss" scoped>
> 
> </style>
> ```

不要用rpx，你这里肯定全局设置了单位为rpx，如果全局设置了，这里就写lineWidth="30px"反正不能用rpx就可以

**Comment by qcjackman** [comment]
> > 请问解决了吗，遇到同样的问题，不明白哪里错了 ![image](https://private-user-images.githubusercontent.com/12554120/298061468-81dba662-d5ac-4eaf-81c8-cd87db315c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjY2ODUsIm5iZiI6MTcwNTY2NjM4NSwicGF0aCI6Ii8xMjU1NDEyMC8yOTgwNjE0NjgtODFkYmE2NjItZDVhYy00ZWFmLTgxYzgtY2Q4N2RiMzE1YzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyMTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YjNhZDg5YzJjYWU5NTA3NGRiY2ZhOTg1M2Q3M2Y1MzE2NGNmZmY4ZDNmZjAxZDEwY2ZjYTJmZWUyNmRkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ExIeTkwdtG7IgTa7eagWpD-5z35RmdfnHARa2PqRZA)
> > ```
> > <template>
> > 	<u-tabs :list="list" :current="tabCur" lineWidth="60" lineHeight="6"></u-tabs>
> > </template>
> > 
> > <script>
> > 	import {
> > 		reactive,
> > 		toRefs
> > 	} from 'vue'
> > 
> > 	export default {
> > 		setup() {
> > 			const data = reactive({
> > 				tabCur: 0,
> > 				list: [{
> > 					id: 1,
> > 					name: 'abc1'
> > 				}, {
> > 					id: 2,
> > 					name: 'abc2'
> > 				}, {
> > 					id: 3,
> > 					name: 'abc3'
> > 				}, {
> > 					id: 4,
> > 					name: 'abc4'
> > 				}, {
> > 					id: 5,
> > 					name: 'abc5'
> > 				}, {
> > 					id: 6,
> > 					name: 'abc6'
> > 				}, {
> > 					id: 7,
> > 					name: 'abc7'
> > 				}]
> > 			})
> > 
> > 			const bindTabChangeEvent = (e) => {
> > 				console.log("bindTabChangeEvent:", e)
> > 				data.tabCur = e.index
> > 			}
> > 
> > 			return {
> > 				...toRefs(data),
> > 
> > 				bindTabChangeEvent
> > 			}
> > 		}
> > 	}
> > </script>
> > 
> > <style lang="scss" scoped>
> > 
> > </style>
> > ```
> 
> 不要用rpx，你这里肯定全局设置了单位为rpx，如果全局设置了，这里就写lineWidth="30px"反正不能用rpx就可以

还真是，感谢🙏
