### ISSUE TITLE
抖音小程序端safeAreaInsetBottom不起效果

### ISSUE THREAD

**Issue by fyp1212** [ijry/uview-plus#207]
![QQ图片20231107135152](https://github.com/ijry/uview-plus/assets/115349838/42922280-dd79-4e76-afc8-28c4d7f689d7)
![QQ图片20231107135158](https://github.com/ijry/uview-plus/assets/115349838/8ec4e63b-45da-4419-a0ba-03e791228929)
为什么这个微信小程序的安全区safeAreaInsetBottom能其效果，而抖音小程序端的安全区safeAreaInsetBottom不起效果啊

**Comment by fyp1212** [comment]
指点一下

**Comment by ijry** [comment]
已修复
