### ISSUE TITLE
启动时报错   Cannot read properties of undefined (reading 'deepMerge')

### ISSUE THREAD

**Issue by zhoubo416** [ijry/uview-plus#209]
TypeError: Cannot read properties of undefined (reading 'deepMerge')
<img width="546" alt="image" src="https://github.com/ijry/uview-plus/assets/66418017/6c2dfb39-2f14-4b68-93ee-e2a05a4f5802">

**Comment by ijry** [comment]
在什么环境什么场景下？

**Comment by zhoubo416** [comment]
抱歉我的问题，配置信息搞错了
