### ISSUE TITLE
Slider组件v-model数值的双向绑定存在问题，以及缺少部分emits声明

### ISSUE THREAD

**Issue by linwei921219** [ijry/uview-plus#214]
1. 组件中缺少"update:modelValue"，"input"这两个emits的声明，控制台中有关于这方面的黄色警告报错
2. v-model数值的双向绑定不可用，控制台中有关于"value"的黄色警告报错

**Comment by linwei921219** [comment]
![微信图片_20231116093829](https://github.com/ijry/uview-plus/assets/22364682/edaab5d7-7a14-469b-9db1-f0bed9433b4d)
![微信图片_20231116094014](https://github.com/ijry/uview-plus/assets/22364682/f101e16e-3408-440f-8e0e-99f207a82852)

**Comment by ijry** [comment]
已修复3.1.40（2023-11-16）

**Comment by linwei921219** [comment]
> 已修复3.1.40（2023-11-16）

牛逼！
