### ISSUE TITLE
u-cell未设置icon，遗留的左侧left-icon-wrap空view容器会导致margin-right存在4px空隙

### ISSUE THREAD

**Issue by lovewinders** [ijry/uview-plus#215]
> 很多场景并非都会设置icon属性图标，设置icon和不设置icon会导致左侧间距存在误差4px，基本肉眼可见左侧竖向不齐，建议参考uView2.0改进代码，改进方案参考下面所提建议；

> 源码定位分析截图

<img width="1477" alt="image" src="https://github.com/ijry/uview-plus/assets/22837419/468e9ab7-da22-4b78-aa42-e9f6de82b830">

> 运行时定位分析截图
<img width="548" alt="image" src="https://github.com/ijry/uview-plus/assets/22837419/521cceea-1cab-40c7-9613-5f436b483be4">

> 改进意见参考uView2.0源码截图

![image](https://github.com/ijry/uview-plus/assets/22837419/24ef15d7-2ab0-46f6-9f20-8fcc366ca200)

**Comment by ijry** [comment]
3.1.41（2023-11-18）已修复感谢

**Comment by lovewinders** [comment]
牛逼
