### ISSUE TITLE
官方文档【快速上手】坑人啊

### ISSUE THREAD

**Issue by wusp1994** [ijry/uview-plus#216]
一直是白页，也不报错，我一直在尝试是我的配置哪里出了问题，结果是这个案例组件数据写错了。真的好烦啊。
![image](https://github.com/ijry/uview-plus/assets/26253981/5432b1ca-05a8-43b1-96c0-c111206aa8f8)

```js
<template>
  <u-action-sheet :list="list" v-model="show"></u-action-sheet>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const list = ref([
  {
    text: '点赞',
    color: 'blue',
    fontSize: 28
  },
  {
    text: '分享'
  },
  {
    text: '评论'
  }
]);

const show = ref(true);
</script>
```

**Comment by ijry** [comment]
哪里看着一样？

**Comment by wusp1994** [comment]
正确代码
不是list 而是 actions
`    <u-action-sheet :show="showSex"
                    :actions="actions"
                    title="请选择证件类型"
                    @close="showSex = false"
                    @select="OnSelectSexSelect">
    </u-action-sheet>`

**Comment by ijry** [comment]
已修正感谢
