### ISSUE TITLE
u-picker点击确定跟取消不会自动关闭

### ISSUE THREAD

**Issue by mzongx** [ijry/uview-plus#217]
复制官网的例子，点击取消跟确定不会自动隐藏弹框

**Comment by haiziohhue** [comment]
+1，一样 并且这个Bug看之前早就有了

**Comment by mzongx** [comment]
> +1，一样 并且这个Bug看之前早就有了

是啊，这种应该默认就要调用关闭的呀，每次都要手动关闭很麻烦

**Comment by ijry** [comment]
这是uview2的设计，为了兼容性暂时也没改。
