### ISSUE TITLE
input组件的change事件在pc端测试的时候生效,但是在真机测试的时候不生效

### ISSUE THREAD

**Issue by SKYE-iiii** [ijry/uview-plus#218]
input组件的change事件在pc端测试的时候生效,但是在真机测试的时候不生效

**Comment by ijry** [comment]
真机iOS/安卓还是小程序

**Comment by SKYE-iiii** [comment]
抱歉. 使用的方法有误. 在使用时是直接用js对input的绑定值进行了赋值 所以一直没有触发事件
