### ISSUE TITLE
uniapp 编译小程序后有很多 css 样式警告

### ISSUE THREAD

**Issue by iibrat** [ijry/uview-plus#220]
[pages/answers/answers] Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./uni_modules/uview-plus/components/u-icon/u-icon.wxss:26:1)
[pages/answers/answers] Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./uni_modules/uview-plus/components/u-loading-icon/u-loading-icon.wxss:26:1)
[pages/answers/answers] Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./uni_modules/uview-plus/components/u-button/u-button.wxss:26:1)

这些样式警告不知道有没有影响？？

**Comment by ijry** [comment]
已修复
