### ISSUE TITLE
u-navbar 组件，微信小程序=>真机调试=》高度塌陷问题

### ISSUE THREAD

**Issue by wusp1994** [ijry/uview-plus#222]
![image](https://github.com/ijry/uview-plus/assets/26253981/21a98c6d-d255-45d3-818e-800cc554fcab)
针对官方案例，直接对导航组件页面进行编译模式，然后真机调试，就会出现下图的高度塌陷问题。
![8268d73d08b2fa21e9b221663bb7773](https://github.com/ijry/uview-plus/assets/26253981/c259f73c-8272-4f84-a15a-7ab09f4587b2)

**Comment by ijry** [comment]
最新版实测了下真机ios/安卓微信均没有塌陷
