### ISSUE TITLE
uview-plus表单校验

### ISSUE THREAD

**Issue by Soumns777** [ijry/uview-plus#226]
uview-plus form组件在正常表单时设置规则是ok的,但是当使用循环遍历的表单时,setRules后并没有生效,不知道这种是什么情况呢?是不是可以优化一下呢?

**Comment by Soumns777** [comment]
我简单写了个demo https://github.com/Soumns777/mini-test-v3，有时间的话看下单表单和循环多表单的校验规则区别呢?
单表单的时候可以正常校验必填和附加的其他规则,但是在多表单的时候只剩下了校验必填,丢失了其他规则的校验

**Comment by Soumns777** [comment]
https://github.com/Soumns777/mini-test-v3

**Comment by ijry** [comment]
setRules存在就是因为在小程序等场景下props不支持传递函数，你这个封装了一层v-model:formRules="item.rules"用这个来传递，又丢失了。
