### ISSUE TITLE
LineProgress 线形进度条 函数表达式单词拼错

### ISSUE THREAD

**Issue by LEI-LJ** [ijry/uview-plus#229]
![image](https://github.com/ijry/uview-plus/assets/110337030/fbe68a60-3538-4ed4-9767-c49185f949f1)

const computedWidth = (type) => {
    if (type === 'plus') {
        percentage.value = uni.$u.range(0, 100, percentage.value + 10);
    } else {
        percentage.value = uni.$u.range(0, 100, percentage.value - 10);
    }
};

**Comment by ijry** [comment]
感谢已修复
