### ISSUE TITLE
没人遇到小程序上popup入场动画无效吗？点击直接就显示出来了，非小程序有入场动画

### ISSUE THREAD

**Issue by T-Inphic** [ijry/uview-plus#230]

**Comment by chengazhen** [comment]
小程序机制吧

**Comment by ijry** [comment]
是最新版本吗

**Comment by T-Inphic** [comment]
> 小程序机制吧

不清楚，反正删除这个就行了
<img width="1008" alt="image" src="https://github.com/ijry/uview-plus/assets/19276771/7fc6db13-fe03-48fe-87b0-16023613d47a">

**Comment by T-Inphic** [comment]
> 是最新版本吗

是最新版，没遇到吗，删除包里面的只在h5生效的标识就行了
<img width="954" alt="image" src="https://github.com/ijry/uview-plus/assets/19276771/8d85d2ce-2e9f-4e1f-acbc-bef01efd7b41">

**Comment by T-Inphic** [comment]
> 小程序机制吧

应该不是，把只在h5生效的标识删了就行了

**Comment by bsoprojects** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
