### ISSUE TITLE
input输入框前后插槽不生效&&是否可以添加一个密码显示隐藏icon及其功能

### ISSUE THREAD

**Issue by bean-chai** [ijry/uview-plus#235]
![image](https://github.com/ijry/uview-plus/assets/94820585/5ec572eb-e5bb-4633-bbe0-5ceda604ded1)
![image](https://github.com/ijry/uview-plus/assets/94820585/6d84a58d-2d8a-4ddd-b96c-a50c9d69d102)

**Comment by ijry** [comment]
代码贴出来看看
