### ISSUE TITLE
Calendar组件maxDate是否可修改为不能小于minDate，而不是不能小于当前时间

### ISSUE THREAD

**Issue by ban-xian** [ijry/uview-plus#238]
在实际需求中很有可能有最大可选时间在当前时间之前，比如最大时间只能选择到昨天，目前Calendar组件maxDate是限制的不能小于当前时间。

**Comment by Gorgeous-R** [comment]
是啊 你现在解决这个问题了，是不是只能maxDate大一天

**Comment by ijry** [comment]
已修复
