### ISSUE TITLE
input输入框添加clearable后，点击图标内容依旧展示

### ISSUE THREAD

**Issue by xiaofei159** [ijry/uview-plus#239]
input输入框添加clearable后，点击图标内容依旧展示，我在u-input组件中的valueChange方法中打印value发现被清空后又执行了一次，又执行的这一次将被清空前的值重新赋值

**Comment by xiaofei159** [comment]
input输入框添加clearable后，点击图标内容依旧展示，我在u-input组件中的valueChange方法中打印value发现被清空后又执行了一次，又执行的这一次将被清空前的值重新赋值

**Comment by jia58960** [comment]
大佬有解决该问题？

**Comment by chengazhen** [comment]
确实有这个问题
