### ISSUE TITLE
u-index-list 在自定义导航的时候，左边的索引触发激活的延迟

### ISSUE THREAD

**Issue by hedanto** [ijry/uview-plus#244]
u-index-list 在自定义导航的时候，同时设定custom-nav-height属性，当时左边的索引触发激活的延迟，比如A索引已经吸顶固定，但是索引的A字母还没激活，这个时候还要往上滑一个自定义导航的高度，才会高亮

**Comment by jinsiyan** [comment]
我也遇到这个问题了 怎么办

**Comment by ijry** [comment]
试下最新版重构了
