### ISSUE TITLE
u-popup组件放其他组件修改不了样式，h5正常，小程序不行

### ISSUE THREAD

**Issue by xiexikang** [ijry/uview-plus#246]
<u-popup :show="show">
        <view>
            <text>测试</text>
        </view>
        <up-button class="btn">按钮</up-button>
    </u-popup>

:deep(.u-button)也试过不行

**Comment by xiexikang** [comment]
` <u-popup :show="dataInfo.show">
        <view>
            <text>测试</text>
        </view>
        <up-button class="btn">按钮</up-button>
    </u-popup>`

**Comment by ijry** [comment]
小程序有一个要求注意，在deep时需要有一个父class节点。

**Comment by chergn** [comment]
`::v-deep` `/deep/` `>>>` `:v-deep()`都试了，不管用https://ask.csdn.net/questions/8140882

**Comment by ijry** [comment]
```
<script>
  export default {
    options: { styleIsolation: 'shared' },
  }
</script>
```
