### ISSUE TITLE
Swiper 轮播图组件Click事件触发两次Bug

### ISSUE THREAD

**Issue by Yjx710** [ijry/uview-plus#248]
问题如下：
`
<u-swiper
    :list="carouselData"
    indicator
    keyName="fontUrl"
    imgMode="scaleToFill"
    class="image"
    height="100%"
    :loading="loading"
    circular
    :interval="swiperConfig.interval"
    :duration="swiperConfig.duration"
    @click="handleSwiperClick"
  ></u-swiper>
`

const handleSwiperClick = (index) => {
  consolg.log(index)
}

这里的index会输出两次，一次是下标索引，另外一个是鼠标点击事件 

![image](https://github.com/ijry/uview-plus/assets/55580717/ff750d5c-472b-493b-90a0-5cad9ec48b8c) @ijry

**Comment by li-shifeng** [comment]
同样遇到了该问题
