### ISSUE TITLE
u-list为什么默认给了内联样式高度

### ISSUE THREAD

**Issue by WsProgrammer** [ijry/uview-plus#252]
![image](https://github.com/ijry/uview-plus/assets/34298947/00e3cad9-fd7f-4583-ab04-15376b6fa811)
![image](https://github.com/ijry/uview-plus/assets/34298947/0fb1ce54-35f8-4bb5-9e84-7011e4a6cda1)
u-list我明明没有写内联样式，为什么会默认有个内联样式把高度设置为设备高度啦

**Comment by ijry** [comment]
![image](https://github.com/ijry/uview-plus/assets/3102798/a71aa735-46dd-479d-8744-162def67f7c9)
