### ISSUE TITLE
Grid宫格布局文档编写错误以及设置border为true未出现边框

### ISSUE THREAD

**Issue by Yjx710** [ijry/uview-plus#253]
1. 文档编写错误之处，默认值为false

![image](https://github.com/ijry/uview-plus/assets/55580717/f4ec83e0-2069-4f8a-ada3-76c2530b38da)
![image](https://github.com/ijry/uview-plus/assets/55580717/c9e4ee08-b66a-4c61-8b52-ae67d3946c78)
![image](https://github.com/ijry/uview-plus/assets/55580717/6182fc08-220e-41cf-ab28-a8a6e5db0247)

2. 当我设置了border为true，边框未显示

![image](https://github.com/ijry/uview-plus/assets/55580717/ad5e0534-fcf5-492c-9d47-610b4d2e3796)

**Comment by ijry** [comment]
请参考https://uiadmin.net/uview-plus/components/grid.html
