### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by JDongKhan** [ijry/uview-plus#257]
1、使用HBuilderX新建的默认模版项目 
2、从插件市场导入uview-plus
3、按照集成步骤对main.js、App.js、uni.scss 进行配置
4、跑不起来

HBuilderX 环境都是最新的。
![苏宁豆芽图片20240112154627220](https://github.com/ijry/uview-plus/assets/4929805/f19be515-0b97-470b-95b2-6febca1e7c35)

下图中的文件都配过了
![苏宁豆芽图片20240112155406209](https://github.com/ijry/uview-plus/assets/4929805/13859497-747a-4fb4-99b2-204c50c9f4a9)

**Comment by JDongKhan** [comment]
原因是@/uni_modules/uview-plus里面的
```
const pleaseSetTranspileDependencies = {},
	babelTest = pleaseSetTranspileDependencies?.test
```
导致的，按照注释给的地址增加了vue.config.js并添加内容
```
// vue.config.js，如没有此文件则手动创建
module.exports = {
	transpileDependencies: ['uview-ui']
}
```

npm install 后依然报错

**Comment by ijry** [comment]
直接启动示例工程演示项目试下

**Comment by JDongKhan** [comment]
演示项目是强制使用uniapp-x,创建的项目没有看到有关任何uview的代码，而且我没研究过uniapp-x，uni-app x项目暂不支持预览 ，不知道如何启动查看效果。

![苏宁豆芽图片20240115104417737](https://github.com/ijry/uview-plus/assets/4929805/38587530-508b-44b8-a45a-c3781c7dde3e)
![苏宁豆芽图片20240115104534861](https://github.com/ijry/uview-plus/assets/4929805/4a94707b-6652-4aca-bb73-2748c3c14f86)

**Comment by JDongKhan** [comment]
main.uts
```
import App from './App.uvue'

import { createSSRApp } from 'vue'
export function createApp() {
  const app = createSSRApp(App)

  return {
    app
  }
}
```
package.json
```
{
  "id": "hello-uvue",
  "name": "hello-uvue",
  "version": "1.0.0",
  "description": "uvue的vue语法示例工程",
  "main": "env.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "uvue",
    "uni-app2.0"
],
  "author": "",
"license": "ISC",
"displayName": "helllo uvue"
}

```

**Comment by JDongKhan** [comment]
我使用npm方式就正常，使用uni_modules就不行

**Comment by ijry** [comment]
uniapp-x暂不兼容，uniapp-x需要后面单独出一个版本，与现有JS引擎底层不一样。
