### ISSUE TITLE
text组件为超链接的情况下size属性不生效

### ISSUE THREAD

**Issue by cv-msan** [ijry/uview-plus#262]
`<up-text  mode="link" size="1" text="忘记密码？" href="https://www.uviewui.com" ></up-text>`
测试该html的size属性设置之后文字大小不变
![image](https://github.com/ijry/uview-plus/assets/76542419/642880a7-cf1b-49fb-8a50-1972d293540f)

**Comment by ijry** [comment]
fixedhttps://github.com/ijry/uview-plus/commit/185c19bc36fc239470bbf808305fedff054eab86
