### ISSUE TITLE
关于$nextTick的问题

### ISSUE THREAD

**Issue by c-sopoo** [ijry/uview-plus#265]
在使用uview-plus时，用了z-paging(@SmileZXLee)，发现有不能滚动到顶部的问题，后面就排查问题，发现不是z-paging本身的问题，然后排查到是uview-plus引起的，后面发现了这行代码，这不就是重写了vue的$nextTick方法了吗，也就是说后续使用`this.$nextTick`已经不是真正的nextTick了

![image](https://github.com/ijry/uview-plus/assets/54697751/98bd01ae-16dd-43eb-bb94-3276c80f592e)

**Comment by ijry** [comment]
可以去掉看是否z-paging正常

**Comment by c-sopoo** [comment]
注释掉后，z-paging正常了，但不明白是为了解决什么问题才这样写的；uview-plus以app.use作为vue插件使用，这里的更改实际是改了整个应用上的$nextTick

**Comment by SmileZXLee** [comment]
需要等uview-plus作者修复一下

**Comment by qcjackman** [comment]
遇到一样的问题了，注释掉就正常，请问后来是咋解决的呢？
