### ISSUE TITLE
关于setConfig覆盖组件默认props无效问题

### ISSUE THREAD

**Issue by zzl0109** [ijry/uview-plus#268]
uview的组件默认值是通过mixin混入组件中的，如果想全局修改组件的props，官网推荐使用setConfig，但有一个问题是修改后的值并不能应用到组件中，可以修改源码，并通过以下几步修复这个问题；
1. 把每个组件的props文件的取值从defprops改为从uni.$u.props里取，下图以u-tabs举例
![image](https://github.com/ijry/uview-plus/assets/64246444/59314584-bf0c-4626-81da-0429223c9f53)
2. 需要在app.use(uview)前执行setConfig函数这样才能在组件mixin前使用修改后的props
![image](https://github.com/ijry/uview-plus/assets/64246444/6b26e317-fd37-4692-845c-b3a397d916d3)

**Comment by ijry** [comment]
原来2.0是从uni.$u.props获取的，移植到vue3后，发现uni-app的SDK全局挂载uni.$u挂载存在奇怪的环境兼容问题，导致无法实现该功能目前。

**Comment by zzl0109** [comment]
> 原来2.0是从uni.$u.props获取的，移植到vue3后，发现uni-app的SDK全局挂载uni.$u挂载存在奇怪的环境兼容问题，导致目前无法实现该功能。

但是我试了改为uni.$u.props上取没发现问题，也许是我验证的case比较少吧，到时遇到问题解决问题就好啦

**Comment by ijry** [comment]
你试试打包APP

**Comment by zzl0109** [comment]
> 你试试打包APP

确实有问题，app打包后，会把props的代码提升在uview install前面

**Comment by zzl0109** [comment]
> 你试试打包APP

作者有时间精力研究怎么修复这个问题吗

**Comment by zzl0109** [comment]
@ijry 找到了一个解决方案，可以把取默认值的方式改为函数返回，目前我在运行的时候是没报错的 
![image](https://github.com/ijry/uview-plus/assets/64246444/8834cd43-cc90-4ac5-a583-38db2346f2d7)
and 还需要将组件props定义中把函数式默认值改一下
![image](https://github.com/ijry/uview-plus/assets/64246444/c1ba0aed-4c2a-4096-9b23-eabff0765347)
