### ISSUE TITLE
input 组件点击clear 无法清空内容

### ISSUE THREAD

**Issue by chengazhen** [ijry/uview-plus#269]
编译为微信小程序, 在开发者端正常清空内容, 但是在手机上出现内容无法清空, clear 事件也可以正常触发, 内容无法正常清空。在历史issue里面也出现了这个问题
![image](https://github.com/ijry/uview-plus/assets/52627267/61e3b3dc-713b-454c-9769-d335d77fbe3b)

**Comment by ishow520** [comment]
我今天也发现了这个情况，急呀，也不知道如何处理

**Comment by ishow520** [comment]
<img width="611" alt="image" src="https://github.com/ijry/uview-plus/assets/28509122/ee25b990-0d2c-4d1d-8522-0d3fcf337c42">
根据排查，发现是 input组件的change方法导致 再次进onInput这个方法，我新增了一个onChange方法，不做任何处理，后续遇到相关的，在做处理
