### ISSUE TITLE
ReadMore 展开阅读更多bug

### ISSUE THREAD

**Issue by LayHuts** [ijry/uview-plus#270]
对于ReadMore中内容是动态的，初次加载后内容高度超过showHeight 会显示 '展开阅读更多'， 如果后面再动态改变内容后调用init也无法关闭 '展开阅读更多'，isLongContent 还是为true  。 
后来改了init方法源码 ，加了else判断
<img width="749" alt="image" src="https://github.com/ijry/uview-plus/assets/45724118/90803749-ee22-4262-a8c4-05e792d037da">

**Comment by ijry** [comment]
已使用上述方式修复
