### ISSUE TITLE
Steps 步骤条可否添加自定义背景色属性

### ISSUE THREAD

**Issue by qcjackman** [ijry/uview-plus#273]
<img width="295" alt="image" src="https://github.com/ijry/uview-plus/assets/12554120/598e8aca-f1f3-429c-8380-6fd325d0da22">

目前步骤条节点背景色写死为#fff了，如果整体有一个其它背景色，步骤节点这里就会很突兀

![image](https://github.com/ijry/uview-plus/assets/12554120/97ab36b8-4cff-4544-bc92-a0de28c98f54)

可否给Steps组建添加一个背景色prop，如：backgroundColor?

**Comment by ijry** [comment]
已增加itemStyle@3.3.10
