### ISSUE TITLE
input 和 textarea 组件在 ios 上同时按下中文和英文，输入框会失焦（安卓没有问题）

### ISSUE THREAD

**Issue by candy252324** [ijry/uview-plus#274]
<img width="322" alt="F87EC3B1-726D-4df2-B00A-AACB87681404" src="https://github.com/ijry/uview-plus/assets/22765708/6802b3c8-4988-46c1-94d4-c5bf47139d3a">

同时按下中文（图片红色框区域）和英文（图片蓝色框区域），输入框会失焦。用户在快速输入的时候很容易触发这个bug。

**Comment by ijry** [comment]
用原生input试试
