### ISSUE TITLE
配置了easycom后,同时使用u-action-sheet和up-button组件后,删除u-action-sheet就报错

### ISSUE THREAD

**Issue by jytx** [ijry/uview-plus#276]
如题,在一个页面中同时使用u-action-sheet和up-button组件时,如果删除了u-action-sheet之后,就会报错,截图如下,如果删除button组件就没有任何问题,只能重启后才可以解决报错问题
依赖如下:
"dependencies": {
    "@dcloudio/uni-app": "3.0.0-3090920231225001",
    "@dcloudio/uni-app-plus": "3.0.0-3090920231225001",
    "@dcloudio/uni-components": "3.0.0-3090920231225001",
    "@dcloudio/uni-h5": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-alipay": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-baidu": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-jd": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-lark": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-qq": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-weixin": "3.0.0-3090920231225001",
    "@dcloudio/uni-mp-xhs": "3.0.0-3090920231225001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-3090920231225001",
    "axios": "1.4.0",
    "axios-miniprogram-adapter": "0.3.5",
    "clipboard": "^2.0.11",
    "dayjs": "^1.11.10",
    "pinia": "2.0.33",
    "uni-mini-router": "0.1.6",
    "uni-parse-pages": "0.0.1",
    "uni-read-pages-vite": "0.0.6",
    "uview-plus": "3.1.45",
    "vue": "3.2.45",
    "vue-i18n": "9.1.9"
  }
<img width="942" alt="image" src="https://github.com/ijry/uview-plus/assets/9834906/db97624e-f0f7-46c3-bb02-f283483a2010">

**Comment by chenwenjieya** [comment]
有没有解决办法，我也遇到了同样的情况

**Comment by ijry** [comment]
未能复现升级最新版本试试
