### ISSUE TITLE
http请求如文档示例在uniapp的安卓模式下报错

### ISSUE THREAD

**Issue by iqinghao** [ijry/uview-plus#277]
https://uiadmin.net/uview-plus/js/http.html 如文档 api / pinia中使用 const http = uni.$u.http 时运行到安卓模拟器/真机 会白屏同时控制台输出http is undefined , 即此时$u并没有挂载成功。

**Comment by gg-guang** [comment]
我这边也有这个问题，请问解决了吗

**Comment by iqinghao** [comment]
> 我这边也有这个问题，请问解决了吗

问题知道了... 那就不要前置调用了.. 不就可以了嘛

**Comment by ijry** [comment]
使用最新版本方式import { http, toast} from '@/uni_modules/uview-plus'

**Comment by cshaptx4869** [comment]
遇到相同的问题 其他端正常 只有App端有问题... 很好奇是什么原因导致的

**Comment by ijry** [comment]
看下文档使用最新的import方式。

**Comment by cshaptx4869** [comment]
> 看下文档使用最新的import方式。

嗯嗯 使用 import 方式导入已经解决这个问题了。只是感觉很奇怪，要么都报错，怎么就只有App端报错，是UniApp自身打包的原因吗

**Comment by ijry** [comment]
是的sdk在App端有兼容问题
