### ISSUE TITLE
Vue3中使用pinia在真机运行时白屏报错： reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->  at useStore (app-service.js:1501:15)

### ISSUE THREAD

**Issue by songyipan** [ijry/uview-plus#278]
![image](https://github.com/ijry/uview-plus/assets/65063252/89e31229-baf1-49a3-afa4-431f51904555)
### 解决办法
 所有使用store的地方，例如
``` js
 const userStore = useUserStore()
```
全部写在函数里面
![image](https://github.com/ijry/uview-plus/assets/65063252/748e7d9c-c6a4-4f69-b96c-f27aad5537cb)

**Comment by Qiu-Jun** [comment]
> ![image](https://github.com/ijry/uview-plus/assets/65063252/89e31229-baf1-49a3-afa4-431f51904555)
> 
> ### 解决办法
> 
>  所有使用store的地方，例如
> 
> ``` js
> 
>  const userStore = useUserStore()
> 
> ```
> 
> 全部写在函数里面
> 
> ![image](https://github.com/ijry/uview-plus/assets/65063252/748e7d9c-c6a4-4f69-b96c-f27aad5537cb)
> 
> 

这个其实和uview没啥关系
