### ISSUE TITLE
u-grid 布局在微信小程序端显示不正确

### ISSUE THREAD

**Issue by hjianmin** [ijry/uview-plus#28]
u-grid 布局在微信小程序端显示不正确，u-grid-item的样式不正确，而且每个item下的图标和文字的长度和位置也不对
![image](https://user-images.githubusercontent.com/20010262/193799059-d3027dd2-1cdc-4644-bc76-164b1d9b3745.png)
![image](https://user-images.githubusercontent.com/20010262/193799195-ac25b7ff-2797-41d3-91a3-d3827373d48a.png)

**Comment by KelvinQQ** [comment]
同遇到

**Comment by ijry** [comment]
fixed
