### ISSUE TITLE
微信小程序内 组件样式修改不了

### ISSUE THREAD

**Issue by zhoufanglu** [ijry/uview-plus#283]
```js
<u-button class="test-btn" type="primary" text="确定"></u-button>

// css
.u-button {
      border: solid 1px red;
    }
```

* 样式不生效
* 自定义类名也检查不到

**Comment by zhoufanglu** [comment]
我试了下，在封装的组件内，改不了样式，但是在page页面里面是可以的，这是什么原因

**Comment by zhoufanglu** [comment]
解决了，真tm蛋疼，需要解除样式隔离。  
在组件内写入如下代码
```js
<script>
  export default {
    options: { styleIsolation: 'shared' },
  }
</script>
```

**Comment by x-17** [comment]
为什么不是给u-button加这个解除样式的选项呢

**Comment by ijry** [comment]
用deep穿透样式

**Comment by x-17** [comment]
我不明白，要修改的是u-button的样式，为什么不解除u-button组件的样式隔离，反而是解除他父组件的样式隔离

**Comment by ijry** [comment]
这得问微信

**Comment by chergn** [comment]
`::v-deep` `/deep/` `>>>` `:v-deep()`都试了，不管用https://ask.csdn.net/questions/8140882

**Comment by ijry** [comment]
页面加
```
<script>
  export default {
    options: { styleIsolation: 'shared' },
  }
</script>
```

**Comment by zhoufanglu** [comment]
> `::v-deep` `/deep/` `>>>` `:v-deep()`都试了，不管用https://ask.csdn.net/questions/8140882

上面解决方法已经给出了，仔细看

**Comment by ijry** [comment]
都是微信搞的鬼，注意微信小程序除了styleIsolation，还有另一个要求，在deep时需要有一个父class节点。
```
.custo-clsss ::v-deep {
    .u-button {
    }
}
```

**Comment by ijry** [comment]
文档都有
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/2da99a37-14dc-44d1-8f10-beb63e20ab59">
