### ISSUE TITLE
NoticeBar 滚动通知组件设置color属性没有生效

### ISSUE THREAD

**Issue by Liu-code3** [ijry/uview-plus#291]
<u-notice-bar 
                :text="noticeText"
                color="#ccc"
                bgColor="#DFE7FA"
                fontSize="16"
            ></u-notice-bar>
            以上color属性没有生效
            https://uiadmin.net/uview-plus/components/noticeBar.html#api这个是文档地址

**Comment by ijry** [comment]
截图看看

**Comment by Liu-code3** [comment]
![view](https://github.com/ijry/uview-plus/assets/100696868/ca03ced8-7d48-45f6-8755-2ff1e30f33e9)
以上是界面截图
![code](https://github.com/ijry/uview-plus/assets/100696868/13e3e87e-dbdc-4c04-8710-d805c1893a56)
以上是代码截图
背景色属性能生效, 但是文字颜色属性没有生效, 目前的解决方案是使用css穿透修改的, 还请指教 盼复！
