### ISSUE TITLE
u-index-list  小程序 

### ISSUE THREAD

**Issue by QHSsss** [ijry/uview-plus#293]
源码 在setValueForTouch方法中
`this.scrollTop = this.children[currentIndex].top`
在这里如果小程序是自定义导航栏的时候即传了customNavHeight的时候会出现跳转偏移的情况，所以加一行代码减去customNavHeight的高度比较合理，跳转也是正常的。另外，sticky属性好像没啥用？好像之前就提过了
`const customNavHeight = this.customNavHeight
this.scrollTop = this.children[currentIndex].top - uni.$u.getPx(customNavHeight)`

**Comment by litiantian-github** [comment]
通过安装依赖包安装的uview直接改源码代码不会上传到git上面 组件库源码可以更新吗

**Comment by ijry** [comment]
感谢，git已更新，依赖下版本发布。

**Comment by jinsiyan** [comment]
添加自定义导航后 传值customNavHeight 小程序滚动（scrollTop）没有减去customNavHeight ,导致点击索引跳转的时候有问题 能改动一下在源码中加上这行么 scrollTop+=this.customNavHeight

**Comment by jinsiyan** [comment]
![Uploading 微信图片_20240522132126.png…]()
