### ISSUE TITLE
u-form-item动态label在ios微信小程序上的问题

### ISSUE THREAD

**Issue by QHSsss** [ijry/uview-plus#296]
场景：ios微信小程序
问题：<u-label-item :label="xxxxx"> 
label为计算属性，当长度从短变成长的时候多的那部分会被某种盒子盖住，不知道啥玩意，感觉像短的宽度放到了长的上面然后被overflow:hidden掉了
<img width="256" alt="企业微信截图_17110881536296" src="https://github.com/ijry/uview-plus/assets/120435958/0ace2210-c6f5-4294-aae6-72f1415b3631">

**Comment by ijry** [comment]
可以传递labelWidth参数设置为100%
