### ISSUE TITLE
抖音小程序grid，swiper等样式失效

### ISSUE THREAD

**Issue by www295686243** [ijry/uview-plus#297]
在抖音小程序目前测试了grid，swiper(卡片模式)这2个组件，样式是失效的。
我看了下貌似是因为抖音小程序自定义组件会多一层元素的原因。
目前HbuilderX4.02以上支持virtualHost: true，我在你的mpMixins中去掉了微信环境的判断，但又导致了其他功能兼容的问题，能否优化一下抖音小程序中的表现？

**Comment by ijry** [comment]
3.2.0已使用grid布局暂时解决
