### ISSUE TITLE
组件u-popup编译器中报错

### ISSUE THREAD

**Issue by hongsedefeng** [ijry/uview-plus#3]
HbilderX:3.5.3.20220729;
<u-popup mode="bottom" :show="show" :overlay="false" :duration="500" @close="close" :round="10">
//...
</u-popup>
编译器提示：Generated an empty chunk: "uni_modules/uview-plus/components/u-transition/nvue.ani-map"。
编译后微信开发者可以正常操作。

**Comment by ijry** [comment]
2.6.4暂未复线，请升级至最新版本HbilderX。
