### ISSUE TITLE
使用v-for list动态渲染u-swipe-item，list添加一个子元素后，所有u-swipe-item不能右滑

### ISSUE THREAD

**Issue by KaleidosChen** [ijry/uview-plus#300]
使用v-for list动态渲染u-swipe-item，u-swipe-item里面有u-cell。
list添加一个子元素后，所有u-swipe-item不能右滑。
添加后点击u-cell，u-swipe-item才可以右滑

**Comment by ijry** [comment]
哪有u-cell
