### ISSUE TITLE
u-form 表单 validate 校验不通过后，返回的 error 列表信息里面 field 字段是对应 prop 最后一层

### ISSUE THREAD

**Issue by unformalized** [ijry/uview-plus#304]
比如 <u-form-item prop='package.id'></u-form-item>
报错后 error 信息为 [{ field: 'id' }] ，prop 最后一层可能存在重复的，我就无法根据错误进行对应字段的操作

**Comment by unformalized** [comment]
`<u-form-item prop="package.id"></u-form-item>`

**Comment by ijry** [comment]
3.3.10已在error对象增加prop字段便于区分
