### ISSUE TITLE
from 表单 asyncValidator， 校验不会阻止validate 结果

### ISSUE THREAD

**Issue by zhengybo** [ijry/uview-plus#306]
u-form 源码对于asyncValidator处理存在问题
![image](https://github.com/ijry/uview-plus/assets/22511317/feffe8e6-37a2-4aba-b798-e0f6b6060f92)
![image](https://github.com/ijry/uview-plus/assets/22511317/6d61a1df-71ed-4e2f-8639-8c47226b387b)
![image](https://github.com/ijry/uview-plus/assets/22511317/079c29aa-61a2-410f-95ca-1f54549fa783)

**Comment by zhengybo** [comment]
应该改为promise.all 完成后执行callback

**Comment by ijry** [comment]
#393
