### ISSUE TITLE
文档关于u-back-top的组件使用错误

### ISSUE THREAD

**Issue by izhaorui** [ijry/uview-plus#309]
文档地址：https://uiadmin.net/uview-plus/components/backTop.html

![image](https://github.com/ijry/uview-plus/assets/16451400/4dc48f3c-7a40-4b33-b30b-e9bc6b58e61e)

应该是<u-back-top>吧
![image](https://github.com/ijry/uview-plus/assets/16451400/7ff7c45e-c317-44c4-8afa-ffeb69d63c1f)

**Comment by ijry** [comment]
up-和u-前缀都支持，只需要正确配置easycom规则即可。
