### ISSUE TITLE
h5 dayjs 导入报错

### ISSUE THREAD

**Issue by JadynWong** [ijry/uview-plus#31]
![image](https://user-images.githubusercontent.com/13699353/195489876-3c58d206-299d-45c4-b089-385d07b31bcb.png)

根据文档修改也无效
https://dayjs.gitee.io/docs/zh-CN/installation/typescript

微信小程序正常

**Comment by ZzzhangLK** [comment]
改成moment就行了

**Comment by JadynWong** [comment]
> 改成moment就行了

主要是datetime-picker组件会用到dayjs，不能用这个组件

**Comment by ZzzhangLK** [comment]
![image](https://user-images.githubusercontent.com/51199163/195969794-3a325f7a-47f8-4c9c-bee1-280890849554.png)
就是要把datetime-picker里面的dayjs改成moment

**Comment by JadynWong** [comment]
> ![image](https://user-images.githubusercontent.com/51199163/195969794-3a325f7a-47f8-4c9c-bee1-280890849554.png)
> 就是要把datetime-picker里面的dayjs改成moment

了解了，感谢

**Comment by SoulLyoko** [comment]
用vite的话在依赖优化中加入dayjs：
```js
// vite.config.js
export default {
    // ...other config
    optimizeDeps: {
        include: ["dayjs"]
    }
}
```

**Comment by JadynWong** [comment]
> 用vite的话在依赖优化中加入dayjs：
> 
> ```js
> // vite.config.js
> export default {
>     // ...other config
>     optimizeDeps: {
>         include: ["dayjs"]
>     }
> }
> ```

可用，感谢。
