### ISSUE TITLE
u-datetime-picker组件的时间(time)模式中能否增加列表的循环滚动

### ISSUE THREAD

**Issue by wjw020206** [ijry/uview-plus#310]
选择时间时可以接着往下滑动而不用往回滑动，例如：01滑动到59后再往后滑接着从01开始
<img width="320" alt="image" src="https://github.com/umicro/uView2.0/assets/59106659/1b099ad8-a9ee-42fd-ba72-6e9845547d55">

**Comment by ijry** [comment]
u-picker基于原生内置picker组件，循环滚动需要uni-app底层支持。
