### ISSUE TITLE
ReadMore组件bug

### ISSUE THREAD

**Issue by x-17** [ijry/uview-plus#311]
![issue](https://github.com/ijry/uview-plus/assets/104053270/e3625405-475e-4e34-993a-4df495fe4b3e)
**这里的height是元素的px高度，如果配置了uni.$u.config.unit为rpx,经过addUnit会返回一个rpx单位的高度，导致展开后内容出现bug**
![issue2](https://github.com/ijry/uview-plus/assets/104053270/72e39ed0-ebe4-4214-90d8-2c7de591dacd)
**给addUnit加上“px”参数得到解决**

**Comment by ijry** [comment]
这段代码咋改的，我跟源码对不上？

**Comment by x-17** [comment]
我是把u-read-more__content动态绑定的style改成下面这样，让contentHeight返回一个px单位的值
`style:”{ height: isLongContent && status === 'close' ? $u.addUnit(showHeight) : $u.addUnit(contentHeight,’px’)}” `
