### ISSUE TITLE
关于up-开头的组件引用问题

### ISSUE THREAD

**Issue by izhaorui** [ijry/uview-plus#313]
按照官方提供的文档进行配置自动引用包时还是会出现 up-开头的组件找不到
![image](https://github.com/ijry/uview-plus/assets/16451400/b45e6236-3389-47df-8ef9-45aad7a25691)

控制它错误
![image](https://github.com/ijry/uview-plus/assets/16451400/85e7a110-d053-4dbf-9dff-693033aa7d1f)

这个是项目 的配置
![image](https://github.com/ijry/uview-plus/assets/16451400/58360e8b-8b66-4274-829f-eb35ccd029be)

**Comment by ijry** [comment]
你这一看就少一层easycom

**Comment by izhaorui** [comment]
示例应该把这个也带上，不然容易错
![image](https://github.com/ijry/uview-plus/assets/16451400/16f69140-c723-44fc-ab45-0558c9889742)

**Comment by ijry** [comment]
可以
