### ISSUE TITLE
up-back-top组合式语法不会触发方法onPageScroll

### ISSUE THREAD

**Issue by izhaorui** [ijry/uview-plus#314]
文档地址：https://uiadmin.net/uview-plus/components/backTop.html

按照文档操作并不会触发方法onPageScroll

改成下面方式就可以了

<script setup>
    import {
    onPageScroll
  } from '@dcloudio/uni-app'

const scrollTop = ref(0)
  // 定义 onPageScroll 方法
  onPageScroll((e) => {
    scrollTop.value = e.scrollTop;
  });
</script>

不知道是不是文档里面的例子都是使用了自动导入的功能

**Comment by ijry** [comment]
已更新文档

**Comment by SnhAenIgseAl** [comment]
我按照这个写法微信小程序仍然不触发onPageScroll方法，h5端正常。
<script setup>
import { ref } from 'vue'
import { onPageScroll } from '@dcloudio/uni-app'
	
const {
    textList,
    imgList
} = defineProps({
    textList: {
    	type: Array,
    	required: true
    },
    imgList: {
        type: Array,
        default: []
    }
})

const scrollTop = ref(0)

onPageScroll((e) => {
	scrollTop.value = e.scrollTop
	console.log(e)
})

</script>
微信小程序端
![image](https://github.com/user-attachments/assets/98c3289e-183d-4f25-81f2-80cb39dddb82)
h5端正常
![image](https://github.com/user-attachments/assets/d77a7507-26b6-4967-bd09-dee7b2cb02dc)

uview-plus版本：3.3.50
微信开发者工具版本：1.06.2412042
浏览器版本：chrome 131.0.6778.140

**Comment by SnhAenIgseAl** [comment]
已解决，在组合式script代码块后面再加一个script代码块声明onPageScroll方法
![image](https://github.com/user-attachments/assets/3f524b9c-b82d-4368-9550-85c59f91be7a)
然后在需要引用组件的页面添加
import { onPageScroll } from '@dcloudio/uni-app'
这句代码即使注释掉了仍能被关键词检查到执行

真没见过这么uni-app这么傻逼的框架
