### ISSUE TITLE
album相册组件urls不能传递空数组的问题

### ISSUE THREAD

**Issue by Yubai2022** [ijry/uview-plus#315]
![image](https://github.com/ijry/uview-plus/assets/64421424/091d411d-3282-4176-b782-3ab0c22417ad)

**Comment by izhaorui** [comment]
我这样写的

<view class="album-wrap" v-if="item && item.coverImgList && item.coverImgList.length > 0">
          <u-album :urls="item.coverImgList"></u-album>
        </view>

**Comment by izhaorui** [comment]
我这样写的

`<view class="album-wrap" v-if="item && item.coverImgList && item.coverImgList.length > 0">
          <u-album :urls="item.coverImgList"></u-album>
        </view>`

**Comment by ijry** [comment]
coverImgList不是空数组吧
