### ISSUE TITLE
一些bug（setConfig、loading-icon）（v3.2.10）

### ISSUE THREAD

**Issue by anno0331** [ijry/uview-plus#318]
1. loading-icon 
![J3HFH_PGAXGEVT0_~42G_TR](https://github.com/ijry/uview-plus/assets/74413722/f6900ae3-10c6-4141-8a1e-794f548196f9)
![T{@F`IA4A2HQ3TW8MG$YNQM](https://github.com/ijry/uview-plus/assets/74413722/67663a37-7ccf-437d-87c7-9a7cdef328be)
loading-icon 的flex 布局没了

2. setConfig我设置了unit 为rpx好像没有效果，之前还好好的，升级了一下依赖就不行了，导致一些组件样式变了
![}IPJF$G_XZ}$ 2S)8JIQCY](https://github.com/ijry/uview-plus/assets/74413722/69b831da-099c-42f4-add0-016d1d23e7b0)
![image](https://github.com/ijry/uview-plus/assets/74413722/1e78b406-f72b-4765-ba43-44f97d3789ea)

**Comment by ijry** [comment]
最新版优化了下
