### ISSUE TITLE
u-notice-bar在h5样式出现问题，模拟器和真机运行又正常

### ISSUE THREAD

**Issue by DeepSea141** [ijry/uview-plus#320]
![image](https://github.com/ijry/uview-plus/assets/135229262/85c1e0ac-4398-4b58-8390-eb5cf633da67)
![image](https://github.com/ijry/uview-plus/assets/135229262/089eb1f2-12b6-4365-a283-0c794bcd8a55)
![Uploading image.png…]()
取消后就又正常

**Comment by DeepSea141** [comment]
![image](https://github.com/ijry/uview-plus/assets/135229262/9fc35541-91c6-43f5-9d7e-893acb540a14)

**Comment by wujingquan** [comment]
怎么关了呢？
