### ISSUE TITLE
抖音小程序使用u-picker的问题

### ISSUE THREAD

**Issue by www295686243** [ijry/uview-plus#322]
在抖音小程序中u-picker无法触发change，排查后发现需要把u-picker组件内把this的传递去掉
![image](https://github.com/ijry/uview-plus/assets/10710116/1fafa11b-eab0-402f-a81d-b60a3e757726)

**Comment by www295686243** [comment]
u-datetime-picker也要去掉

**Comment by ijry** [comment]
fixed
