### ISSUE TITLE
u-datetime-picker初始化的问题

### ISSUE THREAD

**Issue by www295686243** [ijry/uview-plus#323]
该组件的updateIndexs方法中，const padZero = padZero这一句的意义在哪里？这导致padZero这个方法undefined了，初始化失败，去掉正常。
![image](https://github.com/ijry/uview-plus/assets/10710116/3a3366da-ce69-4d36-8d66-20c2ab7798f4)

**Comment by ijry** [comment]
早上3.2.12已经修复，是在做uni.$u改造import时导致的。
