### ISSUE TITLE
index-list组件微信小程序端使用自定义导航栏异常

### ISSUE THREAD

**Issue by lijiexiong-git** [ijry/uview-plus#325]
个人进行了修复，改动如下：
![微信图片_20240424175645](https://github.com/ijry/uview-plus/assets/71053227/056d5887-a34c-4c3a-8c74-7834b096dedb)

![微信图片_20240424175649](https://github.com/ijry/uview-plus/assets/71053227/f8314034-bfd0-435b-8d42-c010e5366979)

**Comment by ijry** [comment]
已修复

**Comment by jinsiyan** [comment]
能不能在不改动源码的情况下进行修改呀

**Comment by lijiexiong-git** [comment]
> 能不能在不改动源码的情况下进行修改呀

作者说修复了，你要不更新下最新的版本试试？

**Comment by jinsiyan** [comment]
3.2.14 不是最新版本的么

**Comment by lijiexiong-git** [comment]
> 3.2.14 不是最新版本的么

![Uploading image.png…]()
最新为3.2.22

**Comment by jinsiyan** [comment]
好的 我试试非常感谢

**Comment by lijiexiong-git** [comment]
> 3.2.14 不是最新版本的么

我查看了提交记录，和我的改的不太一样，你看看更新了能不能用，不行的话你可以试试我改的，直接改代码了

**Comment by jinsiyan** [comment]
好的 不能动源码呀 因为到时候提交上去node_moudels是不能上传上去的 所以想要在不改动源码的情况下进行实现

**Comment by lijiexiong-git** [comment]
> 好的 不能动源码呀 因为到时候提交上去node_moudels是不能上传上去的 所以想要在不改动源码的情况下进行实现

你是通过vue cli创建的项目还是hbuilderx创建的项目？hbuilderx创建的话是放在uni_modules目录下，你整个目录都一起提交git就行了

**Comment by jinsiyan** [comment]
vue cli创建的

**Comment by lijiexiong-git** [comment]
> vue cli创建的

这样

**Comment by jinsiyan** [comment]
![image](https://github.com/ijry/uview-plus/assets/169879398/75f941e0-bc49-48ff-b1c9-3f56501e2431)
他这个gitee上的最新代码跟我现在的是一样的 不行实现不了

**Comment by lijiexiong-git** [comment]
> ![image](https://private-user-images.githubusercontent.com/169879398/331026018-75f941e0-bc49-48ff-b1c9-3f56501e2431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mjc0MTYsIm5iZiI6MTcxNTgyNzExNiwicGF0aCI6Ii8xNjk4NzkzOTgvMzMxMDI2MDE4LTc1Zjk0MWUwLWJjNDktNDhmZi1iMWM5LTNmNTY1MDFlMjQzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwMjM4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM4OTRhMTk1OTE2YmQzMDlmNWIyYTIxMzBhM2RmM2YwZmRiZTQyZGMxYWFjYjg5ZWJjOGViMTQ1Y2EwMzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1nmV4g-EmDJzCg1w_ZJMf6qgD1xQDHLH2hyzL5lka-M) 他这个gitee上的最新代码跟我现在的是一样的 不行实现不了

那就没办法了，个人开发维护的项目作者也只会偶尔抽空解决下问题

**Comment by jinsiyan** [comment]
害 好滴吧

**Comment by lijiexiong-git** [comment]
> 害 好滴吧

说起来uniapp这个框架都没有个像样的ui框架，官方的和第三方的都很拉

**Comment by jinsiyan** [comment]
是滴呀 有点难理解
