### ISSUE TITLE
import mixin from 'uview-plus/libs/mixin/mixin.js' 中beforeDestroy和beforeUnmount的条件编译写法在vite 4.3.5 版本编译不通过

### ISSUE THREAD

**Issue by idujiayou** [ijry/uview-plus#328]
<img width="1235" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/1f4b9614-d7bc-45df-a939-520bdb99e39e">

**Comment by idujiayou** [comment]
建议改成完整的写法
<img width="1079" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/bc9b6872-2ccd-4608-875c-06aacc6854ae">

**Comment by ijry** [comment]
已修改

**Comment by idujiayou** [comment]
> 已修改

<img width="1178" alt="image" src="https://github.com/ijry/uview-plus/assets/16297776/82f4f1c4-1a5b-474a-bbdb-b71b0a9d7676">
已经锁定vue3 版本 干脆把 	// #ifdef VUE3 这个条件编译去掉吧  更新最新版本的uniapp 编译又
报错了

**Comment by Bell-1** [comment]
v3.2.24这个版本的包还是没有修复这个问题，预计多久可以发布呢？可以快点吗！
<img width="356" alt="image" src="https://github.com/ijry/uview-plus/assets/23493322/9824cf1a-d88e-4948-81c5-396f5a7689a3">

**Comment by ijry** [comment]
明天发
