### ISSUE TITLE
v3.1.52以后的版本日历组件有展示问题，可能其他组件也有同样问题

### ISSUE THREAD

**Issue by wfz8023** [ijry/uview-plus#329]
v3.1.52版本后问题
![Snipaste_2024-04-26_19-49-10](https://github.com/ijry/uview-plus/assets/50281678/d64c4100-d27e-4f83-9100-aef73a20a0a5)
将6～8行代码解开就会修复
<img width="739" alt="Snipaste_2024-04-26_19-47-08" src="https://github.com/ijry/uview-plus/assets/50281678/dbdaa104-0142-4112-b572-ad331433d5d8">
修复后展示
![Snipaste_2024-04-26_19-52-02](https://github.com/ijry/uview-plus/assets/50281678/63e811fa-7878-4c54-8011-61b978f3bad5)

**Comment by ijry** [comment]
这几行注释是因为微信新版本不允许直接对这些标签设置样式会warning

**Comment by ijry** [comment]
这个截图是什么环境，我看了H5/微信都正常。
