### ISSUE TITLE
up-action-sheet 取消按钮高度很小

### ISSUE THREAD

**Issue by izhaorui** [ijry/uview-plus#331]
![image](https://github.com/ijry/uview-plus/assets/16451400/58543044-d2a5-49bb-a34c-944ab6c61b05)
![image](https://github.com/ijry/uview-plus/assets/16451400/18f84932-1cd7-47fd-868e-e55fddb85555)

```
    <u-action-sheet @close="show = false" :safeAreaInsetBottom="true" round cancelText="取消" @select="selectClick"
      :actions="moreList" :show="show"></u-action-sheet>

```

**Comment by izhaorui** [comment]
期望加个class 
![image](https://github.com/ijry/uview-plus/assets/16451400/25cd00f6-c244-4a7f-ae28-f2aa680b9046)

**Comment by ijry** [comment]
已增加
