### ISSUE TITLE
Upload组件的deletable/maxCount 是否显示删除图片的按钮 动态控制 这个删除图片的按钮不生效

### ISSUE THREAD

**Issue by zjjjyl** [ijry/uview-plus#333]
<u-upload :fileList="fileList"  :maxCount="state.maxCount" :deletable='state.deletable' :disabled='state.disabled'></u-upload>
const state = reactive({
  disabled:false,
  deletable:false,
  maxCount:0
})
![72f9dc0f07583a193b6dd72a0ed9238](https://github.com/ijry/uview-plus/assets/145547923/2d5a4a04-ed40-4959-a436-6911a1a81683)

disabled是否启用(显示/隐藏)组件 这个是没有问题的 但是maxCount 和 deletable这两个属性 更改了 并不会实时的生效
结束调查的时候 我确定是改变了 deletable和maxCount 属性的值 --但是并没有生效-disabled生效了 仔细看图片就会发现上传灰了 
![bd1c5568cacfe421e4773b912a38d22](https://github.com/ijry/uview-plus/assets/145547923/8881a072-301a-4171-bd92-4445bf558e2d)
当我结束调查的时候--重新渲染一次fileList的值 就会生效！
fileList改变的话 就会渲染---不知道是组件问题 还是只是我写的碰到了这个问题？
![2d2f60ce345137a78a23ad328dd4b05](https://github.com/ijry/uview-plus/assets/145547923/d6691ab1-588c-494a-842a-23d95d7d1bd1)

**Comment by ijry** [comment]
fixed@3.3.11
