### ISSUE TITLE
直接引入up-form报错

### ISSUE THREAD

**Issue by lihwang** [ijry/uview-plus#336]
![image](https://github.com/ijry/uview-plus/assets/25947622/3bded4b6-e1cd-4b40-b40e-305c9479ec2c)
在uni-app中直接引入up-form ，报错语法错误，其他组件正常

**Comment by ijry** [comment]
暂未复现

**Comment by akinstrument** [comment]
> 暂未复现

这个我也遇到了，新建了一个空项目，按照官网下载的方式一步步去做，其他控件都可以，只要是引入了form组件就报和楼主一样的错误
![Uploading 7ABB7BF78BDDBF03AC8E12EE706FDC0D.png…]()

**Comment by ijry** [comment]
原因查明，HBuilderX内置浏览器版本太低不支持JS语法?.可选链。解决方法，使用自己的浏览器即可。
