### ISSUE TITLE
up-tabs 文字会换行

### ISSUE THREAD

**Issue by izhaorui** [ijry/uview-plus#337]
![image](https://github.com/ijry/uview-plus/assets/16451400/ae4fd6fe-f886-4848-b66f-ca1627e51fe9)

如图希望里面的文字可以单独加一个属性样式white-space: nowrap;

**Comment by izhaorui** [comment]
![image](https://github.com/ijry/uview-plus/assets/16451400/dae6f0d7-a7a5-4c9a-b1fb-527c712346d6)

**Comment by ijry** [comment]
感谢已优化
