### ISSUE TITLE
u-code 倒计时没结束前退出，再次进入结束后退出界面，再次进入重新开始倒计时bug

### ISSUE THREAD

**Issue by baofei12** [ijry/uview-plus#341]
u-code 倒计时没结束前退出，再次进入结束后退出界面，再次进入重新开始倒计时bug，
`setTimeToStorage() {
				if(!this.keepRunning || !this.timer) return
				// 记录当前的时间戳，为了下次进入页面，如果还在倒计时内的话，继续倒计时
				// 倒计时尚未结束，结果大于0；倒计时已经开始，就会小于初始值，如果等于初始值，说明没有开始倒计时，无需处理
				if(this.secNum > 0 && this.secNum <= this.seconds) {
					// 获取当前时间戳(+ new Date()为特殊写法)，除以1000变成秒，再去除小数部分
					let nowTimestamp = Math.floor((+ new Date()) / 1000)
					// 将本该结束时候的时间戳保存起来 => 当前时间戳 + 剩余的秒数
					uni.setStorage({
						key: this.uniqueKey + '_$uCountDownTimestamp',
						data: nowTimestamp + Number(this.secNum)
					})
				}
			}`
需要把|| !this.timer加上

**Comment by ijry** [comment]
感谢已添加
