### ISSUE TITLE
checkbox change 没有返回name

### ISSUE THREAD

**Issue by wzhsh90** [ijry/uview-plus#343]
checkbox checked 是单向绑定，当checkbox 的值变化后，并不会影响原来数据集。

而checkbox change 事件里面只返回了当前状态没有返回name。

当在循环多个checkgroup 时，使用value不方便，建议把在change 里面把name 返回。

**Comment by ijry** [comment]
checkbox 的值变化是指？

**Comment by wzhsh90** [comment]
checkbox change事件目前只是返回true或false


当出现循环checkgroup 时，只通过chekgroup v-model 不方便做控制checkbox 选中。


例：
在一个列表中，所有checkbox 并不是在一个checkgroup 里面。而是每个checkgroup 里面包含一个checkbox.
而本身列表数据里面有checked 数据字段，那么当checkbox 状态变化时，不会同步数据的checked状态。而只能通过checkgroup change 事件得到v-model ，再通过v-model 值循环判断checkbox 状态来同步数据状态。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ijry/uview-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 晚上9:23
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [ijry/uview-plus] checkbox change 没有返回name (Issue #343)





 
checkbox 的值变化是指？

**Comment by ijry** [comment]
多层的实时不用group，直接使用新支持的独立使用up-checkbox呢

**Comment by wzhsh90** [comment]
什么时候可以独立了？原来版本不能独立使用必须在group里面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ijry/uview-plus] checkbox change 没有返回name (Issue #343)




 
多层的实时不用group，直接使用新支持的独立使用up-checkbox呢。

**Comment by ijry** [comment]
文档有

**Comment by wzhsh90** [comment]
没有把checkbox的name 返回，这样还是解决不了问题。循环独立使用时把name返回才行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 下午4:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ijry/uview-plus] checkbox change 没有返回name (Issue #343)




 
文档有

**Comment by wzhsh90** [comment]
this.$emit('change', this.isChecked)
为什么不把change 事件写成这样？
this.$emit('change', {"name":this.name,"checked":this.isChecked})


你现在的处理方案根本解决不了问题
