### ISSUE TITLE
bug: 支付宝小程序 qrcode 绘制失败

### ISSUE THREAD

**Issue by Allen-1998** [ijry/uview-plus#345]
### 问题现象
二维码绘制失败，一直loading

### 复现代码
官方base case即可复现
```vue
<up-qrcode :size="200" val="uview-plus"></up-qrcode>
```

### 问题原因
1. `uni.canvasToTempFilePath` 中设置的 canvasId，对应[支付宝小程序canvas标签上的id](https://opendocs.alipay.com/mini/component/canvas) , [微信小程序canvas标签上的canvas-id](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html)
https://github.com/ijry/uview-plus/blob/8d677916e6062d82cfcbe3019c3f5ebfd8510410/src/uni_modules/uview-plus/components/u-qrcode/qrcode.js#L1144-L1150
2. `u-qrcode` 组件中canvas标签只设置了canvas-id，导致支付宝调用 canvasToTempFilePath 时 id 未匹配上
https://github.com/ijry/uview-plus/blob/8d677916e6062d82cfcbe3019c3f5ebfd8510410/src/uni_modules/uview-plus/components/u-qrcode/u-qrcode.vue#L3
### 解决方案
在`u-qrcode` 组件中canvas标签上添加 `:id="cid"`,即:
```vue
<canvas class="u-qrcode__canvas" :id="cid" :canvas-id="cid" :style="{ width: size + unit, height: size + unit }" />
```

**Comment by ijry** [comment]
已发布
