### ISSUE TITLE
feat: 关于 u-qrcode 的loading效果建议

### ISSUE THREAD

**Issue by Allen-1998** [ijry/uview-plus#351]
### 现状
目前的loading效果是直接调用 uni.showLoading 实现，这会造成绘制二维码时整个页面的loading效果,用户体验相对而言较差

### 期望效果
只有二维码的容器部分loaidng

### 可能的实现方案
1. 添加一个和 image 标签同级同宽同高的 view
2. view 的样式大致为半透明的蒙层加上中心一个loding图标(或者同时可以slot形式支持用户传入？)
3. uni.showLoading, uni.hideLoading 逻辑替换为image和view的 if / else 展示

希望可以探讨这是否是最好的实现方案，如果可以的话我愿意来实现这个功能

**Comment by ijry** [comment]
挺好整一个

**Comment by Allen-1998** [comment]
考虑到源码中本身已有 `$emit('result')` 来体现二维码生成的结果，可以通过这个回调来间接的判断当前是否是加载中状态，来进行自定义的loading效果处理，因此这个功能实际上也不是必须的

同时在实现这个功能时，还需要考虑存量用户的向下兼容问题 (部分用户可能已经`props.showLoading: true`且自定义了`props. loadingText`)

当然如果组件里内置loading，使用时相对来说还是会更方便一些，后续如果有更多的人参与讨论，有同样的需求的话，我会再来跟进这个功能的实现

**Comment by ijry** [comment]
3.3.21
