### ISSUE TITLE
可以在 types 中统一导入到 index.d.ts 吗

### ISSUE THREAD

**Issue by sunpm** [ijry/uview-plus#353]
目前导入类型需要加上路径：
<img width="525" alt="image" src="https://github.com/ijry/uview-plus/assets/35005831/fe0e32c0-7979-4dcb-a242-70626696672d">

可否实现下面的导入方式：
<img width="452" alt="image" src="https://github.com/ijry/uview-plus/assets/35005831/8a7c88d3-1f11-4f6a-876d-0db916aad497">

**Comment by ijry** [comment]
`<script setup lang="ts">
	import { ref } from 'vue'
	import type { UniFormRef } from '@/uni_modules/uview-plus/types'
	const form1 = ref<UniFormRef|null>(null)
</script>`
