### ISSUE TITLE
u-code持久缓存倒计时bug

### ISSUE THREAD

**Issue by mywen7** [ijry/uview-plus#357]
![Snipaste_2024-05-10_17-45-04](https://github.com/ijry/uview-plus/assets/74164272/54b6f9c4-0c88-495c-945e-55eca2d18f12)

注释中已说明：倒计时等于初始值时无需处理
但是代码上在等于时 依旧将倒计时缓存在本地，去掉 “=“

**Comment by ijry** [comment]
fixed
