### ISSUE TITLE
使用up-swipe-action与up-swipe-action-item后云打包app时出现错误

### ISSUE THREAD

**Issue by xiaohai0116** [ijry/uview-plus#358]
[HBuilder] 20:14:54.548 [plugin:uni:app-vue-renderjs] Invalid target "modules" in "--target=modules"
[HBuilder] 20:14:54.555 at ../node_modules/uview-plus/components/u-swipe-action-item/index.wxs:1:0
[HBuilder] 20:14:54.561 Build failed with errors.

**Comment by ijry** [comment]
ios?

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/917cc15e-cd36-4103-b43d-75dd9d84d20f)
