### ISSUE TITLE
3.2.22版本up-scroll-list真机运行出错

### ISSUE THREAD

**Issue by JackWSK** [ijry/uview-plus#364]
up-scroll-list在真机环境下报错
因为如下图，你使用const element = {},但是const类型不能重复赋值。请改成let
<img width="590" alt="截屏2024-05-17 上午11 24 51" src="https://github.com/ijry/uview-plus/assets/3961024/659e30fc-5435-4b3a-b0e1-b96a20ff3622">

**Comment by ijry** [comment]
fixed@3.3.7
