### ISSUE TITLE
请问, 在vue3+ts中如何引入工具函数

### ISSUE THREAD

**Issue by fqingyang** [ijry/uview-plus#366]
我按照下面这样引入后功能正常使用,就是报错,请问应该如何解决呢?
import { throttle, debounce, timeFormat, timeFrom, test } from 'uview-plus/index'

报错误:
无法找到模块“uview-plus/index”的声明文件。“uview-plus@3.2.17/node_modules/uview-plus/index.js”隐式拥有 "any" 类型。
  如果“uview-plus”包实际公开了此模块，请尝试添加包含 `declare module‘uview-plus/index';` 的新声明(.d.ts)文件ts(7016)

**Comment by wmt-git** [comment]
我这边也是报同样问题
