### ISSUE TITLE
setConfig设置H5不起作用

### ISSUE THREAD

**Issue by linhaiboma** [ijry/uview-plus#367]
更新到 **setConfig改为浅拷贝解决无法用import导入代替uni.$u.props设置**  这个版本之后，下面设置对H5页面不起作用。微信小程序没有问题。

setConfig({
    // 修改$u.props对象的属性
    props: {
      line: {
        color: '#e4e7ed'
     }
    }
  })

**Comment by ijry** [comment]
实测最新版可以
