### ISSUE TITLE
up-text/u--text组件在uni-app vue3 中编译到微信小程序设置color颜色属性没有生效， 还是默认配置里的color值

### ISSUE THREAD

**Issue by sonicsunsky** [ijry/uview-plus#368]
up-text/u--text组件在uni-app vue3(setup) 中编译到微信小程序设置color颜色属性没有生效， 还是默认配置里的color值, 感觉是父组件传递的color属性没有覆盖默认配置里的color属性

**Comment by sonicsunsky** [comment]
复现代码:
<up-text text="测试color属性" size="30rpx" color="#fff"></up-text>
设置文本颜色为白色不生效

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/65bad821-37c8-4e5d-ae6f-cc32f822f690)
