### ISSUE TITLE
3.2.22版本input表单 confirm事件无法触发

### ISSUE THREAD

**Issue by gouxiwen** [ijry/uview-plus#369]
3.2.22版本input表单 confirm事件无法触发，之前的3.1.49版本也一样
代码如下
template
<u--input
          clearable
          placeholder="姓名/公司/职位"
          v-model="searchValue"
          confirmType="search"
          border="none"
          fontSize="12px"
          @confirm="handleSearch"
        ></u--input>

script
const handleSearch = (v) => {
  console.log('搜索', v)
}

结果是无法触发，uniapp的input表单可以触发

**Comment by ijry** [comment]
最新版经测试均能触发请重试
