### ISSUE TITLE
up-tabbar自定义tabbar闪烁问题

### ISSUE THREAD

**Issue by 1577797057** [ijry/uview-plus#371]
请问一下使用up-tabbar结合原生tabbar的switchTab跳转方式的时候，进入一个未加载过的新页面的时候tabbar会闪烁一下，但是第二次进入就不会闪烁了，请问这个问题如何解决呀，其中官网中关于tabbar组件使用示例的例子也有此问题。
![image](https://github.com/ijry/uview-plus/assets/74478962/81844dca-f838-46b6-8254-009f3b77057a)

**Comment by ijry** [comment]
fixed

**Comment by ijry** [comment]
你这个截图为啥是uview2

**Comment by Guocheng-c** [comment]
因为是组件的，第一次会进行渲染，第二次是因为有缓存了，就不用重新渲染
