### ISSUE TITLE
ActionSheet 组件的取消按钮触发区域太小

### ISSUE THREAD

**Issue by Jiexiansen** [ijry/uview-plus#372]
ActionSheet 组件的取消按钮只能点击文本才可以触发取消功能，希望可以扩大触发区域，如点击整行均可触发取消功能

![image](https://github.com/ijry/uview-plus/assets/26481272/31f99627-1739-4b04-a949-e1e3d37973e2)

uview-plus版本：`"^3.2.22"`

文档：https://uview-plus.jiangruyi.com/components/actionSheet.html

**Comment by ijry** [comment]
fixed
