### ISSUE TITLE
u-number-box 在ios上无法连续点击

### ISSUE THREAD

**Issue by Rayzworld** [ijry/uview-plus#375]
在安卓上可以 ios不行

`<view
		    class="u-number-box__slot"
		    @tap.stop="clickHandler('plus')"
		    @touchstart="onTouchStart('plus')"
		    @touchend.stop="clearTimeout"
		    v-if="showPlus && $slots.plus"
		>
			<slot name="plus" />
		</view>`
		
	经测试是由@touchend.stop的stop引起的 
	现象有点像加了防抖  每次点击都会走onTouchStart  停止点击后 过xxx ms然后走了一次clickHandler
	如果改成@touchend 每次都会走clickHandler
        想问下我把touchend的stop去了 会引起什么问题吗 或者是为了解决什么问题加了stop
        感谢

**Comment by ijry** [comment]
.stop是防止点击事件冒泡到父组件的，没有相关需求去掉也行。缺少iOS证书暂时没法调试iOS的情况。

**Comment by ijry** [comment]
我用ios模拟器跑了下似乎没问题啊
