### ISSUE TITLE
H5 u-input  在表单中初始值为空也会触发一次 formValidate(this,"change")事件导致进入页面直接校验了一次

### ISSUE THREAD

**Issue by QHSsss** [ijry/uview-plus#378]
![image](https://github.com/ijry/uview-plus/assets/120435958/866a0ded-d5a9-4964-a692-5686749ff557)
在line 158建议加上一次firstChange的判断，让第一次不走校验
if(!this.firstChange) formValidate(this, "change");

**Comment by ijry** [comment]
👌
