### ISSUE TITLE
form表单报错

### ISSUE THREAD

**Issue by akinstrument** [ijry/uview-plus#379]
Syntaxerror: Unexpected token .
![A2A51EC7FC8C817EDCFE0A6955BC7C53](https://github.com/ijry/uview-plus/assets/1661385/a8055961-ce70-4b47-a7a1-ad0e771d7ea0)
![Uploading 7ABB7BF78BDDBF03AC8E12EE706FDC0D.png…]()

**Comment by ijry** [comment]
可选链支持因为HBuilderX内置的浏览器版本太低导致，不要使用内置浏览器即可。
