### ISSUE TITLE
up-modal 无法同时设置确定取消按钮的样式

### ISSUE THREAD

**Issue by expanding** [ijry/uview-plus#381]
有自定义模态框的需求

up-modal 无法同时设置确定取消按钮的样式，且无法给模态框自定义class名，如果可以自定义class名可以添加样式进行覆盖

**Comment by ijry** [comment]
u-modal__button-group__wrapper样式穿透

**Comment by chergn** [comment]
`::v-deep` `/deep/` `>>>` `:v-deep()`都试了，不管用https://ask.csdn.net/questions/8140882
