### ISSUE TITLE
up-button 微信小程序自定义的class不生效，app和h5正常

### ISSUE THREAD

**Issue by codergzh** [ijry/uview-plus#382]
源码：
<up-button
        text="已加入"
        size="small"
        color="#F8F8F8"
       class="check"
        @tap="handleAddCompare(false, item)"
></up-button>
运行在微信小程序中：
<button class="u-button u-reset-button data-v-52094d52 u-square u-small">
没有自定义的class

**Comment by ijry** [comment]
这是微信小程序自己限制，可以开启virtualHost并配置HBuilderX的mergeAttebute开头那个参数。
