### ISSUE TITLE
3.2.23 Cell 单元格组件label位置异常

### ISSUE THREAD

**Issue by qcjackman** [ijry/uview-plus#385]
u-cell的`label`属性内容应该在`title`下方吧，3.2.23版本在一行了，看样式也确实没有做换行处理。

```
<u-cell title="标题" label="描述"></u-cell>
```

![image](https://github.com/ijry/uview-plus/assets/12554120/2a260112-f046-4934-aee8-1f362352d662)

**Comment by ijry** [comment]
fixed
