### ISSUE TITLE
u-form 组件异步校异常验问题

### ISSUE THREAD

**Issue by chenyuan8059** [ijry/uview-plus#393]
在 u-form 组件在使用过程中调用 validate 方法校验数据时，使用 { asyncValidator: ()=>{} } 异步校验规则时， validateField 方法未等待异步校验结果直接调用了 callback 回调函数。
 
![2024-06-12_113749](https://github.com/ijry/uview-plus/assets/4230527/5088e5c7-e431-45ad-8202-c0dc94684e66)

**Comment by ijry** [comment]
fixed@3.3.10
