### ISSUE TITLE
up-cell的required配置不生效

### ISSUE THREAD

**Issue by jiaruiyan** [ijry/uview-plus#395]
如图所示 已经添加该配置项

![image](https://github.com/ijry/uview-plus/assets/66373324/e2e81268-7a2f-402c-ae70-dbf0bbdb232d)

页面效果如图所示
![image](https://github.com/ijry/uview-plus/assets/66373324/349728b6-9512-48d5-87f7-e01f7480f1e2)

**Comment by ijry** [comment]
fixed@3.3.7
