### ISSUE TITLE
Collapse 折叠面板 中 Collapse Item Props 的 isLink属性不生效

### ISSUE THREAD

**Issue by Aipubor** [ijry/uview-plus#399]
设置isLink为false后，折叠面板右侧箭头不会被隐藏

对u-collapse-item中的代码查看后，在其内部引用的组件中u-cell隐藏箭头的条件为  $slots['right-icon'] || isLink
而在u-collapse-item vue文件中默认使用的right-icon命名插槽，导致$slots['right-icon']值默认为true 致使isLink属性失效
![1718862359639](https://github.com/ijry/uview-plus/assets/108812315/87d368c1-6cb4-42b8-bb47-633aa5a4b98e)

![1718862296949](https://github.com/ijry/uview-plus/assets/108812315/0e8e6538-ab47-4c53-9597-942da4023795)

**Comment by Aipubor** [comment]
此处disbled字段应为disabled，在u-collapse-item组件上使用字段时，提示的是错误的字段disbled
![1718864239332](https://github.com/ijry/uview-plus/assets/108812315/93bf8491-6556-4517-8cf6-bab86be4f33c)

**Comment by Aipubor** [comment]
版本为3.1.48

**Comment by Aipubor** [comment]
更新至3.2.24同样的错误

**Comment by DeepSea141** [comment]
> 更新至3.2.24同样的错误

你的解决了蛮，我也遇到了

**Comment by ijry** [comment]
因微信小程序不支持slot穿透，现在已单独增加showRight属性控制。
