### ISSUE TITLE
vue-cli脚手架建的uni-app，在根目录下的src文件创建npm，已引入sass依赖，不是版本问题，仍not found

### ISSUE THREAD

**Issue by virgouss** [ijry/uview-plus#404]
引入uview之后引入样式依赖，启动npm run dev:mp-weixin，仍旧报错 [plugin:vite:css] Preprocessor dependency "sass" not found. Did you install it?
node版本18.19.0
查询了sass-loader 匹配的就是8+版本

"devDependencies": {
    "sass": "^1.35.1",
    "sass-loader": "^8.0.2"
  }

**Comment by ijry** [comment]
看起来可能是缓存
