### ISSUE TITLE
form-item设置rule报错，单独设置rule不起作用

### ISSUE THREAD

**Issue by lanix516** [ijry/uview-plus#410]
![1719844647535](https://github.com/ijry/uview-plus/assets/12050749/c2551957-a6ec-4218-b06a-5074f19d1407)
:rule="{ required: true, message: '请输入' ,trigger:'change'}"
版本3.3.2 / 3.2.15
文档中提示rule为object，代码props.js中是string

**Comment by ijry** [comment]
3.3.11以变更为rules参数，传入数组。
