### ISSUE TITLE
vue警告，懒加载少定义了一个emits吧？

### ISSUE THREAD

**Issue by SAO-Asuna** [ijry/uview-plus#413]
![image](https://github.com/ijry/uview-plus/assets/35756695/785cc82a-c2fe-448a-aba1-e83eaa64be04)
![image](https://github.com/ijry/uview-plus/assets/35756695/e4213d16-e1a2-469b-8ff2-b11f71dafa7d)
![image](https://github.com/ijry/uview-plus/assets/35756695/410ce052-31bf-47fe-a9cd-6d5f123ed7ff)

**Comment by ijry** [comment]
fixed
