### ISSUE TITLE
up-button 点击事件失效

### ISSUE THREAD

**Issue by wzjiscode** [ijry/uview-plus#418]
up-button 点击事件失效
<up-button
	@clcik="getLoginHandler" 
	text="登录">
</up-button>

getLoginHandler不触发

**Comment by yangmingqi123** [comment]
> up-button 点击事件失效 <up-button @clcik="getLoginHandler" text="登录">
> 
> getLoginHandler不触发

单词拼错了@click

**Comment by wzjiscode** [comment]
感谢 肝了好久原来如此
