### ISSUE TITLE
up-upload 组件为什么一次性只能选择传9个

### ISSUE THREAD

**Issue by ywenhao** [ijry/uview-plus#420]
`uview-plus\src\uni_modules\uview-plus\components\u-upload\utils.js`

![image](https://github.com/ijry/uview-plus/assets/37856060/c35a51e0-7c88-4bdc-86b1-1896cdd16d97)

我觉得不合理，用户需要9张9张的选，出于什么考虑的呢？我觉得应该不限制，如果需要限制，让开发者可配置。

**Comment by ijry** [comment]
因为没权利，平台限制的。
![IMG_2961](https://github.com/ijry/uview-plus/assets/3102798/0508326c-4b61-4f24-ae73-24cccf2348ca)

**Comment by ywenhao** [comment]
![image](https://github.com/ijry/uview-plus/assets/37856060/01c223a3-d47f-4220-a0c7-0a527968ec9a)
![image](https://github.com/ijry/uview-plus/assets/37856060/ace8aa2f-06c3-4a56-9c46-87474f07244a)

查看uni文档只有chooseMedia 的才是有这个限制，chooseMedia是不支持h5的，uni文档chooseImage没有写这个限制，微信小程序的文档写的又不一样了，我这里是测试的h5开发，没有用ios测试，测试不够充分，估计需要多个设备多个环境进行测试调优才行
