### ISSUE TITLE
upload slot编译bug

### ISSUE THREAD

**Issue by ywenhao** [ijry/uview-plus#423]
[vuejs/core#10728](https://github.com/vuejs/core/issues/10728)

[uniapp#5030](https://github.com/dcloudio/uni-app/issues/5030)

upload slot编译bug

修复参考代码
```vue
 <component v-if="$slots.default" :is="$slots.default" />
  <template v-else> default-value</template>
```
参考代码
```vue
<slot v-if="$slots.trigger" name="trigger" />
<slot v-if="!$slots.trigger && $slots.default" />
 ```
[element-plus/upload](https://github.com/element-plus/element-plus/blob/dev/packages/components/upload/src/upload.vue)

用具名插槽应该可以完美修复这个bug

**Comment by ijry** [comment]
感谢，已采纳@3.3.7。

**Comment by ywenhao** [comment]
> 感谢，已采纳@3.3.7。

文档也更新一下
