### ISSUE TITLE
ActionSheet 操作菜单cancelText属性不传时页面也加载出了取消按钮的dom，点击可以取消

### ISSUE THREAD

**Issue by maomenglan** [ijry/uview-plus#426]
官网中的示例可以看到

**Comment by maomenglan** [comment]
![d8b90a365202f166ebe3107f7615c733](https://github.com/user-attachments/assets/61ce8fcc-9f48-49f4-88c2-48d2a97d5dcf)

**Comment by ijry** [comment]
fixed@3.3.7
