### ISSUE TITLE
怎么配置组件和class以及全局 $uv 都和uview2一样

### ISSUE THREAD

**Issue by yizems** [ijry/uview-plus#427]
我准备把我们的项目整体迁移到vue3, 我感觉应该有办法将 up-, 这种开头的东西都改到 u- , 和uview2一样

因为我们后面还要做鸿蒙app, 所以想请教下是否有方便的方法

**Comment by ijry** [comment]
不用改，本来两种都是支持的。

**Comment by yizems** [comment]
好的, 谢谢
