### ISSUE TITLE
up-input编译到支付宝小程序时有个问题

### ISSUE THREAD

**Issue by sbbs3626** [ijry/uview-plus#430]
当input设置 type = number 或 digit 后，支付宝小程序 npm  run dev 时， 支付宝开发者工具和 iphone获取不到值，安卓正常获取

`
const form = ref({
	mobile: '',
	smsCode: ''
})

<up-input` type="number" v-model="form.mobile" border="none" placeholder="请输入手机号"></up-input>

`

**Comment by ijry** [comment]
当maxlength默认值为-1时会触发此问题，疑似uni-app的问题,，可以指定一个maxlength。新版本3.3.10已调整默认长度为140。
