### ISSUE TITLE
up-form封装成组件无法双向绑定，数据更新视图不更新，且有值的校验不通过

### ISSUE THREAD

**Issue by lq527266969** [ijry/uview-plus#433]
vue3中，up-form封装成组件无法双向绑定，数据更新视图不更新，且有值的校验不通过。且单独封装up-input也双向绑定失效
![image](https://github.com/user-attachments/assets/b1e600a1-d51b-4d2f-aec7-ba68e1c390e4)

**Comment by lq527266969** [comment]
![image](https://github.com/user-attachments/assets/f782489d-3e19-46bb-a8fb-713d81c8f0af)

![image](https://github.com/user-attachments/assets/f134b334-a86f-449c-ab82-4b715158dd81)

**Comment by szhang6** [comment]
请问你在使用 form 组件的时候，在微信开发者工具中，遇到过下面错误吗？
<img width="643" alt="image" src="https://github.com/user-attachments/assets/50a24785-129c-4266-8a39-c36a76ee74eb">

谢谢～
