### ISSUE TITLE
up-popup在组件里面使用出现层级问题 目前仅在IOS系统使用有问题

### ISSUE THREAD

**Issue by 736048546** [ijry/uview-plus#434]
![17547973afecab03f235ba31d6e82a6](https://github.com/user-attachments/assets/68bb2136-8fbb-40ba-ae03-a998d6dc684d)

仅在IOS端并且是子组件调用的时候出现该问题，但是mode=top时候正常 如果不等于top则无法在最上层弹窗

安卓手机正常

**Comment by 736048546** [comment]
目前IOS使用时间组件和自身直接使用up-popup 从底部弹出都会出现该问题

**Comment by 736048546** [comment]
发现问题如果使用DatetimePicker 点击确认后 当前组件所有的up-popup 都会出现上面的问题，如果点击取消就没问题

**Comment by yangmingqi123** [comment]
up-popup 有 zIndex 属性 默认  10075

**Comment by 736048546** [comment]
已经处理了，感谢您的回复

**Comment by ijry** [comment]
支持自定义popup的zIndex
