### ISSUE TITLE
up-form的新建校验生效，但是编辑校验不生效。

### ISSUE THREAD

**Issue by hudaye100200** [ijry/uview-plus#438]
![image](https://github.com/user-attachments/assets/fd8a8e50-1fcb-4ecc-9154-b1f8725b74b9)
![image](https://github.com/user-attachments/assets/937b09ce-71ea-4fd3-b810-83071eadcffd)
![image](https://github.com/user-attachments/assets/04ec9a49-2456-4cc7-a0f3-db6563d1129a)
![image](https://github.com/user-attachments/assets/ff1f0c7f-efae-4ff8-84c9-5e0d64a2131f)

**Comment by ijry** [comment]
没看明白，左右俩有啥却别吗？
