### ISSUE TITLE
在vue3+vite的项目中，pnpm下载之后，配置page.json的esaycom引入，无法解析

### ISSUE THREAD

**Issue by bingxuelang** [ijry/uview-plus#441]
esaycom引入如下：
easycom: {
    autoscan: true,
    custom: {
      '^u-(.*)': 'uview-plus/components/u-$1/u-$1.vue',
    },
  },

编译后浏览器控制台警告如下，且页面没有渲染出预期的效果：
xxx.vue:26 [Vue warn]: Failed to resolve component: up-rate
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
 at <Login>
at <AsyncComponentWrapper>
at <PageBody>
at <Page>
at <Anonymous>
at <KeepAlive>
at <RouterView>
at <Layout>
at <App>
xxx.vue:1 [Vue warn]: Property "safeAreaInsets" was accessed during render but is not defined on instance. 
 at <View>
at <WdConfigProvider>
at <Default>
at <Login>
at <AsyncComponentWrapper>
at <PageBody>
at <Page>
at <Anonymous>
at <KeepAlive>
at <RouterView>
at <Layout>
at <App>

**Comment by ijry** [comment]
根据历史反馈99%是很低缓存

**Comment by chergn** [comment]
只有我觉得[sard-uniapp](https://sutras.github.io/sard-uniapp-docs/#/guide/intro)好用吗？
