### ISSUE TITLE
全局引入，局部引入组件，esaycom引入都试过了。都是无法解析

### ISSUE THREAD

**Issue by bingxuelang** [ijry/uview-plus#442]
esaycom引入如下：
easycom: {
    autoscan: true,
    custom: {
      '^u-(.*)': 'uview-plus/components/u-$1/u-$1.vue',
    },
  },

编译后浏览器控制台警告如下，且页面没有渲染出预期的效果：
xxx.vue:26 [Vue warn]: Failed to resolve component: up-rate
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by axinss** [comment]
你使用的标签语法和你这里设置的正则无法匹配。所以，才报错无法解析。再好好看看文档 [https://uiadmin.net/uview-plus/components/downloadSetting.html](uview-plus)
