### ISSUE TITLE
up-tabs 组件，使用后，右边会有红色点

### ISSUE THREAD

**Issue by Lovely-Ruby** [ijry/uview-plus#443]
问题图片：

![image](https://github.com/user-attachments/assets/8b79568a-1087-403a-bcf7-01449b50c347)

代码片段：
```vue
<template>
<up-tabs :list="list1" :activeStyle="{ color: '#fff', fontWeight: 'bold' }" :inactiveStyle="{ color: 'rgba(128, 128, 128, 1)' }" lineColor="#fff" lineWidth="40"></up-tabs>
</template>
<script>
const list1 = reactive([{ name: '未开始' }, { name: '生产中' }, { name: '已暂停' }])
</script>
```

检查一下是 u. badge 这个类的问题

![image](https://github.com/user-attachments/assets/ce40102b-26f4-45ca-995d-51864b166ee5)

**Comment by axinss** [comment]
怎么看怎么像你设置了。要不就是有缓存你没重新加载
