### ISSUE TITLE
index-list 组件在弹窗中使用时右侧排列的字母显示有问题

### ISSUE THREAD

**Issue by zhangtao98** [ijry/uview-plus#444]
![image](https://github.com/user-attachments/assets/88930f42-7132-42b6-92d8-5b4264583782)

**Comment by zhangtao98** [comment]
当左侧列表中显示的是Z时  右侧对应高亮的字母没对上，只是举个例子哈  其他字母也一样

**Comment by ijry** [comment]
fixed@3.3.8

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/3caec211-3150-43c0-be38-49b5445a8050)
