### ISSUE TITLE
tabs修改current后不会移动到修改后的标签处

### ISSUE THREAD

**Issue by WesySu** [ijry/uview-plus#446]
<up-tabs :list="tabList" @click="clickTab" ref="tabsRef" :current="currentTabIndex">

**Comment by axinss** [comment]
有图片参考吗？传的是什么值

**Comment by WesySu** [comment]
> 有图片参考吗？传的是什么值

索引值，目前只能这样解决了，tabsRef.value.clickHandler(tabsRef.value.list[0], 0);

**Comment by axinss** [comment]
感觉这个需求怪怪的。current只是为了设置默认位置的初始索引，为什么要动态传递索引呢？

**Comment by ijry** [comment]
什么版本我看是有watch监听current的。
![image](https://github.com/user-attachments/assets/8d1d3fa1-d1c8-4358-890b-3ee8c47605b3)
