### ISSUE TITLE
u-tab微信小程序点击会有蓝色背景

### ISSUE THREAD

**Issue by hao-xh** [ijry/uview-plus#449]
#396 如题，还是cursor:pointer属性导致的问题，给加个判断条件吧
<img width="1771" alt="iShot_2024-07-25_16 00 04" src="https://github.com/user-attachments/assets/39a4c54a-ed57-4502-961f-cc07dcd7a7cf">

**Comment by hao-xh** [comment]
补充：3.3.6版本

**Comment by ijry** [comment]
fixed@3.3.7
