### ISSUE TITLE
 import('/config/request.js') 

### ISSUE THREAD

**Issue by lixiaofa** [ijry/uview-plus#45]
![image](https://user-images.githubusercontent.com/23230215/200550746-1777ce5c-5dfc-49a1-a505-086fd20ec3f6.png)
import 没有工作
@13799433448 
@html546 
@huodoushigemi

**Comment by huodoushigemi** [comment]
这可能是 uniapp 的 bug

**Comment by lixiaofa** [comment]
我想问一下，怎么解决，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月08日 19:38 |
| 收件人 | ***@***.***> |
| 抄送至 | Sima ***@***.******@***.***> |
| 主题 | Re: [ijry/uview-plus] import('/config/request.js') (Issue #45) |

这可能是 uniapp 的 bug

**Comment by huodoushigemi** [comment]
> 

为什么不能将 import ‘@/config/request.js’ 放上面？

**Comment by lixiaofa** [comment]
放过了 ， 也不工作

**Comment by huodoushigemi** [comment]
看看你的 `request.js` 代码

**Comment by lixiaofa** [comment]
而且 ，你们文档也是这样写的
![image](https://user-images.githubusercontent.com/23230215/200558010-99cb2989-6d65-4cd3-9527-c87fee66697e.png)

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200558086-9bbbd28f-da03-4fea-a375-83de7829301d.png)

**Comment by lixiaofa** [comment]
我就是按照你们文档写的， 没有改动

**Comment by huodoushigemi** [comment]
将这行代码 `import('@/config/request.js')` 放到 `app.use(uviewPlus)` 下面试试

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200559569-12da92ae-8f9d-409e-9453-b50c8944a546.png)

**Comment by lixiaofa** [comment]
报错

**Comment by huodoushigemi** [comment]
看看19行的代码

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200560378-4128d91e-c11e-4c41-84db-bfd21bb54d9e.png)

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200560378-4128d91e-c11e-4c41-84db-bfd21bb54d9e.png)

**Comment by lixiaofa** [comment]
和这个没关系吧， 他是引入的文件不工作

**Comment by 13799433448** [comment]
> 和这个没关系吧， 他是引入的文件不工作

看看 你引入的文件怎么写的

**Comment by lixiaofa** [comment]
上面两种图， 是我 发请求 的代码

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200563381-974807bb-538c-49d1-b180-de36fd155a4f.png)
引入文件两个都加了 ， 还是不工作

**Comment by lixiaofa** [comment]
而且，对于这种写法， 我也很疑惑， import 应该放在顶层

**Comment by huodoushigemi** [comment]
你可以尝试将这么写
```js
import uviewPlus from "uview-plus";
import '@/config/request.js'

export function createApp() {
  const app = createSSRApp(App);
  app.use(uviewPlus);
  return { app };
}
```

**Comment by lixiaofa** [comment]
![image](https://user-images.githubusercontent.com/23230215/200567658-66db813d-7173-4303-a614-cfcf355dc77a.png)

**Comment by huodoushigemi** [comment]
将第一句 `import('@/config/request.js')` 改为 `import '@/config/request.js'`

**Comment by lixiaofa** [comment]
> 将第一句 `import('@/config/request.js')` 改为 `import '@/config/request.js'`

我们可以在main.js中引用/config/request.js，注意引用的位置，需要在new Vue得到Vue实例之后，
这个时机是错的

谢谢， 非常感谢
