### ISSUE TITLE
slider 中间线条高度给了不生效

### ISSUE THREAD

**Issue by woshishulai** [ijry/uview-plus#451]
`			<up-slider height="20rpx" v-model="value" min="1" max="5"></up-slider>`

**Comment by woshishulai** [comment]
版本是vue3+nvue+uview+plus

**Comment by ijry** [comment]
因slider使用原生slider组件实现，原生组件暂不支持height参数，文档种出现的应为uview2误写。

**Comment by ijry** [comment]
已重写的slider组件可以支持height@3.3.7
