### ISSUE TITLE
up-checkbox 单独提示 u-checkbox必须搭配u-checkbox-group组件使用

### ISSUE THREAD

**Issue by 736048546** [ijry/uview-plus#452]
已经按照文档设置了usedAlone属性还是一直反馈该错误，不过目前没有影响使用。
![image](https://github.com/user-attachments/assets/103c3e57-f997-4736-86d6-fd78660b6606)

**Comment by ijry** [comment]
版本号多少呢

**Comment by 736048546** [comment]
微信基础库3.4.10，UI库版本3.2.24

**Comment by 736048546** [comment]
![image](https://github.com/user-attachments/assets/a03e65a6-139a-44c3-811a-7c9f9375c9b3)

**Comment by ijry** [comment]
升级到最新版消除提示
