### ISSUE TITLE
nvue环境中依然存在编译警告，另外tabbar组件在nvue环境中出现不显示text的bug

### ISSUE THREAD

**Issue by China-Robin** [ijry/uview-plus#458]
<img width="998" alt="image" src="https://github.com/user-attachments/assets/67571d82-e7ed-45de-8492-bbb3b17fdff4">

**Comment by China-Robin** [comment]
排查了一下原因，发现tabbar-item中设置了width100%和height100%导致的，但是修改了之后，tabbar在nvue和vue环境混用的话会出现错位1px的问题，也就是切换tabbar会产生晃动的感觉

**Comment by ijry** [comment]
文本不显示fixed@3.3.8
