### ISSUE TITLE
内置样式不生效

### ISSUE THREAD

**Issue by lixiaofa** [ijry/uview-plus#46]
![image](https://user-images.githubusercontent.com/23230215/201074576-40961fe4-aec8-4e35-b2ba-6bf2ee4c3f6c.png)
@html546 @huodoushigemi @13799433448

**Comment by wlsh** [comment]
> ![image](https://user-images.githubusercontent.com/23230215/201074576-40961fe4-aec8-4e35-b2ba-6bf2ee4c3f6c.png) @html546 @huodoushigemi @13799433448

uview plus移除了u-m、u-p等内置css

**Comment by ijry** [comment]
uview plus未移除此功能，是因为uview2.0本身没有此功能。
