### ISSUE TITLE
安卓手机 微信小程序  up-icon 显示异常bug

### ISSUE THREAD

**Issue by hexiaogou** [ijry/uview-plus#460]
安卓手机显示异常

<img width="376" alt="Screenshot 2024-07-30 at 2 15 57 PM" src="https://github.com/user-attachments/assets/fe9255e1-8106-4447-b6f3-1dcead606d37">

苹果手机显示正常
<img width="390" alt="Screenshot 2024-07-30 at 2 16 59 PM" src="https://github.com/user-attachments/assets/b4b84b97-3f07-4890-81bc-fe779a1968f2">

求大佬帮助！

**Comment by ijry** [comment]
将https://at.alicdn.com/t/font_2225171_8kdcwk4po24.ttf文件放自己服务器，然后修改u-icon.vue里面font-face试下。
