### ISSUE TITLE
up-input nvue 页面 使用focus方法报错

### ISSUE THREAD

**Issue by zhangxushiyong** [ijry/uview-plus#469]
在nvue页面使用 input 需要点击按钮实现输入框聚焦 根据文档提示需要调用focus方法 但是报错了该怎么解决
![a2bd29ac21581307b35ada904d61e4db](https://github.com/user-attachments/assets/8ea67b4b-5292-4f90-8e1e-9dd57c4568b8)

**Comment by ijry** [comment]
```
在u-input的methods里增加
focus() {
    this.$refs['input-native'].focus();
},
blur() {
    this.$refs['input-native'].blur();
}
```
再加这个试下
![image](https://github.com/user-attachments/assets/e1d97b93-3b47-4474-8739-41f16418aa89)
