### ISSUE TITLE
up-swiper无法自定义模版内容

### ISSUE THREAD

**Issue by leezozz** [ijry/uview-plus#473]
<up-swiper
				:autoplay="false"
			>
				<view class="">推荐。。。</view>
				<view class="">咨询。。。</view> 
			</up-swiper>

**Comment by leezozz** [comment]
上面代码在小程序中运行会报错：<swiper>: display-multiple-items 不能大于 swiper-item 数量。如何自定义模版呢？

**Comment by ijry** [comment]
```
<up-swiper
          :list="list1"
          @change="change"
          @click="click"
>
<template #default="scope">自定义</template>
</up-swiper>
```

**Comment by leezozz** [comment]
<up-swiper
				:autoplay="false"
				:list="testLists"
			>
				<template #default="scope">
					<view class="" v-for="(item) in testLists" :key="index">
						<text>{{ item }}</text>
					</view>
				</template>
			</up-swiper>
			// 这样修改了，想要显示自定义文本，但是显示：[渲染层网络层错误] Failed to load local image resource /node-modules/uview-plus/components/u-swiper/111 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)

**Comment by leezozz** [comment]
如何在up-swiper中使用自定义好的组件，列如可能是列表图画像也可能是视频。如何实现呢？请使用vue3语法
