### ISSUE TITLE
 h5自定义导航 u-index-list设置customNavHeight后，索引列表点击后跳转的和显示的不一致

### ISSUE THREAD

**Issue by datasre** [ijry/uview-plus#475]
问题：h5自定义导航 u-index-list设置customNavHeight后，索引列表点击后跳转的和显示的不一致，像是发生了偏移,我点击的索引为E但是跳转到了B

uview-plus版本:3.3.18

**Comment by ijry** [comment]
现在应该不用customNavHeight了，你直接设置u-index-list组件的高度。

**Comment by datasre** [comment]
直接设置高度是正常的，那customNavHeight这个属性现在是不能用了么，我看官网上的api文档里面还是有这个属性

**Comment by ijry** [comment]
嗯这个参数后边没用就废弃掉了
