### ISSUE TITLE
设置单位为rpx时，addUnit函数返回NaN，导致很多传入单位有问题

### ISSUE THREAD

**Issue by iq001** [ijry/uview-plus#476]
当传入带单位数值时，如320rpx，addunit函数会返回NaN

export function addUnit(value = 'auto', unit = '') {
	if (!unit) {
		unit = config.unit || 'px'
	}
	if (unit == 'rpx') {
		value = value * 2  **//----这个地方导致value变成了NaN**
	}
	value = String(value)  
	// 用内置验证规则中的number判断是否为数值
	return testNumber(value) ? `${value}${unit}` : value
}

**Comment by ijry** [comment]
fixed@3.3.19
