### ISSUE TITLE
up-checkbox使用usedAlone，v-model:checked无效

### ISSUE THREAD

**Issue by ye971829766** [ijry/uview-plus#477]
![FabConvert com_qq2024814-101523-hd](https://github.com/user-attachments/assets/95a1e5ec-9941-4928-9186-7d94f9ef394e)
![微信截图_20240814101928](https://github.com/user-attachments/assets/a0f19b4d-3f45-4f99-ac59-22d19e37641b)
![微信截图_20240814101936](https://github.com/user-attachments/assets/33fdb6da-9285-4af2-9821-46620347d445)

**Comment by ijry** [comment]
https://github.com/user-attachments/assets/a65d8209-4a80-4acf-8a1d-d0629852c1ea

**Comment by ye971829766** [comment]
> 20240814_104207.mp4

通过外部驱动可以，但是点击组件本身，v-model就没用了

**Comment by ijry** [comment]
看我视频，本组件也可以，升级到最新版。

**Comment by ye971829766** [comment]
> 看我视频，本组件也可以，升级到最新版。

升级后可以了，麻烦你了，谢谢

**Comment by ijry** [comment]
不客气
