### ISSUE TITLE
up-swiper自定义item内容

### ISSUE THREAD

**Issue by leezozz** [ijry/uview-plus#478]
**问题描述**
还是无法在up-swiper中正常使用自定义内容

**截图**
![image](https://github.com/user-attachments/assets/9409e0d3-dbd0-4773-883c-307a4cd8571b)

**Comment by ijry** [comment]
官网示例这个就是自定义的可以参考
<img width="606" alt="image" src="https://github.com/user-attachments/assets/975e9ced-6800-4fcf-bc20-350e8d369d4d">

**Comment by ijry** [comment]
你这个里面不要用v-for了，插槽默认就是单个swiper。
