### ISSUE TITLE
刚更新了最新版本，uni.$u这个对象是undefined？是改了吗

### ISSUE THREAD

**Issue by codepeng1** [ijry/uview-plus#480]
在js文件中访问uni.$u是undefined，之前的老版本是可以的

**Comment by codepeng1** [comment]
uniapp hbuilderx创建的vue3项目

**Comment by KBWriting** [comment]
> 在js文件中访问uni.$u是undefined，之前的老版本是可以的

3.2.x版本后更新引入方式了, 3.1.41 版本没问题
