### ISSUE TITLE
Steps 步骤条提示 u-steps-item 必须要搭配 u-steps 组件使用

### ISSUE THREAD

**Issue by maxsky** [ijry/uview-plus#492]
**问题描述**

Steps 步骤条提示 u-steps-item 必须要搭配 u-steps 组件使用

**复现步骤**

```vue
<u-steps current="1" direction="column">
    <u-steps-item title="已下单" desc="10:30">
    </u-steps-item>
    <u-steps-item title="已出库" desc="10:35">
    </u-steps-item>
    <u-steps-item title="运输中" desc="11:40"></u-steps-item>
</u-steps>
```

**预期行为**

正确显示步骤条

**截图**

![QQ20240822-174055](https://github.com/user-attachments/assets/6bc53b9f-1068-4a07-adc6-810d7bfc2941)
![QQ20240822-174126](https://github.com/user-attachments/assets/ed5f6fa6-cd9d-4051-b73f-e18cc60edcca)

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.24]

**平台（请填写以下信息）**：
- 平台：H5

**Comment by maxsky** [comment]
更新至 3.3.26 后该问题已修复

**Comment by chergn** [comment]
这个组件线条的height直接用css就能控制
![image](https://github.com/user-attachments/assets/c2af3e05-437b-4885-9b0b-376c539177d3)
不然展开前的高度固定了，展开后还是那个高度
![image](https://github.com/user-attachments/assets/094289f6-bd06-4982-b0ec-80602d244a0c)
