### ISSUE TITLE
waterfall vue3 运行微信小程序或者app 不显示内容 加载不出来

### ISSUE THREAD

**Issue by sx13694658890** [ijry/uview-plus#493]
**问题描述**
清晰地描述该错误是什么。
在微信小程序使用该组件页面不显示
**复现步骤**
复现该行为的步骤：
1. 前往'...'
2. 点击'....'
3. 滚动到'....'
4. 查看错误

**预期行为**
清晰地描述你期望发生什么。

**截图**
如果适用，请添加截图以帮助解释你的问题。

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.8]
- 开发者工具版本：[例如 微信开发者工具1.0.1]

**平台（请填写以下信息）**：
- 平台：[例如 微信小程序iOS]

**智能手机（请填写以下信息）**：
- 设备：[例如 iPhone6]
- 操作系统：[例如 iOS8.1]
**其他上下文**
在此处添加有关问题的任何其他上下文。

**Comment by ijry** [comment]
升级到最新版
