### ISSUE TITLE
u-tabs  current 如果是string类型不会触发textStyle计算属性的正确触发

### ISSUE THREAD

**Issue by QHSsss** [ijry/uview-plus#498]
uview-plus 版本号 3.3.28
微信小程序
u-tabs  current 如果是string类型不会触发textStyle计算属性的正确触发
![image](https://github.com/user-attachments/assets/3089bc1e-5a72-4c01-9684-2ceacd6d144d)
![image](https://github.com/user-attachments/assets/dfd27503-ed44-46da-a182-c677e534e4dd)
![image](https://github.com/user-attachments/assets/614c6a3d-2f7a-457a-934d-d3653b6b8ae3)
![image](https://github.com/user-attachments/assets/45555631-2a3b-4d82-827c-899927e1d9db)
按照设置来说  设置2的话 第三个滑块应该是激活状态的颜色  也就是#1D4EB1 结果不是

源码视角
![image](https://github.com/user-attachments/assets/523a9146-6341-4772-9282-0c7fb9f66ac4)
这个地方用 == 就行了，源码中update:current 返回的都是number类型，用===会导致2和'2'不相等

**Comment by ijry** [comment]
ok
