### ISSUE TITLE
默认头像不显示

### ISSUE THREAD

**Issue by lixiaofa** [ijry/uview-plus#50]
![image](https://user-images.githubusercontent.com/23230215/201570817-1cbf23e2-57ce-47ab-b390-b7a8c809c668.png)
@html546 @huodoushigemi @13799433448

**Comment by ijry** [comment]
经试验，头像显示无问题，请提供demo工程。
<img width="337" alt="image" src="https://user-images.githubusercontent.com/3102798/212655603-b493ee50-ce01-4bdc-940d-a9669f8d7e0c.png">
