### ISSUE TITLE
不支持uniappx？

### ISSUE THREAD

**Issue by veako** [ijry/uview-plus#502]
**您的功能请求是否与某个问题相关？请描述。**
清晰地描述存在什么问题。例如，我总是感到沮丧，因为[...]

**描述您想要的解决方案**
清晰而简洁地描述您希望发生什么。

**描述您已考虑的任何替代方案**
清晰而简洁地描述您已考虑的任何替代解决方案或功能。

**其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by ijry** [comment]
可以看提交记录，uni-app-x支持正在开发中。

**Comment by veako** [comment]
> 可以看提交记录，uni-app-x支持正在开发中。

我的问题。上午引入后一直报错，已经解决了。
