### ISSUE TITLE
官网这个地方错误改一改

### ISSUE THREAD

**Issue by LixHu** [ijry/uview-plus#503]
**问题描述**
清晰地描述该错误是什么。
![image](https://github.com/user-attachments/assets/f4172e37-63a2-4d8b-8d65-fb4c50acb227)

**复现步骤**
复现该行为的步骤：
1. 前往'...'
2. 点击'....'
3. 滚动到'....'
4. 查看错误

**预期行为**
清晰地描述你期望发生什么。

**截图**
如果适用，请添加截图以帮助解释你的问题。

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.8]
- 开发者工具版本：[例如 微信开发者工具1.0.1]

**平台（请填写以下信息）**：
- 平台：[例如 微信小程序iOS]

**智能手机（请填写以下信息）**：
- 设备：[例如 iPhone6]
- 操作系统：[例如 iOS8.1]
**其他上下文**
在此处添加有关问题的任何其他上下文。

**Comment by ijry** [comment]
fixed
