### ISSUE TITLE
up-parse 富文本编辑器事件imgTap和linkTap不触发

### ISSUE THREAD

**Issue by StudyRaise** [ijry/uview-plus#504]
**问题描述**
微信小程序，up-parse 富文本编辑器，事件imgTap和linkTap必须小写才能触发，与文档描述不符。

**截图**
![image](https://github.com/user-attachments/assets/02ac7329-bec6-46e1-93cc-a86deb7c72ca)

**版本（请填写以下信息）**：
- HBuilderX：3.5.3
- uview-plus：1.0.4
- 开发者工具版本： 微信开发者工具1.0.5

**平台（请填写以下信息）**：
- 平台：微信小程序

**Comment by ijry** [comment]
uview-plus不存在1.0.4版本
