### ISSUE TITLE
u-tabs 文字字号设置大一点 下面横线对不齐

### ISSUE THREAD

**Issue by scripted-C20** [ijry/uview-plus#512]
uview-plus 版本号 3.2.24
微信小程序

u-tabs 文字字号设置大一点 下面横线对不齐
![image](https://github.com/user-attachments/assets/88c61291-8522-4275-92ab-fdc6596e5e80)
![image](https://github.com/user-attachments/assets/4db82c56-63ad-4426-9e9d-6b96439e74af)

**Comment by ijry** [comment]
同步设置line样式

**Comment by scripted-C20** [comment]
> 我也出现这个问题，你解决没

没有 我是换了ui  你可以根据开发者上面说的 选中元素或者找到元素类再试试 实在不行换组件找组件 自己写一个
