### ISSUE TITLE
Slider新增插槽功能

### ISSUE THREAD

**Issue by iwenking** [ijry/uview-plus#527]
我希望在Slider 这个组件里面新增一个插槽的功能，
因为可能存在意见业务场景在滑动的时候希望吧数值显示在这个滑动的点上面
类似这种效果
![image](https://github.com/user-attachments/assets/ca2454dc-3ea2-44cd-95b3-06f3931cc2c9)

**Comment by ijry** [comment]
滑块是可以自定义的，然后数据本来你v-model绑定就有的。
