### ISSUE TITLE
使用up-icon标签封装组件时，icon元素始终居左。使用:deep()不能选中他并添加justify-content: center使其居中

### ISSUE THREAD

**Issue by Aihujiao** [ijry/uview-plus#528]
**问题描述**
uniapp vue3小程序环境下，封装一个卡片式组件时，需要使用up-icon中name为arrow-right(类似 > )的图标作为跳链标识。此时的图标一直处于flex布局的最左侧。即使使用:deep()尝试选中.u-icon(.u-right)的元素也无法使其居中，因为:deep()并不能选中它；

**复现步骤**

**预期行为**
我希望能让icon的内容能够居中而不是一直居左，或者让:deep()这样的选择方式能够选中需要加样式的元素。

**截图**
![image](https://github.com/user-attachments/assets/1b99ddf2-0c79-48ea-b026-17f1d02cf9d0)

![image](https://github.com/user-attachments/assets/1dc89df7-c030-4d7a-9606-d0104f0e8e4a)

- IDEA 2024.01
- uview-plus：3.3.34
- 开发者工具版本：1.06.2409131
- 平台：微信小程序Android

**Comment by ijry** [comment]
微信中用deep有许多条件，建议阅读群置顶文章。

**Comment by ijry** [comment]
https://jiangruyi.com/post/75.html
