### ISSUE TITLE
微信小程序中 u-tag 组件自动占满宽度， 标签变成了块级元素 换行

### ISSUE THREAD

**Issue by yy18570728781** [ijry/uview-plus#533]
**问题描述**
微信小程序中 u-tag 组件自动占满宽度， 标签变成了块级元素 换行
![8a2f5302a481f2311e2eb94aa342ca1](https://github.com/user-attachments/assets/ce6de163-ce4c-4e8a-a761-5e50ee3332c9)

**复现步骤**

**预期行为**
清晰地描述你期望发生什么。

**截图**
![8a2f5302a481f2311e2eb94aa342ca1](https://github.com/user-attachments/assets/3fb96b15-09a2-43e7-b2ca-0b4596c58c35)

**版本（请填写以下信息）**：
- HBuilderX：[4.23]
    "uview-plus": "^3.3.32",
- 开发者工具版本：[微信开发者工具1.0.6]

**平台（请填写以下信息）**：
微信小程序

**Comment by ijry** [comment]
给父元素一个flex布局

**Comment by ijry** [comment]
为了保持nvue的兼容性，所有元素默认都是flex垂直布局，所以会占满整行，给父元素一个flex-row布局即可。

**Comment by nreg** [comment]
![Snipaste_2024-12-26_15-03-10](https://github.com/user-attachments/assets/430791ba-5531-49e3-a095-6fa09500aaf2)
不光微信小程序，h5开发也是一样的（图中下方那个黄色标签）

**Comment by nreg** [comment]
![Snipaste_2024-12-26_15-03-10](https://github.com/user-attachments/assets/16c209c9-77c4-4e55-86b6-fe2305bd961c)
不光微信小程序，h5开发也是一样的
