### ISSUE TITLE
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

### ISSUE THREAD

**Issue by H0nGzA1** [ijry/uview-plus#534]
**问题描述**
uniapp cli 运行打包报错sass问题

![image](https://github.com/user-attachments/assets/f456837c-d1d8-4e4d-aa91-228fa53b9a0a)

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[3.3.36]

**平台（请填写以下信息）**：
- 平台：[h5 app-plus]

**Comment by ijry** [comment]
看了下新的@use几乎无法平滑升级，太激进了，这么普遍的底层API说废弃就废弃。建议固定saas版本。
"sass": "^1.63.2",
"sass-loader": "^10.4.1",
