### ISSUE TITLE
在uniapp 中用nvue,IOS 端每个组件都会报错，Android没有问题

### ISSUE THREAD

**Issue by icourseware** [ijry/uview-plus#535]
**问题描述**
 在uniapp 中用nvue,IOS 端每个组件都会报错，组件不显示，Android没有问题。
 [Vue warn]: Unhandled error during execution of created hook

![image](https://github.com/user-attachments/assets/77d443bf-0bef-4ec1-bed6-82524ba5c339)

 

**预期行为**
 希望能看下iOS端nvue页面里组件的调用。

**版本（请填写以下信息）**：
- HBuilderX：4.29
- uview-plus：3.3.8

**平台（请填写以下信息）**：
- 平台： app android,ios

**智能手机（请填写以下信息）**：
- 设备：[例如 iPhone11]
- 操作系统：[例如 iOS16]

**Comment by icourseware** [comment]
真机调试 iOS端会报这个错，几乎每个调用了uview-plus组件的页面都会报这个错误，包含了组件的页面白屏或者组件不显示。

**Comment by ijry** [comment]
之前有人反馈过，让下载官方项目代码打包是没问题的。

**Comment by icourseware** [comment]
> 之前有人反馈过，让下载官方项目代码打包是没问题的。

您说的下载官方的项目代码打包，官方指的是hbuilderX 插件引入，还是用npm install
