### ISSUE TITLE
uview-plus@3.3.35中up-input组件编译到微信小程序的输入框字体颜色问题

### ISSUE THREAD

**Issue by Liu-code3** [ijry/uview-plus#547]
**问题描述**
uview-plus@3.3.35中up-input组件编译到微信小程序的输入框字体颜色问题

**复现步骤**
复现该行为的步骤：
- 1.我在使用up-input组件，根据文档填写了输入框字体颜色为白色
- 2.使用hubuilderx 编译到微信小程序和app-plus中
- 3.微信小程序输入框显示的还是up-input默认的输入框字体颜色，h5与app-plus则正常

**预期行为**
- 在根据文档写了字体颜色的属性后，期望up-input组件编译到微信小程序中的输入框字体颜色为白色

**截图**
- 1.代码截图, 根据uview-plus的up-input文档设置了输入框字体颜色
 
   
   ![image](https://github.com/user-attachments/assets/3be67747-e97d-4a2c-a322-1e5acafc2846)

- 2.使用hbuilderX编译到微信小程序的界面视图
  
   ![image](https://github.com/user-attachments/assets/905199e7-f01c-4d55-ab15-072daef31df3)

- 3.使用hbuilderX编译到微信小程序的css代码视图，如下图所示, up-input使用的是默认的字体颜色
   
   ![image](https://github.com/user-attachments/assets/b61efe48-4a55-4b4d-9576-7f9da5296b59)

   ![image](https://github.com/user-attachments/assets/315de9b3-326b-46ac-9017-c2a49bce8323)

**版本**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.35]
- 开发者工具版本：[例如 微信开发者工具1.06.2407120]

**平台**：
- 平台：[微信小程序]

**智能手机（请填写以下信息）**：
- 设备：[微信小程序自带机型调试]

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/c7325e17-1443-4316-8289-220e376f91ef)
试了下颜色生效的，请检查本地是否有别的样式覆盖。
