### ISSUE TITLE
up-button组件 click事件使用stop修饰符无法阻止事件传播

### ISSUE THREAD

**Issue by gnoixeijil** [ijry/uview-plus#548]
**问题描述**
up-button组件 click事件使用stop修饰符无法阻止事件传播，还是会跳转页面，并且无法执行方法

**复现步骤**
复现该行为的步骤：
up-button组件 click事件使用stop修饰符无法阻止事件传播，还是会跳转页面，并且无法执行方法

**预期行为**
期望和button组件使用stop事件修饰符一致或者有其他方法来替代

**版本（请填写以下信息）**：
- HBuilderX：4.29
- uview-plus：3.3.37

**平台（请填写以下信息）**：
- 平台：h5

**Comment by qiuzixu** [comment]
我也遇到了 微信小程序正常 支付宝不正常

**Comment by ijry** [comment]
一增加stop参数配置是否阻止冒泡
