### ISSUE TITLE
H5 setConfig unit 无效 

### ISSUE THREAD

**Issue by mygitstyle** [ijry/uview-plus#549]
**问题描述**
使用npm下了最新版本 H5下样式错乱 设置setConfig({ config: { unit: 'rpx' } }) 也不行 单位还是px

**复现步骤**
复现该行为的步骤：
输入框头像都超大

**预期行为**

**截图**
![image](https://github.com/user-attachments/assets/76786f58-6a78-4391-b2a2-5085397f869c)
![image](https://github.com/user-attachments/assets/44b3cac6-3325-4a86-812e-528e2b08705d)

**版本（请填写以下信息）**：
- vscode：
  版本: 1.95.1 (user setup)
  日期: 2024-10-31T05:14:54.222Z
  Electron: 32.2.1
  ElectronBuildId: 10427718
  Chromium: 128.0.6613.186
  Node.js: 20.18.0
  V8: 12.8.374.38-electron.0
  OS: Windows_NT x64 10.0.22635
- uview-plus：3.3.39
- Chromium 118.0.5993.159

**平台（请填写以下信息）**：
- 平台：H5

**智能手机（请填写以下信息）**：
- 设备：[例如 iPhone6]
- 操作系统：[例如 iOS8.1]
**其他上下文**

**Comment by ijry** [comment]
别用模拟器，另外由于2.0历史原因，目前对rpx支持有限。

**Comment by mygitstyle** [comment]
> 别用模拟器，另外由于2.0历史原因，目前对rpx支持有限。
用的浏览器 直接用手机打开 也是一样的 但是单位为什么没有转换？

**Comment by ijry** [comment]
这个配置主要是给props传递参数的尺寸用的，无法对内置组建生效的原因是，代价太大了，演示写在style里面单位就是固定的无法更具配置来决定不同单位，而如果将所有样式全部写进js里，那样又回大大降低性能。
