### ISSUE TITLE
route跳转类型type设置无效

### ISSUE THREAD

**Issue by dadadaqin** [ijry/uview-plus#55]
问题（在uview2.0中存在的问题）：
在路由跳转时使用 type设置类型,无效
` uni.$u.route({
          type:'redirect',
          url: "*****",
        });`

原因：
route文件中的函数route中，使用默认配置覆盖了当前入参配置
` mergeConfig = uni.$u.deepMerge(options, this.config)`

解决：
调换覆盖逻辑，使用入参覆盖默认配置
` mergeConfig = uni.$u.deepMerge( this.config,options)`

**Comment by ijry** [comment]
已修复
