### ISSUE TITLE
up-button 组件 没有使用 setConfig 设置的unit rpx 单位

### ISSUE THREAD

**Issue by dengciping0716** [ijry/uview-plus#551]
**问题描述**
up-button 组件 没有使用 setConfig 设置的unit rpx 单位，

**预期行为**
 setConfig 设置的unit rpx 单位之后up-button 显示rpx大小
 
**版本（请填写以下信息）**：
- HBuilderX：4.29
- uview-plus：3.3.37

**平台（请填写以下信息）**：
- 平台：app,h5

**Comment by ijry** [comment]
由于历史原因rpx现阶段主要是给props传值使用，内置组件在CSS中无法通过JS控制单位。
