### ISSUE TITLE
codeInput 组件v-model 双向绑定怎么突然没用了 ，之前还是好好的 。突然生产的不起作用了

### ISSUE THREAD

**Issue by qiuzixu** [ijry/uview-plus#559]
code-input组件双向绑定怎么突然没用了 
![1731813107063](https://github.com/user-attachments/assets/cea2c0c0-b47c-4700-97fe-6f5ffed69624)
而且我之前看组件库写的是u-code-input 现在变成了 up-code-input 。且我换成p-code-input双向绑定还是没用 是不是最近有更新

**Comment by ijry** [comment]
code-input没更新，你再检查下呢，前缀不影响双向绑定。

**Comment by qiuzixu** [comment]
我现在就是把
![image](https://github.com/user-attachments/assets/188d1e9f-7e5d-4209-b6d5-52dbcb576aa1)
组件库的代码拉下来，v-mode 双向绑定还是不生效 ，必须用change事件

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/4f40cbb4-537f-4eaa-87c1-b960b8529653)
有点奇怪，这俩事件是一前一后发出的。

**Comment by qiuzixu** [comment]
对我也看了源码。但是现在就是v-model 不起作用。之前写好的代码，在生产突然就不行了，领导发现了，然后现在本地运行确实看也不行了。
![image](https://github.com/user-attachments/assets/06e4321a-2d55-4c79-89b4-4126d7574e67)

**Comment by qiuzixu** [comment]
加了change 事件 
![image](https://github.com/user-attachments/assets/aadd676f-b286-4033-a7a3-9d254da4707d)
就正常了

**Comment by qiuzixu** [comment]
![1731816626663](https://github.com/user-attachments/assets/0567a034-1f27-4946-982e-01f9a74c1ee2)
好像破案了，我又两份代码 同一个版本好拉下来的代码怎么源码不一样了

**Comment by ijry** [comment]
左边的看着是很老很老的版本还没兼容vue3

**Comment by qiuzixu** [comment]
![image](https://github.com/user-attachments/assets/bd1e070f-cd34-4d66-b7f3-e514b5cfffb1)
但是这个版本号我还是7个月前更新的 我现在重新install 一下就正常了 不知道之前为啥拉下来的是老代码，有点神奇

**Comment by ijry** [comment]
可能是你npm拉的本地cache没从网络更新

**Comment by qiuzixu** [comment]
主要这个项目我一开始就是用vue3写的 好奇怪 我也第一次遇到这种问题

**Comment by ijry** [comment]
你切换用过npm pnpm等吗

**Comment by qiuzixu** [comment]
之前是npm ，但刚刚重新install 后恢复正常的那次是用的pnpm install操作

**Comment by ijry** [comment]
应该就是cache导致的

**Comment by qiuzixu** [comment]
嗯嗯 我在研究一下。还cache 到vue2 版本去了
