### ISSUE TITLE
uniapp:3.0.0-alpha-3061020221121002版本，引入组件支付宝小程序报错了，无法引入组件

### ISSUE THREAD

**Issue by Dizzy-zz** [ijry/uview-plus#56]
版本更新之前是正常运行的，uniapp更新了最新的版本后就开始报错引入不了组件了
![Uploading image.png…]()

**Comment by Dizzy-zz** [comment]
![image](https://user-images.githubusercontent.com/26196307/203683466-482ae09b-2bd0-42ae-ab99-7b82ff56ba70.png)

**Comment by ijry** [comment]
look at this https://ask.dcloud.net.cn/question/140695
