### ISSUE TITLE
setConfig能设置成功，但是并没有作用到组件当中？

### ISSUE THREAD

**Issue by Maxbsy** [ijry/uview-plus#562]
**问题描述**
使用了setConfig，但是在组件当中，并没有生效，那么这个setConfig设置我是作何用呢？

**复现步骤**
复现该行为的步骤：
1. 前往'...'
2. 点击'....'
3. 滚动到'....'
4. 查看错误

**预期行为**
清晰地描述你期望发生什么。

**截图**
![image](https://github.com/user-attachments/assets/1404206d-8cb3-4007-8277-ae8c955614cd)
![image](https://github.com/user-attachments/assets/cbc3bd19-9af8-4100-94d4-edd6906f492d)
![image](https://github.com/user-attachments/assets/986fd473-705b-4ac8-890f-af3eafbffc7e)
![image](https://github.com/user-attachments/assets/642072cc-c1c9-4440-84e6-b6bbbf447fe4)

**版本（请填写以下信息）**：
- HBuilderX：4.29
- uview-plus：3.3.43

**平台（请填写以下信息）**：
- 平台：H5

**智能手机（请填写以下信息）**：
- 设备：Chrome
- 操作系统：MAC
**其他上下文**
在此处添加有关问题的任何其他上下文。

**Comment by ijry** [comment]
排查中

**Comment by ijry** [comment]
这个并非配置不生效，而是rpx配置目前技术上无法做到修改Vue单文件组件中的Css/Sass中写死的px单位，这个配置主要用于prop传参时的单位修改，如果需要全局组件样式变为rpx，可以尝试使用postcss等第三方插件转换。
