### ISSUE TITLE
关于开发文档广告，无合适广告播放问题

### ISSUE THREAD

**Issue by QixuanH** [ijry/uview-plus#563]
**问题描述**
您好，我十分赞成开源产品通过广告来维持产品的推进。

我目前在国外，我在扫码进入小程序点击播放广告后，会显示无合适的广告，从而无法通过其他的方式查看开发文档。

**复现步骤**
复现该行为的步骤：
https://uiadmin.net/uview-plus/components/intro.html
挂梯子到外网ip，微信扫码，点击播放广告

**预期行为**
如果有其他的方式来看广告或者说直接跳过。

**截图**
![WechatIMG220](https://github.com/user-attachments/assets/19f69178-12a9-4586-a3a5-051196b4b676)

**Comment by ijry** [comment]
如遇到国外等特殊清空的可以加我598821125

**Comment by mynameiscuining** [comment]
使用vant4

**Comment by HS3** [comment]
为什么一个官网的组件https://uiadmin.net/uview-plus/components/intro.html广告这么多，也没有预览，必须要扫码小程序才能预览组件UI。

**Comment by bigshans** [comment]
强制看广告就近乎流氓网站了。

**Comment by lwliang** [comment]
只能说，越做越流氓，消耗一些老玩家的心，新玩家也不会接入
