### ISSUE TITLE
up-radio组件以 kebab-case 命名格式的部分属性不生效

### ISSUE THREAD

**Issue by wangpf1129** [ijry/uview-plus#570]
**问题描述**
在 uni-app 项目中，up-radio-group 组件的 `active-color` 属性（kebab-case）不生效，只有使用 `activeColor`（camelCase）才能正常工作。根据 Vue 的命名约定，这两种写法按道理应该都是有效的。

**复现步骤**
使用 kebab-case 命名格式不生效
```vue
<up-radio-group
v-model="gender"
placement="row"
active-color="#573E2B"
>
<!-- radio items -->
</up-radio-group>
```

使用 camelCase 设置属性（正常工作）：
```vue
<up-radio-group
v-model="gender"
placement="row"
activeColor="#573E2B"
>
<!-- radio items -->
</up-radio-group>
```

**预期行为**
按照 Vue 的命名约定：
- camelCase 形式 (`activeColor`) 生效
- kebab-case 形式 (`active-color`) 也应该生效
- 这两种写法应该是等价的

**版本（请填写以下信息）**：
- uview-plus：3.3.43
-  微信开发者工具 Stable 1.06.2409140

**Comment by ijry** [comment]
建议与文档保持一致，因为uni-app要考虑多端适配等特殊情况，存在不能与web完全一致的情况。
