### ISSUE TITLE
希望在未设置绑定值时，DatetimePicker组件能手动设置默认值

### ISSUE THREAD

**Issue by wlijiao3015** [ijry/uview-plus#573]
希望在未设置value时，打开日期选择器，选择器中能默认选中当日
![image](https://github.com/user-attachments/assets/6647209a-7db7-434c-9a49-3599d3a45075)

`<template>
	<view>
                <up-datetime-picker
                    hasInput
                    :show="show"
                    v-model="value"
                    mode="datetime"
                ></up-datetime-picker>
		<up-button @click="show = true">打开</up-button>
	</view>
</template>

<script setup>
import { ref } from 'vue';

const show = ref(false);
const value = ref(“”);
</script>`

**Comment by ijry** [comment]
这会破坏历史兼容性，很多场景默认其实不选就是为空的，建议手动赋值初始化。

**Comment by wlijiao3015** [comment]
未选择日期时打开日期控件，要定位到当天需要滑动一大段距离，会比较繁琐，请问有没有解决办法
![image](https://github.com/user-attachments/assets/62c85e49-bb6f-41b0-a452-f3b024da0dfc)

**Comment by wlijiao3015** [comment]
未选择日期时打开日期控件，要定位到当天需要滑动一大段距离，会比较繁琐，请问有没有解决办法

![image](https://github.com/user-attachments/assets/d43f4eb5-10c6-4fe6-b5c1-fb4be027d32b)
