### ISSUE TITLE
input,textarea 设置maxlength 无效

### ISSUE THREAD

**Issue by PLONGJ** [ijry/uview-plus#574]
问题：
input textarea组件设置了maxlength=200 页面上超过200字确实不会再显示了，但是提交给接口后，超过的字一样会被提交
使用例子：
 <up-textarea
                v-model="formData.purpose"
                border="none"
                fontSize="28rpx"
                maxlength="200"/>

**Comment by ijry** [comment]
这是uni-app内置属性的默认特性。
