### ISSUE TITLE
Invalid prop: custom validator check failed for prop "inputmode".

### ISSUE THREAD

**Issue by Hs-Shrek** [ijry/uview-plus#575]
**问题描述**
uview-plus3.0 HubilderX Dcloud 安装
更新日期：2024-11-28版本：3.3.47
使用`<up-input>`时出现了以下警告。
![image](https://github.com/user-attachments/assets/73648799-aafd-4aa6-b78b-100ad89d6e80)

在2天前 用npm安装的uview-plus还没有该告警，不知道是不是今天更新出现的。
请问如何解决或者停止显示该告警

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.47]
- 开发者工具版本：[例如 微信开发者工具1.0.1]

**Comment by ijry** [comment]
明天更新
