### ISSUE TITLE
在弹出的popup中再弹出picker时，picker会被popup盖住，希望给Picker增加z-index属性

### ISSUE THREAD

**Issue by humlzy** [ijry/uview-plus#576]
**您的功能请求是否与某个问题相关？请描述。**
在弹出的popup中再弹出picker时，picker会被popup盖住

**描述您想要的解决方案**
给picker添加z-index属性，通过设置z-index的值使picker能够显示在pupup之上。

**描述您已考虑的任何替代方案**
修改picker组件源码u-picker.vue第14行增加z-index="10076"。

**其他上下文**
无。

**Comment by ijry** [comment]
已增加对应prop下版本发布
