### ISSUE TITLE
image组件在微信小程序下高宽样式设置无效

### ISSUE THREAD

**Issue by eAliwei** [ijry/uview-plus#577]
**问题描述**
image组件在微信小程序下高宽样式设置无效。
```js
<up-image src="/static/avatar.jpg" shape="circle" width="60" height="60" :show-loading="true"></up-image>
```
已提交PR
https://github.com/ijry/uview-plus/pull/572

**截图**
微信小程序
![cdded3b0d358af3f4293077d7ffd95a0](https://github.com/user-attachments/assets/4ea0807e-6a2e-4ce0-aa2e-ce2e939ce0a3)

H5
![image](https://github.com/user-attachments/assets/7940570c-8b88-48d9-9d5b-5bf4314bf416)

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.8]
- 开发者工具版本：[例如 微信开发者工具1.0.1]

**平台（请填写以下信息）**：
- 平台：[微信小程序iOS]

**Comment by ijry** [comment]
配置下mergeVirtualHostAttributes，文档安装章节已增加说明。
