### ISSUE TITLE
up-input, 给文本框字体设置了绿色，但是未生效，依然是黑色

### ISSUE THREAD

**Issue by humlzy** [ijry/uview-plus#578]
**问题描述**
给文本框字体设置了绿色，但是未生效。
<u-cell-group :border="false">
	<u-cell title="每月租金" 
		:border="false" 
		:isLink="true">
		<template #value>
			<up-input
				type="digit"
				placeholder="请输入"
				**color="#07CE52"**
				border="none"
				fontSize="20px"
				inputAlign="right"
				v-model="rent"
			  ></up-input>
		</template>
		<template #right-icon>
			<text style="color:#07CE52">元</text>
		</template>
	</u-cell>
</u-cell-group>

**版本（请填写以下信息）**：
- HBuilderX：[ 4.29 ]
- uview-plus：[ 3.3.48 ]
- 运行到chrome浏览器，尺寸:iPhone12Pro

**Comment by humlzy** [comment]
<u-cell-group :border="false">
	<u-cell title="每月租金" 
		:border="false" 
		:isLink="true">
		<template #value>
			<up-input
				type="digit"
				placeholder="请输入"
				color="#07CE52"
				border="none"
				fontSize="20px"
				inputAlign="right"
				v-model="rent"
			  ></up-input>
		</template>
		<template #right-icon>
			<text style="color:#07CE52">元</text>
		</template>
	</u-cell>
</u-cell-group>

**Comment by humlzy** [comment]
![微信截图_20241129152535](https://github.com/user-attachments/assets/3603aa27-dc4c-4075-9349-5550b03bfbb8)

**Comment by ijry** [comment]
测试了H5与小程序均可以
![image](https://github.com/user-attachments/assets/de1b571e-d918-4fc6-8904-96a01b83b6d7)
请检查本地是否存在别的样式覆盖，另外添加"mergeVirtualHostAttributes" : true试试。
