### ISSUE TITLE
使用cli模式的uniapp无法显示组件

### ISSUE THREAD

**Issue by censujiang** [ijry/uview-plus#58]
```console
[Vue warn]: Failed to resolve component: u-icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

**Comment by lihe6666** [comment]
引入的路径找不到吧，把pages.json -> easycom 修改一下

**Comment by censujiang** [comment]
修改过的，就是用官网的方式

**Comment by ijry** [comment]
cli方式安卓、H5、微信小程序都确认可以，请自己参考文档配置，并升级相关开发工具至最新版本：
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/3102798/212620581-73136501-207e-4906-9ab6-9cfb2cb9b6c5.png">
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/3102798/212620657-3ca65bb6-8609-439a-a324-fcb35d2f30f7.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/3102798/212620816-847fb53e-bec8-41b7-931e-0c33139b2f20.png">
