### ISSUE TITLE
uiview-plus占小程序主包超2mb，怎么办

### ISSUE THREAD

**Issue by JAYCHOUMINSTER** [ijry/uview-plus#582]
![image](https://github.com/user-attachments/assets/729c6ef9-8341-40b0-9a59-d0b7a576e759)
超过2mb不能打包，致命问题，求解！

**Comment by ijry** [comment]
你的配置方式不争取，你看每个组件都100K，明显是重复导入文件了。

**Comment by hduhdc** [comment]
> 你的配置方式不正确，你看每个组件都100K，明显是重复导入文件了。

我也是做了分包还是最终打包到主包去了
![image](https://github.com/user-attachments/assets/ddeb2a2f-3e49-46cd-83bb-7e2933cf9020)

node_modules 全是uview-plus 
![image](https://github.com/user-attachments/assets/039f3201-84c6-45ea-b30e-18154a74e408)

**Comment by hduhdc** [comment]
![image](https://github.com/user-attachments/assets/fed2ecd6-7970-4839-ab77-2b5f0c17d9d2)

**Comment by ijry** [comment]
不是分包的事，是你配置有问题，导致每个组件都导入了同一个文件，等于有几十个重复文件。

**Comment by hduhdc** [comment]
> 不是分包的事，是你配置有问题，导致每个组件都导入了同一个文件，等于有几十个重复文件。

  "easycom": {
    "autoscan": true,
    "custom": {
      "^u-button": "uview-plus/components/u-button/u-button.vue",
       "^u-input":"uview-plus/components/u-input/u-input.vue",
       "^up-input":"uview-plus/components/u-input/u-input.vue",
       "^u-icon" : "uview-plus/components/u-icon/u-icon.vue",
       "^u-picker":"uview-plus/components/u-picker/u-picker.vue",
       "^u-popup":"uview-plus/components/u-popup/u-popup.vue",
       "^u-overlay":"uview-plus/components/u-overlay/u-overlay.vue",
       "^u-transition": "uview-plus/components/u-transition/u-transition.vue",
       "^u-toolbar":"uview-plus/components/u-toolbar/u-toolbar.vue",
       "^u-line":"uview-plus/components/u-line/u-line.vue"
 
    }
  },我是这个配置

**Comment by ijry** [comment]
uni.scc看看

**Comment by hduhdc** [comment]
> 不是分包的事，是你配置有问题，导致每个组件都导入了同一个文件，等于有几十个重复文件。

![image](https://github.com/user-attachments/assets/afe7e0b9-3876-436a-8338-6ab269229f04)
主包单独uview 就1.51M

**Comment by hduhdc** [comment]
> uni.scss看看

/**
 * 这里是uni-app内置的常用样式变量
 *
 * uni-app 官方扩展插件及插件市场（https://ext.dcloud.net.cn）上很多三方插件均使用了这些样式变量
 * 如果你是插件开发者，建议你使用scss预处理，并在插件代码中直接使用这些变量（无需 import 这个文件），方便用户通过搭积木的方式开发整体风格一致的App
 *
 */

/**
 * 如果你是App开发者（插件使用者），你可以通过修改这些变量来定制自己的插件主题，实现自定义主题功能
 *
 * 如果你的项目同样使用了scss预处理，你也可以直接在你的 scss 代码中使用如下变量，同时无需 import 这个文件
 */

/* 颜色变量 */

/* 行为相关颜色 */
$uni-color-primary: #007aff;
$uni-color-success: #4cd964;
$uni-color-warning: #f0ad4e;
$uni-color-error: #dd524d;

/* 文字基本颜色 */
$uni-text-color: #333; // 基本色
$uni-text-color-inverse: #fff; // 反色
$uni-text-color-grey: #999; // 辅助灰色，如加载更多的提示信息
$uni-text-color-placeholder: #808080;
$uni-text-color-disable: #c0c0c0;

/* 背景颜色 */
$uni-bg-color: #fff;
$uni-bg-color-grey: #f8f8f8;
$uni-bg-color-hover: #f1f1f1; // 点击状态颜色
$uni-bg-color-mask: rgba(0, 0, 0, 0.4); // 遮罩颜色

/* 边框颜色 */
$uni-border-color: #c8c7cc;

/* 尺寸变量 */

/* 文字尺寸 */
$uni-font-size-sm: 12px;
$uni-font-size-base: 14px;
$uni-font-size-lg: 16;

/* 图片尺寸 */
$uni-img-size-sm: 20px;
$uni-img-size-base: 26px;
$uni-img-size-lg: 40px;

/* Border Radius */
$uni-border-radius-sm: 2px;
$uni-border-radius-base: 3px;
$uni-border-radius-lg: 6px;
$uni-border-radius-circle: 50%;

/* 水平间距 */
$uni-spacing-row-sm: 5px;
$uni-spacing-row-base: 10px;
$uni-spacing-row-lg: 15px;

/* 垂直间距 */
$uni-spacing-col-sm: 4px;
$uni-spacing-col-base: 8px;
$uni-spacing-col-lg: 12px;

/* 透明度 */
$uni-opacity-disabled: 0.3; // 组件禁用态的透明度

/* 文章场景相关 */
$uni-color-title: #2c405a; // 文章标题颜色
$uni-font-size-title: 20px;
$uni-color-subtitle: #555; // 二级标题颜色
$uni-font-size-subtitle: 18px;
$uni-color-paragraph: #3f536e; // 文章段落颜色
$uni-font-size-paragraph: 15px;

@import "uview-plus/theme.scss";
@import "uview-plus/index.scss";

**Comment by ijry** [comment]
不要在uni.scss中引入任何除了变量以外的文件，因为这里引入会导致每个页面复制一份。

**Comment by hduhdc** [comment]
> 严格按照文档配置，不要在uni.scss中引入任何除了变量以外的文件，因为这里引入会导致每个页面复制一份。

好了，感谢感谢

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/de1fbc42-d2e1-4237-9b6a-43b1bd2aec66)
加了强调效果了

**Comment by aimerthyr** [comment]
> ![image](https://private-user-images.githubusercontent.com/3102798/392684690-de1fbc42-d2e1-4237-9b6a-43b1bd2aec66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODAwODQsIm5iZiI6MTczMzU3OTc4NCwicGF0aCI6Ii8zMTAyNzk4LzM5MjY4NDY5MC1kZTFmYmM0Mi1kMmUxLTQyMzctOWI2YS00M2IxYmQyYWVjNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMTM1NjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU4Mzk1NDIxOGYxMDUxOTZhMzJkM2IwNGY3ODhiMzM4YjM0ZjBkODY4NTA4NDY5MjdjYjI2ZGRkNmFkY2M3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HFqAGsVm8isLdzeAo5E48lDIaDnWcDgPitI_wByPAss) 加了强调效果了

大佬，请问我只用到了一些组件，但是还是全部引入进来了。
<img width="755" alt="image" src="https://github.com/user-attachments/assets/53c00277-02d8-4636-b17f-193bf407bd53">
这种是正常表现吗，我的期望是只引入我使用到的组件

**Comment by ijry** [comment]
跟楼上一样问题吧

**Comment by ijry** [comment]
看看uview-plus/index.js

**Comment by aimerthyr** [comment]
```js
// 看到此报错，是因为没有配置vite.config.js的【transpileDependencies】
// const pleaseSetTranspileDependencies = {}, babelTest = pleaseSetTranspileDependencies?.test

// 引入全局mixin
import { mixin } from './libs/mixin/mixin.js'
// 小程序特有的mixin
import { mpMixin } from './libs/mixin/mpMixin.js'
// 全局挂载引入http相关请求拦截插件
import Request from './libs/luch-request'

// 路由封装
import route from './libs/util/route.js'
// 颜色渐变相关,colorGradient-颜色渐变,hexToRgb-十六进制颜色转rgb颜色,rgbToHex-rgb转十六进制
import colorGradient from './libs/function/colorGradient.js'

// 规则检验
import test from './libs/function/test.js'
// 防抖方法
import debounce from './libs/function/debounce.js'
// 节流方法
import throttle from './libs/function/throttle.js'
// 公共文件写入的方法
import index from './libs/function/index.js'

// 配置信息
import config from './libs/config/config.js'
// props配置信息
import props from './libs/config/props.js'
// 各个需要fixed的地方的z-index配置文件
import zIndex from './libs/config/zIndex.js'
// 关于颜色的配置，特殊场景使用
import color from './libs/config/color.js'
// 平台
import platform from './libs/function/platform'

// 导出
const http = new Request()
let themeType = ['primary', 'success', 'error', 'warning', 'info'];
export { route, http, debounce, throttle, platform, themeType, mixin, mpMixin, props, color, test, zIndex }
export * from './libs/function/index.js'
export * from './libs/function/colorGradient.js'

/**
 * @description 修改uView内置属性值
 * @param {object} props 修改内置props属性
 * @param {object} config 修改内置config属性
 * @param {object} color 修改内置color属性
 * @param {object} zIndex 修改内置zIndex属性
 */
export function setConfig(configs) {
	index.shallowMerge(config, configs.config || {})
	index.shallowMerge(props, configs.props || {})
	index.shallowMerge(color, configs.color || {})
	index.shallowMerge(zIndex, configs.zIndex || {})
}
index.setConfig = setConfig

const $u = {
    route,
    date: index.timeFormat, // 另名date
    colorGradient: colorGradient.colorGradient,
    hexToRgb: colorGradient.hexToRgb,
    rgbToHex: colorGradient.rgbToHex,
    colorToRgba: colorGradient.colorToRgba,
    test,
    type: themeType,
    http,
    config, // uview-plus配置信息相关，比如版本号
    zIndex,
    debounce,
    throttle,
    mixin,
    mpMixin,
    props,
    ...index,
    color,
    platform
}

export const mount$u = function() {
    uni.$u = $u
}

// #ifdef H5
const importFn = import.meta.glob('./components/u-*/u-*.vue', { eager: true })
let components = [];

// 批量注册全局组件
for (const key in importFn) {
    let component = importFn[key].default;
    if (component.name && component.name.indexOf('u--') !== 0) {
        component.install = function (Vue) {
            Vue.component(name, component);
        };
        
        // 导入组件
        components.push(component);
    }
}
// #endif

function toCamelCase(str) {
    return str.replace(/-([a-z])/g, function(match, group1) {
      return group1.toUpperCase();
    }).replace(/^[a-z]/, function(match) {
      return match.toUpperCase();
    });
}

const install = (Vue) => {
    // #ifdef H5
    components.forEach(function(component) {
        const name = component.name.replace(/u-([a-zA-Z0-9-_]+)/g, 'up-$1');
        Vue.component(name, component); 
    });
    // #endif

    // 同时挂载到uni和Vue.prototype中
    // $u挂载到uni对象上
    uni.$u = $u

    // #ifndef APP-NVUE
    // 只有vue，挂载到Vue.prototype才有意义，因为nvue中全局Vue.prototype和Vue.mixin是无效的
    Vue.config.globalProperties.$u = $u
    Vue.mixin(mixin)
    // #endif
}

export default {
    install
}

```
这是目录结构
<img width="835" alt="image" src="https://github.com/user-attachments/assets/485b391a-e829-4bc4-b8e9-22f7cb296a70">

**Comment by ijry** [comment]
看看微信的依赖分析，是不是文件虽然被uni-app编译过来但是实际存在上传会忽略没用到的。

**Comment by aimerthyr** [comment]
比方说这个u-code 我没有用到
<img width="997" alt="image" src="https://github.com/user-attachments/assets/f7964f75-dd71-479c-af3f-a52885e09a0f">
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/ea793025-5e7b-47cf-b779-fd9139ca29ec">

**Comment by aimerthyr** [comment]
> 看看微信的依赖分析，是不是文件虽然被uni-app编译过来但是实际存在上传会忽略没用到的。

看了源码，大概知道啥原因了，因为在 lib/config/props.js ，所有组件的props 都被解构到了这个js里
<img width="761" alt="image" src="https://github.com/user-attachments/assets/25ca386c-66f4-4220-89dd-c93c998b928f">
这就导致变成了全量加载，但是如果不解构到这里，我看你是为了实现全局覆盖props这个功能，又必须拿到所有的props，所以感觉有利有弊吧，我建议还是让开发者自己去单个处理props，把解构删了，这样可以减少不少打包体积，不知道作者大大想法如何

**Comment by maYunLaoXi** [comment]
这个问题还没有解决啊！！为什么把issue关了？
