### ISSUE TITLE
noticebar 竖向滚动时 由于文字较少 所以显得没有居中，请求增加一个居中参数，谢谢

### ISSUE THREAD

**Issue by humlzy** [ijry/uview-plus#583]
**您的功能请求是否与某个问题相关？请描述。**
noticebar 竖向滚动时 由于文字较少 所以显得没有居中，请求增加一个居中参数，谢谢
![微信图片_20241205140936](https://github.com/user-attachments/assets/a3eed9ef-6abe-49c8-8bee-627174c63132)

**描述您想要的解决方案**
如图，由于noticebar滚动的文字较少， 无法居中显示，影响美观，请求增加一个参数，用于竖向滚动时文字居中，谢谢。

**描述您已考虑的任何替代方案**
清晰而简洁地描述您已考虑的任何替代解决方案或功能。

**其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by ijry** [comment]
🆗

**Comment by humlzy** [comment]
谢谢

**Comment by ijry** [comment]
已增加justifyCenter参数@3.3.52
