### ISSUE TITLE
样式覆盖繁琐

### ISSUE THREAD

**Issue by ethanCode97** [ijry/uview-plus#584]
初次使用这个组件库，样式覆盖好繁琐呀，好多styles内联样式，需要一个一个覆盖掉。（后续加进来帮修改ui的，没有抽离组件，样式覆盖只好全局替换）而且一些选中也没有class类名。没有吐槽的意思哈，只想知道自己用的对不对。

**Comment by ijry** [comment]
内联样式是因为很多通过props传参数进来用的，不用去强制覆盖。

**Comment by ijry** [comment]
正常都有class的，如果特殊没有的可以提出来后续加上。

**Comment by hga97** [comment]
嗯嗯，我知道可以用props传递，但好家伙好多需要替换的，没抽离组件，发现抽离还不如全局替换。

**Comment by ethanCode97** [comment]
作者你好，我在app嵌套webview下，发现up-navbar的statusBarHeight为0，导致没有状态栏的高度，请问下，是用的方法不对，还是这个主要用在app端和小程序端的。

**Comment by ethanCode97** [comment]
> 作者你好，我在app的webview嵌套h5下，发现up-navbar的statusBarHeight为0，导致没有状态栏的高度，请问下，是用的方法不对，还是这个主要用在app端和小程序端的。

作者你好，我在app的webview嵌套h5下，发现up-navbar的statusBarHeight为0，导致没有状态栏的高度，请问下，是用的方法不对，还是这个主要用在app端和小程序端的。

**Comment by ijry** [comment]
![image](https://github.com/user-attachments/assets/661fd84a-d8a6-4600-b792-f1c4329da196)
因为H5似乎无法获取状态栏的高度，你试试替换下u-status-bar.vue的内容看有没有用？
`
<template>
	<view
	    :style="[style]"
	    class="u-status-bar"
		:class="[isH5 && 'u-safe-area-inset-top']"
	>
		<slot />
	</view>
</template>

<script>
	import { props } from './props';
	import { mpMixin } from '../../libs/mixin/mpMixin';
	import { mixin } from '../../libs/mixin/mixin';
	import { addUnit, addStyle, deepMerge, sys } from '../../libs/function/index';
	/**
	 * StatbusBar 状态栏占位
	 * @description 本组件主要用于状态填充，比如在自定导航栏的时候，它会自动适配一个恰当的状态栏高度。
	 * @tutorial https://uview-plus.jiangruyi.com/components/statusBar.html
	 * @property {String}			bgColor			背景色 (默认 'transparent' )
	 * @property {String | Object}	customStyle		自定义样式 
	 * @example <u-status-bar></u-status-bar>
	 */
	export default {
		name: 'u-status-bar',
		mixins: [mpMixin, mixin, props],
		data() {
			return {
				// #ifdef H5
				isH5: true
				// #endif
			}
		},
		computed: {
			style() {
				const style = {}
				// 状态栏高度，由于某些安卓和微信开发工具无法识别css的顶部状态栏变量，所以使用js获取的方式
				style.height = addUnit(sys().statusBarHeight, 'px')
				style.backgroundColor = this.bgColor
				return deepMerge(style, addStyle(this.customStyle))
			}
		},
	}
</script>

<style lang="scss" scoped>
	.u-status-bar {
		// nvue会默认100%，如果nvue下，显式写100%的话，会导致宽度不为100%而异常
		/* #ifndef APP-NVUE */
		width: 100%;
		/* #endif */
	}
</style>

`
