### ISSUE TITLE
u-popup 组件 非bottom 模式 不应该默认显示safeAreaInsetBottom。

### ISSUE THREAD

**Issue by dengciping0716** [ijry/uview-plus#585]
版本：3.3.43

**Comment by ijry** [comment]
传参数safeAreaInsetBottom="false"就好了哈，不然props默认值不好做。

**Comment by dengciping0716** [comment]
> 传参数safeAreaInsetBottom="false"就好了哈，不然props默认值不好做。

`<u-safe-bottom v-if="safeAreaInsetBottom && mode == 'bottom'"></u-safe-bottom>`
这样判断是否可以。
