### ISSUE TITLE
popup组件在定位为center时，点击内容区域也会触发close事件

### ISSUE THREAD

**Issue by eAliwei** [ijry/uview-plus#586]
**问题描述**
清晰地描述该错误是什么，请不要直接贴一张图或者一句话描述，需要提供尽可能多的信息才能便于问题定位，特别是连个版本号都没有的无从下手。

**复现步骤**
```html
  <up-popup :show="show" :zIndex="998" :closeOnClickOverlay="true" :round="20" mode="center"
    @close="handleClose" closeable>
    <view class="announcement-box">
.....
    </view>
  </up-popup>
```

**预期行为**
内容区域不触发close事件,点击遮罩区域触发close事件.

**截图**
![image](https://github.com/user-attachments/assets/fba0fd31-1f79-49d2-abf2-bc0af44ebbb5)

**版本（请填写以下信息）**：
- HBuilderX：[例如 4.24]
- uview-plus：[例如 3.3.8]
- 开发者工具版本：[例如 微信开发者工具1.0.1]

**平台（请填写以下信息）**：
- 平台：[例如 微信小程序iOS]

**智能手机（请填写以下信息）**：
- 设备：[例如 iPhone6]
- 操作系统：[例如 iOS8.1]
**其他上下文**
在此处添加有关问题的任何其他上下文。

**Comment by ijry** [comment]
3.3.53版本修复明早更新
