### ISSUE TITLE
feat: 希望up-qrcode组件新增是否开启预览的props

### ISSUE THREAD

**Issue by zhouxuhui12138** [ijry/uview-plus#587]
### 现状

up-qrcode组件点击二维码默认弹出uni.previewImage，用户无法自定义预览弹出框

### 期望效果

增加一个props参数 是否使用组件内部自带的预览功能

### 可能实现的方案

增加一个props参数 是否使用组件内部自带的预览功能

**Comment by ijry** [comment]
git已提交，明早发布。
