### ISSUE TITLE
mpMixin混入文件在微信小程序中没有起到作用

### ISSUE THREAD

**Issue by steavengong** [ijry/uview-plus#59]
vue 3
uni app ：3.0.0-alpha-3061020221121002
uview-plus  3.1.19

uview-plus_3.1.19_example项目

mpMixin混入文件在微信小程序中没有起到作用

![image](https://user-images.githubusercontent.com/10862092/204453526-157e4242-e560-48ca-a809-02f239921f76.png)

但是把
<img width="541" alt="image" src="https://user-images.githubusercontent.com/10862092/204453603-d5ce6edf-ead3-4eaa-a7d7-d37e2e7dbed4.png">
直接加在
<img width="924" alt="image" src="https://user-images.githubusercontent.com/10862092/204454302-03fd3b9e-6180-4cbd-8527-e6e7933d5134.png">
是生效的
![image](https://user-images.githubusercontent.com/10862092/204454409-257cf241-3a63-45c1-9099-a361ec1164d0.png)

**Comment by ijry** [comment]
建议提交PR

**Comment by ijry** [comment]
目前结论，uniapp官方编译器不兼容。
