### ISSUE TITLE
u-slider组件的change和changing事件没有参数

### ISSUE THREAD

**Issue by ideal-5** [ijry/uview-plus#591]
**问题描述**
u-slider 组件的 change 和 changing 事件没有参数，

**复现步骤**

 1. 使用u-slider组件
 2. 使用v-model绑定一个值
 3. 绑定 change 和 changing 事件，并在事件回调内打印参数
 4. 滑动滑块

**预期行为**
 change 和 changing 事件参数应为当前滑块绑定的值，但并没有接受到值

**截图**
文档中事件有参数:
![PixPin_2024-12-16_18-03-59](https://github.com/user-attachments/assets/ea8e7d3f-c952-4a05-a10d-5d9c22e3f31e)
源码中并未传递参数:
![PixPin_2024-12-16_18-07-23](https://github.com/user-attachments/assets/e3208a58-5141-4062-bdce-f1913e98df6a)

**版本（请填写以下信息）**：
- uview-plus：[3.3.39]
- 开发者工具版本：[微信开发者工具1.06.2409140]
- 微信开发者工具调试基础库：[3.7.1]

**平台**：
- 平台：[微信小程序]

**其他问题**
通过 v-model 绑定的值可以直接获取当前滑块的值，因此在我的项目场景中并不需要事件参数。然而，文档中提到事件存在参数，但实际上事件并未传递该参数。

**Comment by ijry** [comment]
好的下一版本修复
