### ISSUE TITLE
Tabs组件选中时，增加一个active的class

### ISSUE THREAD

**Issue by dyjx2004** [ijry/uview-plus#595]
**您的功能请求是否与某个问题相关？请描述。**
Tabs 组件在使用自定义插槽时，想要更改背景色且不需要底部的滑块，没有当前item的active的class，

**描述您想要的解决方案**
当选中当前tab的时候，当scope.index == activeIndex时，在u-tabs__wrapper__nav__item增加一个active的class

**Comment by ijry** [comment]
已增加下版本发布
