### ISSUE TITLE
u-parse组件报错如下

### ISSUE THREAD

**Issue by xiaojiangK** [ijry/uview-plus#60]
u-parse组件报错如下： VM2290:11 TypeError: Cannot read property 'style' of undefined at :29799/appservice/use at :29799/appservice/uni_modules/uview-ui/components/u-parse/node/node.wxml:34(env: Windows,mp,1.06.2209190; lib: 2.25.4) x @ VM2290:11 e @ VM2290:11 l @ VM2290:11 t5K @ VM2327:257 y @ VM22

**Comment by dodu2014** [comment]
已提交了 pr

**Comment by dodu2014** [comment]
#83 已经修复，可以 close 了
