### ISSUE TITLE
action-sheet组件的closeOnClickAction及select方法类型定义问题

### ISSUE THREAD

**Issue by yht-7550** [ijry/uview-plus#600]
**问题描述**
action-sheet组件的closeOnClickAction属性，在props里定义的是Boolean，但是在引用类型包中定义的却是String。
select的方法其实是有回调参数的，但是类型定义里没有返回参数。引发了ts类型报错

**预期行为**
closeOnClickAction类型统一为Boolean，select方法定义为有返回参数

**截图**
closeOnClickAction属性
![image](https://github.com/user-attachments/assets/418d06fa-fcd5-406c-9962-662180f9d990)
![image](https://github.com/user-attachments/assets/b9d99ce3-1204-4e94-91f1-166845df443e)
select方法
![image](https://github.com/user-attachments/assets/9d64818b-0d7a-4f68-a749-4119940d158e)
![image](https://github.com/user-attachments/assets/5d415499-5fcd-4403-80c6-85675e9c8664)

**版本**：
- Visual Studio Code：[1.95.3]
- uview-plus：[3.3.56]

**Comment by ijry** [comment]
下版本发布
