### ISSUE TITLE
uniapp android 真机调试引入up-navbar  [Vue warn]: Property "isH5" was accessed during render but is not defined on instance.  

### ISSUE THREAD

**Issue by XiaoLiz** [ijry/uview-plus#607]
**问题描述**
uniapp android 真机调试引入up-navbar  [Vue warn]: Property "isH5" was accessed during render but is not defined on instance. 
[Vue warn]: Property "isH5" was accessed during render but is not defined on instance.
 at <UStatusBarkey=0bgColor="#ffffff">
 at <UNavbartitle="个人中心"autoBack=trueplaceholder=true>

**复现步骤**
复现该行为的步骤：
1.  vue3 项目中 引入 <up-navbar> <up-navbar/> 组件
2. 运行Android 真机调试
3. 控制台提示 [Vue warn]: Property "isH5" was accessed during render but is not defined on instance. 

**预期行为**
期望Android真机确运行不要导致报错。

**截图**
1.代码注册组件
![image](https://github.com/user-attachments/assets/34e08649-ab14-49b8-8324-ab2febf8b382)

2.报错警告
![image](https://github.com/user-attachments/assets/b64ee9ef-4dc8-4da0-bcd2-d76ef342b538)

**版本（请填写以下信息）**：
- HBuilderX：4.36
- uview-plus：3.3.58
- 开发者工具版本：无

**平台（请填写以下信息）**：
- 平台：Android

**智能手机（请填写以下信息）**：
- 设备：红米k60 pro
- 操作系统：Android 14  小米澎湃OS : 1.0.13.0

**Comment by XiaoLiz** [comment]
经过排查是  u-status-bar.vue  data 属性 isH5 环境判断导致未定义，源代码如下

`vue
<template>
	
	<view
		:style="[style]"
		class="u-status-bar"
		:class="[isH5 && 'u-safe-area-inset-top']"
	>
		<slot />
	</view>
	
</template>

<script>
	import { props } from './props';
	import { mpMixin } from '../../libs/mixin/mpMixin';
	import { mixin } from '../../libs/mixin/mixin';
	import { addUnit, addStyle, deepMerge, sys } from '../../libs/function/index';
	/**
	 * StatbusBar 状态栏占位
	 * @description 本组件主要用于状态填充，比如在自定导航栏的时候，它会自动适配一个恰当的状态栏高度。
	 * @tutorial https://uview-plus.jiangruyi.com/components/statusBar.html
	 * @property {String}			bgColor			背景色 (默认 'transparent' )
	 * @property {String | Object}	customStyle		自定义样式 
	 * @example <u-status-bar></u-status-bar>
	 */
	export default {
		name: 'u-status-bar',
		mixins: [mpMixin, mixin, props],
		data() {
			return {
				// #ifdef H5
				isH5: true
				// #endif
			}
		},
		computed: {
			style() {
				const style = {}
				// 状态栏高度，由于某些安卓和微信开发工具无法识别css的顶部状态栏变量，所以使用js获取的方式
				style.height = addUnit(sys().statusBarHeight, 'px')
				style.backgroundColor = this.bgColor
				return deepMerge(style, addStyle(this.customStyle))
			}
		},
	}
</script>
`

**Comment by ijry** [comment]
fixed@3.3.59
