### ISSUE TITLE
datetimePicker赋值与显示问题

### ISSUE THREAD

**Issue by wu123tao** [ijry/uview-plus#62]
当我给datetimePicker一个默认值的时候，按理说这个组件应该会显示我给它的一个时间显示，但是并没有这样。
而且，当选择时间后，显示的所选时间是时间戳形式，能否根据formatter的形式展示选中的时间数据

**Comment by ijry** [comment]
默认值有效
<img width="314" alt="image" src="https://user-images.githubusercontent.com/3102798/212658406-d8c15767-b237-4ed3-bd44-d3247a62bc27.png">
格式化也有效
<img width="462" alt="image" src="https://user-images.githubusercontent.com/3102798/212668086-07d01fed-91f8-4b76-9c5e-cd751198819a.png">
如仍有问题，请提供最小demo工程。
