### ISSUE TITLE
演示还是不行

### ISSUE THREAD

**Issue by baseSky** [ijry/uview-plus#69]
![image](https://user-images.githubusercontent.com/22609772/208301391-43255f4b-9c1e-47a1-a6f0-efe0007f98c1.png)

**Comment by NEWDSA** [comment]
请使用下面新地址：
https://ijry.github.io/uview-plus/ （需翻墙)

**Comment by NEWDSA** [comment]
> ![image](https://user-images.githubusercontent.com/22609772/208301391-43255f4b-9c1e-47a1-a6f0-efe0007f98c1.png)

请使用下面新地址：
https://ijry.github.io/uview-plus/ （需翻墙)
