### ISSUE TITLE
Picker 选择器 

### ISSUE THREAD

**Issue by NEWDSA** [ijry/uview-plus#70]
picker不显示数据
![image](https://user-images.githubusercontent.com/24479035/208603638-33fefc3e-68a5-45b6-8dd0-6c78948fc823.png)
![image](https://user-images.githubusercontent.com/24479035/208603734-fb22a65c-80ee-4be5-8e75-4aefe9b96ec7.png)
![image](https://user-images.githubusercontent.com/24479035/208603787-c68fef5a-a1f6-47cf-bc4e-ae8da270494b.png)

**Comment by ijry** [comment]
van-picker？
