### ISSUE TITLE
样式scope问题

### ISSUE THREAD

**Issue by BTBMan** [ijry/uview-plus#72]
请问是否可以去掉组件中的样式scope标记 由于组件库使用了scope 在项目中改起样式非常麻烦 vue3+uni的热重载有问题 如果想使覆盖的scope的样式生效（:deep） 就必须重启dev命令

**Comment by BTBMan** [comment]
已通过 `styleIsolation` 解决， 但仍然希望作者可以去掉scoped style.

**Comment by ijry** [comment]
scoped去掉容易污染全局，有组件内样式修改需求可以用deep。
