### ISSUE TITLE
支持TypeScript

### ISSUE THREAD

**Issue by pure1220** [ijry/uview-plus#75]
希望后续能支持ts~作者大大们~

**Comment by ijry** [comment]
目前没计划改造成ts,不过按照部分用户的经历及TS本身的特性，是可以支持在TS环境中使用。

**Comment by dodu2014** [comment]
@pure1220 ts 前，推荐使用 uview-helper vscode扩展（vscode 中搜索 uview-helper），https://marketplace.visualstudio.com/items?itemName=tntgroup.uview-helper

![image](https://user-images.githubusercontent.com/15245544/210695763-2805d6b0-26c7-4f12-8464-c237d3198aff.png)
![image](https://user-images.githubusercontent.com/15245544/210695794-87b22d88-857e-4036-be3a-4d907610069d.png)
![image](https://user-images.githubusercontent.com/15245544/210695809-6115e5e3-4bb6-489b-a74a-fdea14909baf.png)

**Comment by ijry** [comment]
https://www.npmjs.com/package/@ttou/uview-typings

**Comment by ijry** [comment]
> 希望后续能支持ts~作者大大们~

https://www.npmjs.com/package/@ttou/uview-typings
