### ISSUE TITLE
cli创建的项目，dev:mp-weixin，小程序中使用 calendar 报错

### ISSUE THREAD

**Issue by dodu2014** [ijry/uview-plus#77]
SyntaxError: Identifier 'alert' has already been declared  (env: Windows,mp,1.06.2212011; lib: 2.26.2)

只要引入 u-calendar 组件，就报错。

**Comment by rocwong** [comment]
遇到同样的问题，试了几个组件都正常，用u-calendar就报这错。（mac、uniapp vue3+vite）
前些天用echarts也报一样的错，以为是echarts兼容问题，
现在搞不懂是哪的问题了

**Comment by dodu2014** [comment]
作者呢 😎，cell 的 right-icon slot 貌似也有问题

**Comment by dodu2014** [comment]
@rocwong 你在官方qq群里问问，我进不去，人满了。

@ijry @ijry @ijry

**Comment by dodu2014** [comment]
@ijry 解决了吗?

**Comment by ijry** [comment]
> SyntaxError: Identifier 'alert' has already been declared (env: Windows,mp,1.06.2212011; lib: 2.26.2)
> 
> 只要引入 u-calendar 组件，就报错。

mac12.6+Hbuilder3.6.4.20220922+微信开发者工具最新正式版本下，这个未能复线，需要提供demo工程尝试。
<img width="354" alt="image" src="https://user-images.githubusercontent.com/3102798/212460002-e19c313b-ffc9-4156-bd8b-34b69a2a6cea.png">

**Comment by dodu2014** [comment]
@ijry 抱歉，标题没说清除，项目是 cli 方式创建的

**Comment by ijry** [comment]
> @ijry 解决了吗?

right-icon没有问题，使用vue3语法。

<u-cell
  title="单元格"
  isLink
  >
    <template #value>
    <text
    class="u-slot-value"
    >99</text>
    </template>
    <template #right-icon>
    0
    </template>
  </u-cell>
