### ISSUE TITLE
cli 方式创建的uniapp，h5发布模式 cell 点击报错

### ISSUE THREAD

**Issue by dodu2014** [ijry/uview-plus#79]
h5 开发模式 cell 点击正常，build 后，cell 点击报错，如下：

![image](https://user-images.githubusercontent.com/15245544/210748309-89f256dd-6d51-44c0-9214-2381f7cfd3d4.png)

**Comment by huodoushigemi** [comment]
你的 linkType 参数是什么

**Comment by dodu2014** [comment]
没设置，保持默认值 navigateTo

**Comment by dodu2014** [comment]
经查实，这个问题应该时 uniapp 的问题，build 后，uni 为空对象 {}，才导致

**Comment by dodu2014** [comment]
@ijry 根据官方回复，这个问题还是 uview-plus 的问题，已经提交了 pr 给你
