### ISSUE TITLE
3.1.24 cli 项目报错

### ISSUE THREAD

**Issue by dodu2014** [ijry/uview-plus#85]
cli 项目，h5 正常，mp-weixin 和 app 都报错

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/15245544/213490650-225818f2-b8cd-4a65-a4fb-d2b29c9beffa.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/15245544/213490801-d51d12f8-d4b0-4d94-8c24-d3e7862d2119.png">

**Comment by dodu2014** [comment]
非cli项目也是这样，当前示例项目也是如此，hbx 也提示编译错误

运行到小程序：
![image](https://user-images.githubusercontent.com/15245544/213601188-a8ee3c82-3270-4541-9e51-72fb65564297.png)

**Comment by ijry** [comment]
试一下3.1.25

**Comment by kongweigen** [comment]
这个问题没解决吧

**Comment by ijry** [comment]
没这问题啊，你试试github项目下载跑一下。
