### ISSUE TITLE
u-index-list 组件吸顶问题

### ISSUE THREAD

**Issue by RuningPenguin** [ijry/uview-plus#86]
按照文档非nvue页面 u-index-anchor 放在 u-index-item中 小程序吸顶失效
- html代码
<img width="564" alt="image" src="https://user-images.githubusercontent.com/81668708/216255679-ba71f40f-4841-493b-8442-52424a428f10.png">

- 运行效果（mp-weixin）
![屏幕录制2023-02-02 下午2 (2)](https://user-images.githubusercontent.com/81668708/216254918-2f017206-35d6-4f17-90de-9f6f69e4a51e.gif)

- 运行效果（ios-app）
![屏幕录制2023-02-02 下午2](https://user-images.githubusercontent.com/81668708/216254719-c3caea66-b2d9-421b-af88-1d9cf5c1f5bd.gif)

将u-index-anchor 放在 u-index-item外时小程序吸顶效果正常,控制台报错
- html代码
<img width="567" alt="image" src="https://user-images.githubusercontent.com/81668708/216255761-22ae5016-5e7e-4f8d-9425-60e5a58b97ba.png">

- 运行效果（mp-weixin）
![屏幕录制2023-02-02 下午2 (1)](https://user-images.githubusercontent.com/81668708/216254693-9d5a1689-6479-47ee-8779-00c928d484c3.gif)

项目是unapp vue3版本的 主要依赖包如下
![WechatIMG73538](https://user-images.githubusercontent.com/81668708/216253980-cf1a9699-570f-475f-a931-a400a10fd68d.jpeg)

**Comment by lijiexiong-git** [comment]
版本太旧了升级试试吧
