### ISSUE TITLE
setConfig配置没效果欸

### ISSUE THREAD

**Issue by liu-wen-wu** [ijry/uview-plus#88]
`uni.$u.setConfig({
    color: {
      primary:"red"
    },
    // 修改$u.config对象的属性
    config: {
      // 修改默认单位为rpx，相当于执行 uni.$u.config.unit = 'rpx'
      unit: 'rpx'
    },
    // 修改$u.props对象的属性
    props: {
      // 修改radio组件的size参数的默认值，相当于执行 uni.$u.props.radio.size = 30
      button: {
        text:'登录'
      }
      // 其他组件属性配置
      // ......
    }
  })
  uni.$u.props.button.text = '登录'//也没效果
  uni.$u.color.info = 'green'//也没效果` 
![image](https://user-images.githubusercontent.com/109645294/218657483-3c423782-4297-4252-8ecb-8ba6f6601ece.png)
数据变了，但是页面效果没有变化

**Comment by ijry** [comment]
由于uni sdk限制，暂时props的setConfig无法使用。

**Comment by zzl0109** [comment]
可以对源码进行一些改造，比如想要修改tabs组件的默认值，需要把src/uni_modules/uview-plus/components/u-tabs/props.js 文件下defprops 改为 uni.$u.props，但需要在app.use(uview)前执行setConfig
![image](https://github.com/ijry/uview-plus/assets/64246444/5b5dcf63-a666-457e-bb47-96e9124a97aa)

**Comment by ijry** [comment]
已修复
