### ISSUE TITLE
 form 校验报没有then 方法

### ISSUE THREAD

**Issue by dguoqing** [ijry/uview-plus#89]
<template>
    <view class="container">
        <view>
            <img class="img_box" src="../../static/images/zhaomu.png" alt="" />
            <img class="img_box2" src="../../static/images/zhaomu_bg.png" alt="" />
        </view>
        <view class="content">
            <u--form
                labelPosition="top"
                :model="form"
                ref="form1"
                :rules="rules"
                :labelStyle="{ fontSize: '30rpx', width: '600rpx', fontWeight: 600, margin: '0 0 45rpx 0' }"
            >
                <u-form-item label="01  您的名字" prop="userInfo.name" borderBottom>
                    <u--input v-model="form.name"></u--input>
                </u-form-item>
                <u-form-item label="02  您所在的学校及对应校区" prop="userInfo.name" borderBottom>
                    <u--input></u--input>
                </u-form-item>
                <u-form-item label="03  您的联系方式" prop="userInfo.name" borderBottom>
                    <u--input></u--input>
                </u-form-item>

                <u-form-item label="04  您是否有自己的学生团队" prop="userInfo.name" borderBottom>
                    <u-radio-group placement="column">
                        <u-radio
                            :customStyle="{ marginBottom: '8px' }"
                            :key="index"
                            label="是（团队人员规模是）"
                            name="是（团队人员规模是）"
                        >
                        </u-radio>
                        <u-form-item prop="userInfo.name" borderBottom>
                            <u--input border="bottom"></u--input>
                        </u-form-item>

                        <u-radio :customStyle="{ marginBottom: '8px' }" :key="index" label="否" name="否"> </u-radio>
                    </u-radio-group>
                </u-form-item>

                <u-form-item label="05  您是否有创业经验或者校外项目对接经验" prop="userInfo.name" borderBottom>
                    <u-radio-group placement="column">
                        <u-radio
                            :customStyle="{ marginBottom: '8px' }"
                            :key="index"
                            label="是（请简单描述一下）"
                            name="是（请简单描述一下）"
                        >
                        </u-radio>
                        <u-form-item prop="userInfo.name" borderBottom>
                            <u--input border="bottom"></u--input>
                        </u-form-item>

                        <u-radio :customStyle="{ marginBottom: '8px' }" :key="index" label="否" name="否"> </u-radio>
                        <u-radio :customStyle="{ marginBottom: '8px' }" :key="index" label="其他" name="其他">
                        </u-radio>
                        <u-form-item prop="userInfo.name" borderBottom>
                            <u--input border="bottom"></u--input>
                        </u-form-item>
                    </u-radio-group>
                </u-form-item>
            </u--form>

            <img class="img_box2" @click="onSubmit" src="../../static/images/button_zhaomu.png" alt="" />
        </view>
    </view>
</template>

<script >
 import { onPageScroll, onLoad, onShow, onHide, onReachBottom, onNavigationBarButtonTap } from '@dcloudio/uni-app'
 import { ref, onMounted, getCurrentInstance, reactive } from 'vue'
import { useCustomBarState } from '@/hooks'
export default {
    components: {},

    setup() {

        const { ctx } = getCurrentInstance()
        const form = reactive({
            name:'dddd'
        })

        onShow(() => {
            console.log('onShow')
        })

        onMounted(() => {
            console.log('process.env.', process.env.VITE_APP_ENV)
        })

        const onSubmit = () => {
            console.log(ctx.$refs.form1,ctx)
            ctx.$refs.form1.validate().then(res => {
                console.log('re', res)
            })
        }

        return { onSubmit, form }
    },
}
</script>

**Comment by Liuyan4809** [comment]
可能是有没有rules 或者 rules.length 是 0，validate就会返回 undefined
