### ISSUE TITLE
uview-plus引入失败

### ISSUE THREAD

**Issue by Luxii44** [ijry/uview-plus#92]
![image](https://user-images.githubusercontent.com/90958941/222381928-fc371755-7994-4500-999a-6a4e2dffa167.png)
错误内容如下：
![image](https://user-images.githubusercontent.com/90958941/222382154-6d5dd8d5-a29c-40ff-83c6-1e9378142ca8.png)

**Comment by ijry** [comment]
declare module "uview-plus"
