### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by ljb2458** [ijry/uview-plus#94]
如今typescript在前端领域十分重要,希望uview可以对typescript做出更好的支持,这或许会增加uview团队的开发成本,但是这实在是时代所趋

**Comment by canyonwan** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/17877692/224950364-25fcf811-e1c8-4b52-9ff5-01f488698bf2.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/17877692/224950411-14d368d8-d57a-4d7d-8600-89e3a9745f15.png">

**Comment by Ttou** [comment]
@canyonwan @ljb2458 我为 uView2 写了一份类型定义包，这个项目应该也可以用
包名：[@ttou/uview-typings](https://www.npmjs.com/package/@ttou/uview-typings)
参考项目：[uni-template](https://gitee.com/jh_shot/uni-template)
