### ISSUE TITLE
NPM安装完后，使用easycom引入规则，无法变异

### ISSUE THREAD

**Issue by Matrix-X** [ijry/uview-plus#99]
1 先使用了npm install 安装正常，单个页面引入组件也能使用，但是按照官方推荐使用easycom，跑到u-icon这个组件编译就出错了

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/317570/224555441-11361c37-f081-4267-b518-ae35a08c07bc.png">

2 然后我不用npm安装，直接使用HBX来安装，安装完后，引入到main.js，编译也报同样的错误。

**Comment by ijry** [comment]
看着是scss未引入
